/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class simpleskullbedAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new simpleskullbedAddonDeed();
			}
		}

		[ Constructable ]
		public simpleskullbedAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 8708 );
			ac.Hue = 2520;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2708 );
			ac.Hue = 2282;
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 3110 );
			ac.Hue = 2520;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 3111 );
			ac.Hue = 2520;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 3112 );
			ac.Hue = 2520;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 8708 );
			ac.Hue = 2520;
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 8708 );
			ac.Hue = 2520;
			AddComponent( ac, 2, 0, 11 );
			ac = new AddonComponent( 8708 );
			ac.Hue = 2520;
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 8708 );
			ac.Hue = 2520;
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 8708 );
			ac.Hue = 2520;
			AddComponent( ac, 0, 2, 12 );

		}

		public simpleskullbedAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class simpleskullbedAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new simpleskullbedAddon();
			}
		}

		[Constructable]
		public simpleskullbedAddonDeed()
		{
			Name = "simpleskullbed";
		}

		public simpleskullbedAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}