/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class OrnateFountainAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OrnateFountainAddonDeed();
			}
		}

		[ Constructable ]
		public OrnateFountainAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1819 );
			AddComponent( ac, 3, 1, 2 );
			ac = new AddonComponent( 1820 );
			AddComponent( ac, 1, -3, 2 );
			ac = new AddonComponent( 1819 );
			AddComponent( ac, 2, 2, 2 );
			ac = new AddonComponent( 1820 );
			AddComponent( ac, 2, -2, 2 );
			ac = new AddonComponent( 1820 );
			AddComponent( ac, 3, -1, 2 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 1821 );
			AddComponent( ac, -3, 1, 2 );
			ac = new AddonComponent( 1821 );
			AddComponent( ac, -2, 2, 2 );
			ac = new AddonComponent( 1821 );
			AddComponent( ac, -1, 3, 2 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, -1, 0, 3 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, 0, -1, 3 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, 1, -1, 3 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, 1, 1, 3 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -2, 0, 3 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, -1, 1, 3 );
			ac = new AddonComponent( 1819 );
			AddComponent( ac, 1, 3, 2 );
			ac = new AddonComponent( 1818 );
			AddComponent( ac, -1, -3, 2 );
			ac = new AddonComponent( 1818 );
			AddComponent( ac, -2, -2, 2 );
			ac = new AddonComponent( 1818 );
			AddComponent( ac, -3, -1, 2 );
			ac = new AddonComponent( 1813 );
			AddComponent( ac, 2, -3, 2 );
			ac = new AddonComponent( 1813 );
			AddComponent( ac, 3, -2, 2 );
			ac = new AddonComponent( 1813 );
			AddComponent( ac, 4, -1, 2 );
			ac = new AddonComponent( 1812 );
			AddComponent( ac, -4, 1, 2 );
			ac = new AddonComponent( 1812 );
			AddComponent( ac, -3, 2, 2 );
			ac = new AddonComponent( 1812 );
			AddComponent( ac, -2, 3, 2 );
			ac = new AddonComponent( 1812 );
			AddComponent( ac, -1, 4, 2 );
			ac = new AddonComponent( 1811 );
			AddComponent( ac, 4, 1, 2 );
			ac = new AddonComponent( 1811 );
			AddComponent( ac, 3, 2, 2 );
			ac = new AddonComponent( 1811 );
			AddComponent( ac, 2, 3, 2 );
			ac = new AddonComponent( 1811 );
			AddComponent( ac, 1, 4, 2 );
			ac = new AddonComponent( 1810 );
			AddComponent( ac, -1, -4, 2 );
			ac = new AddonComponent( 1810 );
			AddComponent( ac, -2, -3, 2 );
			ac = new AddonComponent( 1813 );
			AddComponent( ac, 1, -4, 2 );
			ac = new AddonComponent( 1810 );
			AddComponent( ac, -3, -2, 2 );
			ac = new AddonComponent( 1810 );
			AddComponent( ac, -4, -1, 2 );
			ac = new AddonComponent( 1805 );
			AddComponent( ac, -4, 0, 2 );
			ac = new AddonComponent( 1804 );
			AddComponent( ac, 0, -4, 2 );
			ac = new AddonComponent( 1803 );
			AddComponent( ac, 4, 0, 2 );
			ac = new AddonComponent( 1802 );
			AddComponent( ac, 0, 4, 2 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 1, -2, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 0, -3, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 3, 0, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, -1, -2, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, -2, -1, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, -3, 0, 5 );
			ac = new AddonComponent( 13456 );
			AddComponent( ac, 0, 0, 23 );
			ac = new AddonComponent( 13591 );
			AddComponent( ac, 0, 0, 13 );
			ac = new AddonComponent( 13591 );
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 13561 );
			AddComponent( ac, 0, 0, 13 );
			ac = new AddonComponent( 13561 );
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 2, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, 0, 3 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -2, 3 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 1, 2, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, -1, 2, 5 );
			ac = new AddonComponent( 4554 );
			AddComponent( ac, -2, 1, 5 );

		}

		public OrnateFountainAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OrnateFountainAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OrnateFountainAddon();
			}
		}

		[Constructable]
		public OrnateFountainAddonDeed()
		{
			Name = "OrnateFountain";
		}

		public OrnateFountainAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}