//Created By Milva
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;

namespace Server.Gumps
{
    public class BarrelLidCapenterGump : Gump
    {
         
      public static void Initialize() 
      {
          CommandSystem.Register("BarrelLidCapenterGump", AccessLevel.GameMaster, new CommandEventHandler(BarrelLidCapenterGump_OnCommand)); 
      } 

      private static void BarrelLidCapenterGump_OnCommand( CommandEventArgs e ) 
      { 
         e.Mobile.SendGump( new BarrelLidCapenterGump( e.Mobile ) ); 
      } 

      public BarrelLidCapenterGump( Mobile owner ) : base( 50,50 ) 
      { 
        
            this.Closable=true;
			this.Disposable=true;
			this.Dragable=true;
			this.Resizable=false;

			AddPage(0);
			AddImageTiled(13, 5, 382, 433, 2524);
			AddImageTiled(7, 5, 388, 25, 2627);
			AddImageTiled(11, 420, 382, 18, 2627);
			AddImage(13, 23, 9265, 1152);
			AddImage(13, 115, 9265, 1152);
            AddItem(12, 390, 7608);
            AddItem(12, 62, 7608);
            AddImage(390, 29, 9303, 1152);
            AddImage(391, 180, 9303, 1152);
			
			AddTextEntry(122, 46, 170, 20, 33, 0, @"    Fish Tank Quest!");


			AddHtml( 34, 95, 346, 281,"<BODY>" +
"<BASEFONT COLOR=Red>Hi good day to you!.. So Nathan sent ye here..<BR><BR>" +
"<BASEFONT COLOR=Red>You are collecting items to make a full keg of paint?.<BR><BR>And you need one of my Paint Lids.<BR><BR>" +
"<BASEFONT COLOR=Red>BR><BR>Well how about we make a deal, yes let's make a deal! .<BR>" +
"<BASEFONT COLOR=Red>I really need a new Heavy Steel Skillet! Hakamie the Master of Stealing has so many items!!<BR><BR>" +
"<BASEFONT COLOR=Red>If you go pay him a visit, I'm betting you will find one at his place <BR><BR>" +
"<BASEFONT COLOR=Red>He lives next to a very large beautiful garden in Tokuno! <BR><BR>" +
"<BASEFONT COLOR=Red>Come back with the Heavy Steel Skillet and my book in which i jotted down<BR><BR>" +
"<BASEFONT COLOR=Red>A clue to the next person will be yours along with the Paint Lid which you need!!<BR><BR>" +
                                              "</BODY>",false,true); 

			AddButton(163, 385, 247, 248, 0, GumpButtonType.Reply, 0);
			AddItem(10, 228, 7608);
			
			


        }

        

        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch(info.ButtonID)
            {
                				case 0:
				{

					break;
				}

            }
        }
    }
}