//Created By Milva
//////////////////////////////////////////////////////////////////////
// Automatically generated by Bradley's GumpStudio and roadmaster's 
// exporter.dll,  Special thanks goes to Daegon whose work the exporter
// was based off of, and Shadow wolf for his Template Idea.
//////////////////////////////////////////////////////////////////////
#define RunUo2_0

using System;
using Server;
using Server.Gumps;
using Server.Network;
using Server.Commands;

namespace Server.Gumps

        {
public class PaintMakerGump : Gump 
   { 
      public static void Initialize() 
      {
          CommandSystem.Register("PaintMakerGump", AccessLevel.GameMaster, new CommandEventHandler(PaintMakerGump_OnCommand)); 
      } 

      private static void PaintMakerGump_OnCommand( CommandEventArgs e ) 
      { 
         e.Mobile.SendGump( new PaintMakerGump( e.Mobile ) ); 
      } 

      public PaintMakerGump( Mobile owner ) : base( 50,50 ) 
      { 
            this.Closable=true;
			this.Disposable=true;
			this.Dragable=true;
			this.Resizable=false;


			AddPage(0);
			AddImageTiled(14, 10, 377, 433, 2524);
			AddImageTiled(9, 6, 388, 13, 1143);
			AddImageTiled(9, 433, 384, 11, 1143);
			AddImage(14, 18, 3005, 1152);
			AddImage(389, 191, 3003, 1152);
			AddImage(14, 187, 3005, 1152);
			AddImage(389, 17, 3003, 1152);
            AddImage(108, 29, 96);
			AddImage(104, 420, 96);
			AddItem(23, 35, 3659, 395);
			AddItem(309, 34, 3659, 380);
			AddItem(57, 37, 5437, 1298);
			AddTextEntry(115, 39, 170, 20, 33, 0,    @"Fish Tank Quest!");


	AddHtml( 34, 90, 346, 281, "<BODY>" +		
 
"<BASEFONT COLOR=Red>Why are you looking at me so strange?<BR><BR>" +
"<BASEFONT COLOR=Red>Oh my clothes! They match the color of the paints I create!<BR>" +
"<BASEFONT COLOR=Red>But...<BR><BR>I have heard of this Red Apple Woven Cloth.<BR>" +
"<BASEFONT COLOR=Red>Which I would love to have,to match the color of the new red paint I just created!.<BR><BR>" +
"<BASEFONT COLOR=Red>Oh,  so you need my jars of blue paint?<BR><BR>" +
"<BASEFONT COLOR=Red>Well if you would be so kind to go get me that Red Apple Woven Cloth.<BR><BR>" +
"<BASEFONT COLOR=Red>I will trade you my paint for the cloth!<BR><BR>" +
"<BASEFONT COLOR=Red>-Teryn the Apple Cloth Weaver is the only one who makes this cloth<BR><BR>" +
"<BASEFONT COLOR=Red>-If you bring this cloth back to me I will give you some of my blue paint<BR><BR>" +
"<BASEFONT COLOR=Red>-Rumor is she is very partial to her cloth so it might take alot of<BR><BR>" +
"<BASEFONT COLOR=Red>-Convincing on your part to bring me back some of that cloth!<BR><BR>" +
"<BASEFONT COLOR=Red>-She lives by the water just past the Minoc Stables<BR><BR>" +
                                               "</BODY>", false,true);

			AddButton(163, 385, 247, 248, 0, GumpButtonType.Reply, 0);
			
			

        }

        

        public override void OnResponse(NetState sender, RelayInfo info)
        {
            Mobile from = sender.Mobile;

            switch(info.ButtonID)
            {
                				case 0:
				{

					break;
				}

            }
        }
    }
}