/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CoffinOpenWithSkeletonSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CoffinOpenWithSkeletonSouthAddonDeed();
			}
		}

		[ Constructable ]
		public CoffinOpenWithSkeletonSouthAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 7276 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 7277 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 7278 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 7272 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 7568 );
			AddComponent( ac, 2, 1, 16 );
			ac = new AddonComponent( 7275 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 7274 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 7270 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 7273 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 7271 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1313 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 7569 );
			AddComponent( ac, 1, 1, 16 );

		}

		public CoffinOpenWithSkeletonSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CoffinOpenWithSkeletonSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CoffinOpenWithSkeletonSouthAddon();
			}
		}

		[Constructable]
		public CoffinOpenWithSkeletonSouthAddonDeed()
		{
			Name = "CoffinOpenWithSkeletonSouth";
		}

		public CoffinOpenWithSkeletonSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}