/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CoffinClosedSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CoffinClosedSouthAddonDeed();
			}
		}

		[ Constructable ]
		public CoffinClosedSouthAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 7290 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 7291 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 7288 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 7289 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 7292 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 7287 );
			AddComponent( ac, 1, 1, 0 );

		}

		public CoffinClosedSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CoffinClosedSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CoffinClosedSouthAddon();
			}
		}

		[Constructable]
		public CoffinClosedSouthAddonDeed()
		{
			Name = "CoffinClosedSouth";
		}

		public CoffinClosedSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}