/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SunkenShipAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SunkenShipAddonDeed();
			}
		}

		[ Constructable ]
		public SunkenShipAddon()
		{
			AddComponent( new AddonComponent( 16044 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 3332 ), 0, 2, 3 );
			AddComponent( new AddonComponent( 16050 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 16040 ), 1, 4, 0 );
			AddComponent( new AddonComponent( 16044 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 4972 ), 0, 1, 3 );
			AddComponent( new AddonComponent( 7023 ), 0, 1, 41 );
			AddComponent( new AddonComponent( 16037 ), -1, 3, 0 );
			AddComponent( new AddonComponent( 16039 ), -1, 4, 0 );
			AddComponent( new AddonComponent( 16044 ), 0, -2, 0 );
			AddComponent( new AddonComponent( 7068 ), 0, -2, 3 );
			AddComponent( new AddonComponent( 16033 ), -1, -2, 0 );
			AddComponent( new AddonComponent( 16033 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 6007 ), -1, -1, 3 );
			AddComponent( new AddonComponent( 7022 ), -1, -1, 23 );
			AddComponent( new AddonComponent( 16092 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 16033 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 16033 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 16030 ), 1, -4, 0 );
			AddComponent( new AddonComponent( 16032 ), 1, -3, 0 );
			AddComponent( new AddonComponent( 16028 ), 1, -5, 0 );
			AddComponent( new AddonComponent( 16094 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 4973 ), 2, -1, 3 );
			AddComponent( new AddonComponent( 7021 ), 2, -1, 21 );
			AddComponent( new AddonComponent( 16100 ), 2, -2, 0 );
			AddComponent( new AddonComponent( 16044 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 6817 ), 1, 0, 8 );
			AddComponent( new AddonComponent( 6986 ), 1, 0, 3 );
			AddComponent( new AddonComponent( 16044 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 16038 ), 1, 3, 0 );
			AddComponent( new AddonComponent( 7020 ), 1, 3, 3 );
			AddComponent( new AddonComponent( 16060 ), 0, 6, 0 );
			AddComponent( new AddonComponent( 16044 ), 0, 3, 0 );
			AddComponent( new AddonComponent( 16093 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 6815 ), 0, -1, 1 );
			AddComponent( new AddonComponent( 6815 ), 0, -1, 22 );
			AddComponent( new AddonComponent( 6817 ), 0, -1, 17 );
			AddComponent( new AddonComponent( 8707 ), 0, -1, 80 );
			AddComponent( new AddonComponent( 16044 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 6005 ), 1, -1, 3 );
			AddComponent( new AddonComponent( 16042 ), 0, 5, 0 );
			AddComponent( new AddonComponent( 4968 ), 0, 5, 0 );
			AddComponent( new AddonComponent( 6924 ), 0, 5, 3 );
			AddComponent( new AddonComponent( 16033 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 16049 ), -2, 2, 0 );
			AddComponent( new AddonComponent( 16044 ), 1, -2, 0 );
			AddComponent( new AddonComponent( 16054 ), -1, 5, 0 );
			AddComponent( new AddonComponent( 1063 ), -3, 0, 47 );
			AddComponent( new AddonComponent( 16049 ), -2, -2, 0 );
			AddComponent( new AddonComponent( 16049 ), -2, 1, 0 );
			AddComponent( new AddonComponent( 16078 ), -2, 1, 0 );
			AddComponent( new AddonComponent( 16049 ), -2, 0, 0 );
			AddComponent( new AddonComponent( 16027 ), -1, -5, 0 );
			AddComponent( new AddonComponent( 16029 ), -1, -4, 0 );
			AddComponent( new AddonComponent( 16031 ), -1, -3, 0 );
			AddComponent( new AddonComponent( 16044 ), 0, -3, 0 );
			AddComponent( new AddonComponent( 16045 ), 0, -4, 0 );
			AddComponent( new AddonComponent( 15941 ), 0, -6, 0 );
			AddComponent( new AddonComponent( 16050 ), 2, 2, 0 );
			AddComponent( new AddonComponent( 1062 ), 3, -1, 36 );
			AddComponent( new AddonComponent( 4963 ), 1, 5, 3 );
			AddComponent( new AddonComponent( 16044 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 3310 ), 1, 2, 42 );
			AddComponent( new AddonComponent( 16050 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 1062 ), 2, 1, 73 );
			AddComponent( new AddonComponent( 16044 ), 0, 4, 0 );
			AddComponent( new AddonComponent( 7070 ), 0, 4, 3 );
			AddComponent( new AddonComponent( 16044 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 6008 ), 0, 0, 3 );
			AddComponent( new AddonComponent( 6987 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 1063 ), 0, 0, 61 );
			AddonComponent ac = null;
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 16050 );
			ac.Hue = 2101;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 16050 );
			ac.Hue = 2101;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 16049 );
			ac.Hue = 2101;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 16078 );
			ac.Hue = 2101;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 16033 );
			ac.Hue = 2101;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 16031 );
			ac.Hue = 2101;
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 16037 );
			ac.Hue = 2101;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 16033 );
			ac.Hue = 2101;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 16045 );
			ac.Hue = 2101;
			AddComponent( ac, 0, -4, 0 );
			ac = new AddonComponent( 16028 );
			ac.Hue = 2101;
			AddComponent( ac, 1, -5, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 16040 );
			ac.Hue = 2101;
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 16038 );
			ac.Hue = 2101;
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 16042 );
			ac.Hue = 2101;
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 16049 );
			ac.Hue = 2101;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 16032 );
			ac.Hue = 2101;
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 16033 );
			ac.Hue = 2101;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 16039 );
			ac.Hue = 2101;
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 16049 );
			ac.Hue = 2101;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 16033 );
			ac.Hue = 2101;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 16049 );
			ac.Hue = 2101;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 16029 );
			ac.Hue = 2101;
			AddComponent( ac, -1, -4, 0 );
			ac = new AddonComponent( 16027 );
			ac.Hue = 2101;
			AddComponent( ac, -1, -5, 0 );
			ac = new AddonComponent( 16030 );
			ac.Hue = 2101;
			AddComponent( ac, 1, -4, 0 );
			ac = new AddonComponent( 15941 );
			ac.Hue = 2101;
			AddComponent( ac, 0, -6, 0 );
			ac = new AddonComponent( 16050 );
			ac.Hue = 2101;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 16093 );
			ac.Hue = 2101;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 16100 );
			ac.Hue = 2101;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 16094 );
			ac.Hue = 2101;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 16054 );
			ac.Hue = 2101;
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 16092 );
			ac.Hue = 2101;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 16033 );
			ac.Hue = 2101;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 16044 );
			ac.Hue = 2101;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 1, 5, 3 );
			ac = new AddonComponent( 4968 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 6008 );
			AddComponent( ac, 0, 0, 3 );
			ac = new AddonComponent( 6007 );
			AddComponent( ac, -1, -1, 3 );
			ac = new AddonComponent( 4973 );
			AddComponent( ac, 2, -1, 3 );
			ac = new AddonComponent( 6005 );
			AddComponent( ac, 1, -1, 3 );
			ac = new AddonComponent( 4972 );
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 7020 );
			AddComponent( ac, 1, 3, 3 );
			ac = new AddonComponent( 7021 );
			AddComponent( ac, 2, -1, 21 );
			ac = new AddonComponent( 7022 );
			AddComponent( ac, -1, -1, 23 );
			ac = new AddonComponent( 7023 );
			AddComponent( ac, 0, 1, 41 );
			ac = new AddonComponent( 6815 );
			ac.Hue = 156;
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 6815 );
			ac.Hue = 156;
			AddComponent( ac, 0, -1, 22 );
			ac = new AddonComponent( 6817 );
			ac.Hue = 156;
			AddComponent( ac, 0, -1, 17 );
			ac = new AddonComponent( 6817 );
			ac.Hue = 156;
			AddComponent( ac, 1, 0, 8 );
			ac = new AddonComponent( 3310 );
			ac.Hue = 156;
			AddComponent( ac, 1, 2, 42 );
			ac = new AddonComponent( 3332 );
			ac.Hue = 156;
			AddComponent( ac, 0, 2, 3 );
			ac = new AddonComponent( 7070 );
			AddComponent( ac, 0, 4, 3 );
			ac = new AddonComponent( 7068 );
			AddComponent( ac, 0, -2, 3 );
			ac = new AddonComponent( 6986 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 6987 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 8707 );
			AddComponent( ac, 0, -1, 80 );
			ac = new AddonComponent( 6924 );
			AddComponent( ac, 0, 5, 3 );
			ac = new AddonComponent( 1062 );
			ac.Hue = 1439;
			AddComponent( ac, 2, 1, 73 );
			ac = new AddonComponent( 1063 );
			ac.Hue = 1439;
			AddComponent( ac, 0, 0, 61 );
			ac = new AddonComponent( 1063 );
			ac.Hue = 1439;
			AddComponent( ac, -3, 0, 47 );
			ac = new AddonComponent( 1062 );
			ac.Hue = 1439;
			AddComponent( ac, 3, -1, 36 );
			ac = new AddonComponent( 16060 );
			ac.Hue = 2101;
			AddComponent( ac, 0, 6, 0 );

		}

		public SunkenShipAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SunkenShipAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SunkenShipAddon();
			}
		}

		[Constructable]
		public SunkenShipAddonDeed()
		{
			Name = "SunkenShip";
		}

		public SunkenShipAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}