
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ATAChristmasTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3286, -2, -2, 0}, {3287, -2, -2, 1}, {3289, -2, -2, 3}// 1	2	3	
			, {11229, 0, 0, 36}, {3886, -2, -1, 22}, {11234, 1, 0, 41}// 7	23	24	
			, {11230, -2, -2, 31}, {11230, -1, -1, 16}, {11232, 0, 1, 41}// 26	28	29	
			, {11231, -1, -1, 33}, {11233, -1, 0, 38}, {11232, -1, -1, 36}// 30	33	35	
			, {11233, 1, 2, 47}, {3864, -2, -2, 20}, {11234, -1, -1, 39}// 36	47	49	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ATAChristmasTreeAddonDeed();
			}
		}

		[ Constructable ]
		public ATAChristmasTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3874, -1, -1, 10, 0, -1, "Christmas Tree Light", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6253, -1, -1, 29, 2569, -1, "Christmas Ball Ornament", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2512, 1, 0, 30, 1260, -1, "Christmas Apple Ornament", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3887, 1, 0, 51, 0, -1, "Christmas Tree Light", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3859, 1, 2, 50, 0, -1, "Christmas Tree Light", 1);// 9
			AddComplexComponent( (BaseAddon) this, 15292, -2, -2, 7, 2819, -1, "garland", 1);// 10
			AddComplexComponent( (BaseAddon) this, 15292, -1, -1, 3, 2819, -1, "garland", 1);// 11
			AddComplexComponent( (BaseAddon) this, 15291, -1, -1, 10, 2819, -1, "garland", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3855, -2, -2, 29, 1153, -1, "Christmas Tree Light", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3865, -2, -2, 26, 0, -1, "Christmas Tree Light", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3883, 1, 0, 46, 0, -1, "Christmas Tree Light", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3887, 0, 2, 47, 0, -1, "Christmas Tree Light", 1);// 16
			AddComplexComponent( (BaseAddon) this, 3882, -2, -2, 31, 0, -1, "Christmas Tree Light", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3888, 1, 0, 35, 0, -1, "Christmas Tree Light", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3876, -2, -2, 26, 0, -1, "Christmas Tree Light", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3875, 1, 0, 45, 0, -1, "Christmas Tree Light", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2512, -1, -1, 21, 1260, -1, "Christmas Apple Ornament", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6253, 1, 0, 35, 2569, -1, "Christmas Ball Ornament", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6253, 0, 2, 37, 2815, -1, "Christmas Ball Ornament", 1);// 25
			AddComplexComponent( (BaseAddon) this, 3874, 2, 2, 50, 0, -1, "Christmas Tree Light", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2512, -2, -1, 22, 1260, -1, "Christmas Apple Ornament", 1);// 31
			AddComplexComponent( (BaseAddon) this, 6253, -1, 0, 28, 2819, -1, "Christmas Ball Ornament", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2512, -1, 0, 19, 1260, -1, "Christmas Apple Ornament", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3875, -1, -1, 22, 0, -1, "Christmas Tree Light", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2512, -2, -2, 31, 1260, -1, "Christmas Apple Ornament", 1);// 38
			AddComplexComponent( (BaseAddon) this, 3882, 2, 0, 38, 0, -1, "Christmas Tree Light", 1);// 39
			AddComplexComponent( (BaseAddon) this, 3884, -2, -2, 30, 0, -1, "Christmas Tree Light", 1);// 40
			AddComplexComponent( (BaseAddon) this, 3885, 1, 0, 30, 0, -1, "Christmas Tree Light", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2512, -2, -2, 25, 1260, -1, "Christmas Apple Ornament", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2512, -1, -2, 22, 1260, -1, "Christmas Apple Ornament", 1);// 43
			AddComplexComponent( (BaseAddon) this, 10299, -2, -2, 38, 1260, -1, "ATA Christmas Tree", 1);// 44
			AddComplexComponent( (BaseAddon) this, 3881, 0, 2, 38, 0, -1, "Christmas Tree Light", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6253, -2, -1, 33, 2569, -1, "Christmas Ball Ornament", 1);// 46
			AddComplexComponent( (BaseAddon) this, 3879, -2, -1, 36, 0, -1, "Christmas Tree Light", 1);// 48

		}

		public ATAChristmasTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ATAChristmasTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ATAChristmasTreeAddon();
			}
		}

		[Constructable]
		public ATAChristmasTreeAddonDeed()
		{
			Name = "ATAChristmasTree";
		}

		public ATAChristmasTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}