
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BridgewithwaterAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13579, -5, -2, 4}, {4963, -7, -3, 2}, {6039, -4, -1, 3}// 1	2	3	
			, {3255, -4, -2, 4}, {6039, -3, -1, 3}, {6039, -5, -1, 3}// 4	5	6	
			, {6060, -5, -2, 3}, {6057, -3, -2, 3}, {6039, -6, -1, 3}// 7	8	9	
			, {6039, -4, -2, 3}, {6054, -7, -2, 3}, {6054, -8, -1, 3}// 10	11	12	
			, {6048, -4, -3, 3}, {6048, -6, -2, 3}, {6053, -3, -3, 3}// 13	14	15	
			, {6054, -5, -3, 3}, {4963, -7, -2, 2}, {4963, -5, -3, 7}// 16	17	18	
			, {4970, -6, -2, 12}, {6060, -7, -1, 3}, {13579, -6, -2, 3}// 19	20	21	
			, {4963, -4, -1, 4}, {4963, -5, -3, 2}, {4963, -6, -3, 2}// 22	23	24	
			, {3252, -7, -2, 5}, {3253, -5, -3, 5}, {4090, -4, -2, 21}// 25	26	27	
			, {3259, -7, -1, 4}, {4963, -6, -3, 7}, {4963, -4, -2, 18}// 28	29	30	
			, {3259, -4, -3, 4}, {6039, -6, 2, 3}, {6039, -4, 1, 3}// 31	32	33	
			, {6039, -4, 0, 3}, {6039, -5, 2, 3}, {6039, -5, 1, 3}// 34	35	36	
			, {6039, -5, 0, 3}, {6039, -4, 3, 3}, {6039, -4, 2, 3}// 37	38	39	
			, {6056, -8, 2, 3}, {6039, -3, 0, 3}, {6039, -3, 2, 3}// 40	41	42	
			, {6039, -3, 3, 3}, {6039, -3, 1, 3}, {6039, -7, 1, 3}// 43	44	45	
			, {6039, -6, 0, 3}, {3258, -4, 2, 3}, {6056, -5, 4, 3}// 46	47	48	
			, {6039, -6, 1, 3}, {6051, -8, 1, 3}, {3332, -7, 1, 4}// 49	50	51	
			, {6059, -5, 3, 3}, {6056, -7, 3, 3}, {3338, -3, 0, 4}// 52	53	54	
			, {6052, -8, 0, 3}, {3336, -5, 1, 5}, {6049, -6, 3, 3}// 55	56	57	
			, {6049, -4, 4, 3}, {6050, -3, 4, 3}, {6039, -7, 0, 3}// 58	59	60	
			, {6059, -7, 2, 3}, {13487, -6, 0, 6}, {13488, -4, 1, 4}// 61	62	63	
			, {3518, -5, 1, 4}, {3256, -6, 2, 4}, {3237, -6, 3, 2}// 64	65	66	
			, {3332, -3, 3, 4}, {6039, 2, -1, 3}, {6039, 1, -1, 3}// 67	68	70	
			, {6039, 3, -1, 3}, {6047, 4, -2, 3}, {6039, 4, -1, 3}// 71	72	74	
			, {6039, -2, -1, 3}, {6047, -2, -2, 3}, {6053, 8, -1, 3}// 75	77	78	
			, {6048, 3, -2, 3}, {6047, 2, -2, 3}, {6053, 5, -2, 3}// 80	83	85	
			, {3220, -2, -2, 3}, {6057, 5, -1, 3}, {3256, 4, -1, 4}// 87	88	89	
			, {6814, -2, -2, 0}, {6814, 2, -1, 6}, {3204, 6, -1, 3}// 90	92	94	
			, {3332, 2, -1, 4}, {6047, 7, -1, 3}, {6048, 6, -1, 3}// 95	96	97	
			, {6039, 6, 2, 3}, {6039, 1, 3, 3}, {6039, 1, 2, 3}// 98	99	100	
			, {6039, 6, 1, 3}, {6039, 3, 0, 3}, {6039, 3, 1, 3}// 101	102	103	
			, {6039, 3, 2, 3}, {6039, 5, 2, 3}, {6039, 5, 1, 3}// 104	105	106	
			, {6039, 5, 0, 3}, {6039, 6, 0, 3}, {6039, 4, 3, 3}// 107	108	109	
			, {6039, 2, 3, 3}, {6039, 4, 2, 3}, {6039, 2, 1, 3}// 110	111	115	
			, {6039, -2, 1, 3}, {6039, -2, 2, 3}, {6039, -2, 3, 3}// 116	117	118	
			, {6039, 1, 1, 3}, {6045, 8, 1, 3}, {6039, 4, 0, 3}// 119	122	125	
			, {6039, 4, 1, 3}, {6039, 2, 2, 3}, {3339, 4, 1, 4}// 126	127	128	
			, {6039, 1, 0, 3}, {3332, 7, 0, 4}, {6049, 3, 4, 3}// 129	130	131	
			, {13451, 2, 0, 3}, {6050, 2, 4, 3}, {6039, 2, 0, 3}// 133	134	135	
			, {6039, 3, 3, 3}, {6055, 5, 4, 3}, {13578, 2, 1, 3}// 136	137	138	
			, {13446, 4, 2, 4}, {6816, -1, 4, 2}, {3220, 2, 4, 4}// 139	140	141	
			, {6050, 4, 4, 3}, {13573, -2, 1, 4}, {6039, 7, 1, 3}// 142	144	146	
			, {6055, 8, 2, 3}, {6039, -2, 0, 3}, {6055, 7, 3, 3}// 150	154	160	
			, {3257, 4, 3, 3}, {6050, 6, 3, 3}, {6049, -2, 4, 3}// 161	162	163	
			, {6058, 5, 3, 3}, {6058, 7, 2, 3}, {3220, -2, 4, 3}// 165	166	167	
			, {6046, 8, 0, 3}, {3259, 2, 2, 4}, {4964, 6, 1, 4}// 168	169	170	
			, {3336, 4, 1, 4}, {3516, 3, 2, 4}, {3255, 6, 2, 4}// 171	173	174	
			, {6039, 7, 0, 3}, {6816, 2, 4, 2}, {2860, -1, 2, 7}// 175	176	177	
			, {2860, -1, 0, 7}, {4555, -1, 1, 9}// 178	179	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BridgewithwaterAddonDeed();
			}
		}

		[ Constructable ]
		public BridgewithwaterAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2145, -2, -1, 7, 1358, -1, "Bridge", 1);// 69
			AddComplexComponent( (BaseAddon) this, 2143, 1, -2, 7, 1358, -1, "Bridge", 1);// 73
			AddComplexComponent( (BaseAddon) this, 2143, -2, -2, 7, 1358, -1, "Bridge", 1);// 76
			AddComplexComponent( (BaseAddon) this, 2145, 1, -1, 7, 1358, -1, "Bridge", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1851, 1, -2, 2, 0, -1, "Bridge", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1981, 1, -1, 5, 1855, -1, "Bridge", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1981, -1, -1, 5, 1855, -1, "Bridge", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1981, 0, -1, 5, 1855, -1, "Bridge", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1851, 0, -2, 2, 0, -1, "Bridge", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1851, -1, -2, 2, 0, -1, "Bridge", 1);// 93
			AddComplexComponent( (BaseAddon) this, 2142, -2, 3, 7, 1358, -1, "Bridge", 1);// 112
			AddComplexComponent( (BaseAddon) this, 2145, -2, 2, 7, 1358, -1, "Bridge", 1);// 113
			AddComplexComponent( (BaseAddon) this, 2145, -2, 1, 7, 1358, -1, "Bridge", 1);// 114
			AddComplexComponent( (BaseAddon) this, 2145, 1, 2, 7, 1358, -1, "Bridge", 1);// 120
			AddComplexComponent( (BaseAddon) this, 2142, 1, 3, 7, 1358, -1, "Bridge", 1);// 121
			AddComplexComponent( (BaseAddon) this, 2145, 1, 0, 7, 1358, -1, "Bridge", 1);// 123
			AddComplexComponent( (BaseAddon) this, 2145, -2, 0, 7, 1358, -1, "Bridge", 1);// 124
			AddComplexComponent( (BaseAddon) this, 2145, 1, 1, 7, 1358, -1, "Bridge", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1849, 1, 4, 2, 0, -1, "Bridge", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1981, 1, 2, 5, 1855, -1, "Bridge", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1981, 1, 0, 5, 1855, -1, "Bridge", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1981, 1, 1, 5, 1855, -1, "Bridge", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1981, 1, 3, 5, 1855, -1, "Bridge", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1981, -1, 2, 5, 1855, -1, "Bridge", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1981, -1, 1, 5, 1855, -1, "Bridge", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1981, -1, 0, 5, 1855, -1, "Bridge", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1981, -1, 3, 5, 1855, -1, "Bridge", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1981, 0, 3, 5, 1855, -1, "Bridge", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1981, 0, 2, 5, 1855, -1, "Bridge", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1981, 0, 1, 5, 1855, -1, "Bridge", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1981, 0, 0, 5, 1855, -1, "Bridge", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1849, -1, 4, 2, 0, -1, "Bridge", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1849, 0, 4, 2, 0, -1, "Bridge", 1);// 172

		}

		public BridgewithwaterAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BridgewithwaterAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BridgewithwaterAddon();
			}
		}

		[Constructable]
		public BridgewithwaterAddonDeed()
		{
			Name = "Bridgewithwater";
		}

		public BridgewithwaterAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}