
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CrystalCouchEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5534, -1, 2, 2}, {5534, -1, -2, 2}// 12	13	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CrystalCouchEastAddonDeed();
			}
		}

		[ Constructable ]
		public CrystalCouchEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 13799, -2, 2, 0, 0, -1, "crystal couch", 1);// 1
			AddComplexComponent( (BaseAddon) this, 13799, -2, -2, 0, 0, -1, "crystal couch", 1);// 2
			AddComplexComponent( (BaseAddon) this, 13791, -2, 1, 3, 0, -1, "crystal couch", 1);// 3
			AddComplexComponent( (BaseAddon) this, 13791, -2, 0, 3, 0, -1, "crystal couch", 1);// 4
			AddComplexComponent( (BaseAddon) this, 13791, -2, -1, 3, 0, -1, "crystal couch", 1);// 5
			AddComplexComponent( (BaseAddon) this, 13778, 0, 2, 0, 0, -1, "crystal couch", 1);// 6
			AddComplexComponent( (BaseAddon) this, 13778, 0, -2, 0, 0, -1, "crystal couch", 1);// 7
			AddComplexComponent( (BaseAddon) this, 13786, 0, -2, 9, 1153, -1, "crystal lamp", 1);// 8
			AddComplexComponent( (BaseAddon) this, 13786, 0, 2, 8, 1153, -1, "crystal lamp", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2330, 0, -2, 10, 91, -1, "crystal lamp", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2330, 0, 2, 9, 91, -1, "crystal lamp", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2914, 0, 1, 0, 191, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2915, 0, -1, 0, 191, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2916, 0, 0, 0, 191, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2760, -1, -2, 0, 91, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2760, -1, -1, 0, 91, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2760, -1, 0, 0, 91, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2760, -1, 1, 0, 91, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2760, -1, 2, 0, 91, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2760, 0, -2, 0, 91, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2760, 0, -1, 0, 1266, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 0, 1266, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2760, 0, 1, 0, 1266, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2760, 0, 2, 0, 91, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2760, 1, -2, 0, 1266, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2760, 1, -1, 0, 1266, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 0, 1266, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 0, 1266, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2760, 1, 2, 0, 1266, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2767, 2, -2, 0, 1266, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2767, 2, -1, 0, 1266, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2767, 2, 0, 0, 1266, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2767, 2, 1, 0, 1266, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2767, 2, 2, 0, 1266, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 5028, -1, 0, 5, 1266, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 5690, -1, -1, 5, 1266, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 5690, -1, 1, 5, 1266, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 13778, -1, 2, 0, 0, -1, "crystal couch", 1);// 40
			AddComplexComponent( (BaseAddon) this, 13778, -1, 1, 0, 0, -1, "crystal couch", 1);// 41
			AddComplexComponent( (BaseAddon) this, 13778, -1, -2, 0, 0, -1, "crystal couch", 1);// 42
			AddComplexComponent( (BaseAddon) this, 13778, -1, 0, 0, 0, -1, "crystal couch", 1);// 43
			AddComplexComponent( (BaseAddon) this, 13778, -1, -1, 0, 0, -1, "crystal couch", 1);// 44
			AddComplexComponent( (BaseAddon) this, 3538, 0, -2, 7, 1266, -1, "crystal couch", 1);// 45
			AddComplexComponent( (BaseAddon) this, 3538, 0, 2, 6, 1266, -1, "crystal couch", 1);// 46

		}

		public CrystalCouchEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CrystalCouchEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CrystalCouchEastAddon();
			}
		}

		[Constructable]
		public CrystalCouchEastAddonDeed()
		{
			Name = "CrystalCouchEast";
		}

		public CrystalCouchEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}