
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CrystalFullBedEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13803, 2, -2, 1}, {13790, -2, -2, 0}, {13792, 2, -2, 0}// 1	3	6	
			, {13791, 2, -1, 0}, {13791, 2, 2, 0}, {13803, 2, 2, 1}// 11	13	41	
			, {13790, -2, 2, 0}, {13792, 2, 2, 0}, {13936, -2, 1, 0}// 62	63	64	
			, {5534, -2, 2, 3}, {5534, -2, -1, 2}// 71	72	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CrystalFullBedEastAddonDeed();
			}
		}

		[ Constructable ]
		public CrystalFullBedEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2766, -2, -2, 0, 91, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2764, 3, -2, 0, 91, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2766, -1, -2, 0, 91, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2766, 2, -2, 0, 91, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2766, 1, -2, 0, 91, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2766, 0, -2, 0, 91, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 13778, -2, 2, 0, 0, -1, "crystal table", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2768, -1, 3, 0, 91, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2760, 1, -1, 0, 91, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13938, 0, 1, 0, 0, -1, "crystal bed", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1116, 1, 1, 0, 90, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 13746, 0, 1, 5, 0, -1, "crystal bed", 1);// 17
			AddComplexComponent( (BaseAddon) this, 13853, -1, 1, 5, 1153, -1, "crystal bed", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13799, -3, -1, 0, 0, -1, "crystal bed", 1);// 19
			AddComplexComponent( (BaseAddon) this, 13936, -1, 1, 0, 0, -1, "crystal bed", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2760, 0, 1, 0, 91, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 5028, -2, 1, 5, 91, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2760, 0, 2, 0, 91, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2760, -2, -1, 0, 91, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2767, 3, 2, 0, 91, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 13853, -1, 0, 5, 1153, -1, "crystal bed", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2767, 3, 0, 0, 91, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2767, 3, 1, 0, 91, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 13746, -2, 1, 5, 0, -1, "crystal bed", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2760, 2, 2, 0, 91, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2768, -2, 3, 0, 91, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2760, -2, 0, 0, 91, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2760, 2, -1, 0, 91, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2760, 2, 0, 0, 91, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2760, -1, 0, 0, 91, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2760, 2, 1, 0, 91, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 13791, -3, 0, 0, 0, -1, "crystal headboard", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2761, 3, 3, 0, 91, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2767, 3, -1, 0, 91, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2760, -1, 1, 0, 91, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2768, 1, 3, 0, 91, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2768, 0, 3, 0, 91, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2760, -1, 2, 0, 91, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 5028, -2, 0, 5, 91, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 13791, -3, 1, 0, 0, -1, "crystal headboard", 1);// 46
			AddComplexComponent( (BaseAddon) this, 13799, -3, 2, 0, 0, -1, "crystal bed", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2760, -2, 2, 0, 91, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2760, 1, 2, 0, 91, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 0, 91, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 0, 91, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 0, 91, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 2760, 0, -1, 0, 91, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 13778, -2, -1, 0, 0, -1, "crystal table", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2760, -1, -1, 0, 91, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2760, -2, 1, 0, 91, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2768, 2, 3, 0, 91, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1116, 1, 0, 0, 90, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 2767, -1, 1, 5, 1150, -1, "crystal bed", 1);// 59
			AddComplexComponent( (BaseAddon) this, 13937, 0, 0, 0, 0, -1, "crystal bed", 1);// 60
			AddComplexComponent( (BaseAddon) this, 13746, -2, 0, 5, 0, -1, "crystal bed", 1);// 61
			AddComplexComponent( (BaseAddon) this, 2330, -2, -1, 10, 91, -1, "crystal lamp", 1);// 65
			AddComplexComponent( (BaseAddon) this, 13786, -2, 2, 9, 1153, -1, "crystal lamp", 1);// 66
			AddComplexComponent( (BaseAddon) this, 13746, 0, 0, 5, 0, -1, "crystal bed", 1);// 67
			AddComplexComponent( (BaseAddon) this, 13786, -2, -1, 9, 1153, -1, "crystal lamp", 1);// 68
			AddComplexComponent( (BaseAddon) this, 2330, -2, 2, 10, 91, -1, "crystal lamp", 1);// 69
			AddComplexComponent( (BaseAddon) this, 2767, -1, 0, 5, 1150, -1, "crystal bed", 1);// 70

		}

		public CrystalFullBedEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CrystalFullBedEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CrystalFullBedEastAddon();
			}
		}

		[Constructable]
		public CrystalFullBedEastAddonDeed()
		{
			Name = "CrystalFullBedEast";
		}

		public CrystalFullBedEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}