
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CrystalFullBedSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13789, -2, -2, 1}, {13789, 2, -2, 1}, {5535, -1, -2, 3}// 44	45	46	
			, {5535, 2, -2, 3}, {13792, 2, 2, 1}, {13792, -1, 2, 1}// 47	66	67	
			, {13803, -2, 2, 2}, {13803, 2, 2, 2}, {13791, -2, 2, 1}// 70	71	72	
			, {13791, 2, 2, 1}// 73	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CrystalFullBedSouthAddonDeed();
			}
		}

		[ Constructable ]
		public CrystalFullBedSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2760, -1, -2, 1, 91, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2760, 0, -2, 1, 91, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2760, 1, -2, 1, 91, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2760, 2, -2, 1, 91, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2760, 2, -1, 1, 91, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2760, 2, 0, 1, 91, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2760, -1, -1, 1, 91, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2760, -1, 0, 1, 91, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2760, 0, -1, 1, 91, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 1, 91, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2760, 1, -1, 1, 91, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 1, 91, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2765, -2, -2, 1, 91, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2765, -2, -1, 1, 91, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2765, -2, 0, 1, 91, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2767, 3, -2, 1, 91, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2767, 3, -1, 1, 91, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2767, 3, 0, 1, 91, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13949, -1, -3, 1, 0, -1, "crystal bed", 1);// 19
			AddComplexComponent( (BaseAddon) this, 13949, 2, -3, 1, 0, -1, "crystal bed", 1);// 20
			AddComplexComponent( (BaseAddon) this, 13938, 1, 0, 0, 0, -1, "crystal bed", 1);// 21
			AddComplexComponent( (BaseAddon) this, 13936, 0, 0, 1, 0, -1, "crystal bed", 1);// 22
			AddComplexComponent( (BaseAddon) this, 13937, 1, -1, 1, 0, -1, "crystal bed", 1);// 23
			AddComplexComponent( (BaseAddon) this, 13937, 1, -2, 1, 0, -1, "crystal bed", 1);// 24
			AddComplexComponent( (BaseAddon) this, 13792, 1, -3, 1, 0, -1, "crystal headboard", 1);// 25
			AddComplexComponent( (BaseAddon) this, 13792, 0, -3, 1, 0, -1, "crystal headboard", 1);// 26
			AddComplexComponent( (BaseAddon) this, 13778, -1, -2, 1, 0, -1, "crystal table", 1);// 27
			AddComplexComponent( (BaseAddon) this, 13778, 2, -2, 1, 0, -1, "crystal table", 1);// 28
			AddComplexComponent( (BaseAddon) this, 13746, 1, 0, 6, 0, -1, "crystal bed", 1);// 29
			AddComplexComponent( (BaseAddon) this, 13746, 0, 0, 6, 0, -1, "crystal bed", 1);// 30
			AddComplexComponent( (BaseAddon) this, 13853, 1, -1, 6, 1153, -1, "crystal bed", 1);// 31
			AddComplexComponent( (BaseAddon) this, 13853, 1, -1, 6, 1153, -1, "crystal bed", 1);// 32
			AddComplexComponent( (BaseAddon) this, 13853, 0, -1, 6, 1153, -1, "crystal bed", 1);// 33
			AddComplexComponent( (BaseAddon) this, 13746, 1, -2, 6, 0, -1, "crystal bed", 1);// 34
			AddComplexComponent( (BaseAddon) this, 13746, 0, -2, 6, 0, -1, "crystal bed", 1);// 35
			AddComplexComponent( (BaseAddon) this, 5029, 0, -2, 6, 91, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 5029, 1, -2, 6, 91, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2768, 0, -1, 6, 1150, -1, "crystal bed", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2768, 1, -1, 6, 1150, -1, "crystal bed", 1);// 39
			AddComplexComponent( (BaseAddon) this, 13786, -1, -2, 10, 1153, -1, "crystal lamp", 1);// 40
			AddComplexComponent( (BaseAddon) this, 13786, 2, -2, 10, 1153, -1, "crystal lamp", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2330, -1, -2, 11, 91, -1, "crystal lamp", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2330, 2, -2, 11, 91, -1, "crystal lamp", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2760, 2, 1, 1, 91, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2760, 2, 2, 1, 91, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2760, -1, 1, 1, 91, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2760, -1, 2, 1, 91, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2760, 1, 2, 1, 91, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 2760, 0, 2, 1, 91, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 2760, 0, 1, 1, 91, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 1, 91, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2765, -2, 1, 1, 91, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2765, -2, 2, 1, 91, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2767, 3, 1, 1, 91, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 2767, 3, 2, 1, 91, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 2768, -1, 3, 1, 91, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 2768, 0, 3, 1, 91, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 2768, 1, 3, 1, 91, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 2768, 2, 3, 1, 91, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 2763, -2, 3, 1, 91, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 2761, 3, 3, 1, 91, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1115, 0, 1, 1, 90, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1115, 1, 1, 1, 90, -1, "", 1);// 69

		}

		public CrystalFullBedSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CrystalFullBedSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CrystalFullBedSouthAddon();
			}
		}

		[Constructable]
		public CrystalFullBedSouthAddonDeed()
		{
			Name = "CrystalFullBedSouth";
		}

		public CrystalFullBedSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}