
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CrystalSinkWestAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CrystalSinkWestAddonDeed();
			}
		}

		[ Constructable ]
		public CrystalSinkWestAddon()
		{



			AddComplexComponent( (BaseAddon) this, 13791, 1, 1, 0, 0, -1, "CrystalSink", 1);// 1
			AddComplexComponent( (BaseAddon) this, 13791, 1, 0, 0, 0, -1, "CrystalSink", 1);// 2
			AddComplexComponent( (BaseAddon) this, 13792, 1, -1, 0, 0, -1, "CrystalSink", 1);// 3
			AddComplexComponent( (BaseAddon) this, 13790, 1, 0, 5, 0, -1, "CrystalSink", 1);// 4
			AddComplexComponent( (BaseAddon) this, 13790, 1, 1, 5, 0, -1, "CrystalSink", 1);// 5
			AddComplexComponent( (BaseAddon) this, 13789, 0, 0, 5, 0, -1, "CrystalSink", 1);// 6
			AddComplexComponent( (BaseAddon) this, 13789, 0, 1, 5, 0, -1, "CrystalSink", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2881, 1, 1, 9, 0, -1, "CrystalSink", 1);// 8
			AddComplexComponent( (BaseAddon) this, 13789, 1, 0, 10, 0, -1, "CrystalSink", 1);// 9
			AddComplexComponent( (BaseAddon) this, 13789, 1, 1, 11, 0, -1, "CrystalSink", 1);// 10
			AddComplexComponent( (BaseAddon) this, 13754, 1, 0, 11, 0, -1, "CrystalSink", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6197, 1, 1, 11, 0, -1, "CrystalSink", 1);// 12
			AddComplexComponent( (BaseAddon) this, 13790, 1, -1, 11, 0, -1, "CrystalSink", 1);// 13
			AddComplexComponent( (BaseAddon) this, 13791, 1, 2, 0, 0, -1, "CrystalSink", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13792, 1, 2, 0, 0, -1, "CrystalSink", 1);// 15
			AddComplexComponent( (BaseAddon) this, 13789, 0, 2, 5, 0, -1, "CrystalSink", 1);// 16
			AddComplexComponent( (BaseAddon) this, 13789, 1, 2, 10, 0, -1, "CrystalSink", 1);// 17
			AddComplexComponent( (BaseAddon) this, 13754, 1, 2, 11, 0, -1, "CrystalSink", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13790, 1, 2, 11, 0, -1, "CrystalSink", 1);// 19

		}

		public CrystalSinkWestAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CrystalSinkWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CrystalSinkWestAddon();
			}
		}

		[Constructable]
		public CrystalSinkWestAddonDeed()
		{
			Name = "CrystalSinkWest";
		}

		public CrystalSinkWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}