
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenWoodsBathtubSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3353, -2, 0, 8}, {3434, 0, 0, 11}, {3473, 0, -1, 7}// 2	3	5	
			, {3473, -2, -1, 5}, {3473, 1, 0, 16}, {3671, -2, 0, 3}// 9	10	24	
			, {12479, 2, 0, 2}, {3412, 0, -1, 6}, {12479, -2, 0, 0}// 30	33	40	
			, {4090, -2, 1, 6}, {11516, 1, -1, 1}, {11516, 0, -1, 1}// 41	46	47	
			, {3264, -1, -1, 6}// 48	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenWoodsBathtubSouthAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenWoodsBathtubSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1824, 1, 2, 1, 0, -1, "Elven Woods Tub", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1824, -2, 1, 1, 0, -1, "Elven Woods Tub", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6212, 0, 0, 3, 0, -1, "water", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1824, 2, 0, 1, 0, -1, "Elven Woods Tub", 1);// 7
			AddComplexComponent( (BaseAddon) this, 9269, -1, 0, 1, 0, -1, "water", 1);// 8
			AddComplexComponent( (BaseAddon) this, 9269, 1, 1, 1, 0, -1, "water", 1);// 11
			AddComplexComponent( (BaseAddon) this, 7386, 0, 1, 3, 1266, -1, "water", 1);// 12
			AddComplexComponent( (BaseAddon) this, 7386, 0, 0, 3, 1266, -1, "water", 1);// 13
			AddComplexComponent( (BaseAddon) this, 7386, -1, 1, 3, 1266, -1, "water", 1);// 14
			AddComplexComponent( (BaseAddon) this, 7386, -1, 0, 3, 1266, -1, "water", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 5, 0, -1, "bubbles", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1824, -2, -1, 1, 0, -1, "Elven Woods Tub", 1);// 17
			AddComplexComponent( (BaseAddon) this, 11581, 1, -1, 4, 0, -1, "Elven Woods Tub", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1836, -2, 2, 1, 0, -1, "Elven Woods Tub", 1);// 19
			AddComplexComponent( (BaseAddon) this, 9269, 0, 0, 1, 0, -1, "water", 1);// 20
			AddComplexComponent( (BaseAddon) this, 9269, 1, 0, 1, 0, -1, "water", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1824, -1, -1, 1, 0, -1, "Elven Woods Tub", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2706, -1, 2, 5, 1150, -1, "towel", 1);// 23
			AddComplexComponent( (BaseAddon) this, 9269, 0, 1, 1, 0, -1, "water", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6197, 0, 0, 7, 0, -1, "Faucet", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1826, 0, 2, 1, 0, -1, "Elven Woods Tub", 1);// 27
			AddComplexComponent( (BaseAddon) this, 5155, 2, 1, 7, 1150, -1, "soap", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1835, 2, 2, 1, 0, -1, "Elven Woods Tub", 1);// 29
			AddComplexComponent( (BaseAddon) this, 11581, 0, -1, 4, 0, -1, "Elven Woods Tub", 1);// 31
			AddComplexComponent( (BaseAddon) this, 9429, 2, 1, 6, 1150, -1, "Wash Cloth", 1);// 32
			AddComplexComponent( (BaseAddon) this, 11581, -1, -1, 4, 0, -1, "Elven Woods Tub", 1);// 34
			AddComplexComponent( (BaseAddon) this, 7386, 1, 0, 3, 1266, -1, "water", 1);// 35
			AddComplexComponent( (BaseAddon) this, 7386, 1, 1, 3, 1266, -1, "water", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1824, 2, -1, 1, 0, -1, "Elven Woods Tub", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1824, -2, 0, 1, 0, -1, "Elven Woods Tub", 1);// 38
			AddComplexComponent( (BaseAddon) this, 9269, -1, 1, 1, 0, -1, "water", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1824, 1, -1, 1, 0, -1, "Elven Woods Tub", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1824, 0, -1, 1, 0, -1, "Elven Woods Tub", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1824, 2, 1, 1, 0, -1, "Elven Woods Tub", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1824, -1, 2, 1, 0, -1, "Elven Woods Tub", 1);// 45

		}

		public ElvenWoodsBathtubSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenWoodsBathtubSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenWoodsBathtubSouthAddon();
			}
		}

		[Constructable]
		public ElvenWoodsBathtubSouthAddonDeed()
		{
			Name = "ElvenWoodsBathtubSouth";
		}

		public ElvenWoodsBathtubSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}