
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenCampingMattAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenCampingMattAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenCampingMattAddon()
		{



			AddComplexComponent( (BaseAddon) this, 4581, 1, -1, 0, 0, -1, "ElvenCampingMatt", 1);// 1
			AddComplexComponent( (BaseAddon) this, 4581, 1, 0, 0, 0, -1, "ElvenCampingMatt", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4581, 1, 1, 0, 0, -1, "ElvenCampingMatt", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4581, 1, 2, 0, 0, -1, "ElvenCampingMatt", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4581, 0, -1, 0, 0, -1, "ElvenCampingMatt", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4581, 0, 0, 0, 0, -1, "ElvenCampingMatt", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4581, 0, 1, 0, 0, -1, "ElvenCampingMatt", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4581, 0, 2, 0, 0, -1, "ElvenCampingMatt", 1);// 8
			AddComplexComponent( (BaseAddon) this, 5690, 0, 2, 2, 1159, -1, "ElvenCampingMatt", 1);// 9
			AddComplexComponent( (BaseAddon) this, 5690, 1, 2, 2, 1159, -1, "ElvenCampingMatt", 1);// 10
			AddComplexComponent( (BaseAddon) this, 5035, 1, 2, 5, 2218, -1, "ElvenCampingMatt", 1);// 11
			AddComplexComponent( (BaseAddon) this, 5035, 0, 2, 5, 2218, -1, "ElvenCampingMatt", 1);// 12

		}

		public ElvenCampingMattAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenCampingMattAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenCampingMattAddon();
			}
		}

		[Constructable]
		public ElvenCampingMattAddonDeed()
		{
			Name = "ElvenCampingMatt";
		}

		public ElvenCampingMattAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}