
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenWoodsBathtubEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3353, 0, -1, 13}, {3434, 1, 0, 17}, {3412, -1, 0, 10}// 3	5	6	
			, {12479, 0, -1, 3}, {11580, -1, 0, 4}, {11580, -1, -1, 4}// 10	11	13	
			, {11514, -1, 0, 1}, {11580, -1, 1, 4}, {12479, 0, 3, 0}// 29	31	34	
			, {3473, 0, 1, 16}, {4090, 1, 2, 6}, {3673, 0, 2, 5}// 35	37	38	
			, {1824, 0, 2, 1}, {3353, 0, 2, 10}, {3473, -1, 1, 6}// 41	45	46	
			, {11514, -1, 1, 1}, {3264, -1, 1, 8}// 47	48	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenWoodsBathtubEastAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenWoodsBathtubEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1824, -1, -2, 1, 0, -1, "Elven Woods Tub", 1);// 1
			AddComplexComponent( (BaseAddon) this, 9430, 1, -2, 6, 1150, -1, "wash cloth", 1);// 2
			AddComplexComponent( (BaseAddon) this, 9269, 0, -1, 1, 0, -1, "water", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2669, 2, -1, 6, 1153, -1, "towel", 1);// 7
			AddComplexComponent( (BaseAddon) this, 7386, 1, -1, 3, 1266, -1, "water", 1);// 8
			AddComplexComponent( (BaseAddon) this, 7386, 1, 0, 3, 1266, -1, "water", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1837, 2, -2, 1, 0, -1, "Elven Woods Tub", 1);// 12
			AddComplexComponent( (BaseAddon) this, 9269, 0, 0, 1, 0, -1, "water", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3577, 0, 0, 4, 0, -1, "bubbles", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7386, 0, -1, 3, 1266, -1, "water", 1);// 16
			AddComplexComponent( (BaseAddon) this, 9269, 1, -1, 1, 0, -1, "water", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1827, 2, 0, 1, 0, -1, "Elven Woods Tub", 1);// 18
			AddComplexComponent( (BaseAddon) this, 9269, 1, 0, 1, 0, -1, "water", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1824, 1, -2, 1, 0, -1, "Elven Woods Tub", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1824, 0, -2, 1, 0, -1, "Elven Woods Tub", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1824, 2, -1, 1, 0, -1, "Elven Woods Tub", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1824, -1, 0, 1, 0, -1, "Elven Woods Tub", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1824, -1, -1, 1, 0, -1, "Elven Woods Tub", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6194, 0, 0, 6, 0, -1, "Faucet", 1);// 25
			AddComplexComponent( (BaseAddon) this, 7386, 0, 0, 3, 1266, -1, "water", 1);// 26
			AddComplexComponent( (BaseAddon) this, 5154, 1, -2, 6, 1150, -1, "soap", 1);// 27
			AddComplexComponent( (BaseAddon) this, 6212, 0, 0, 2, 0, -1, "water", 1);// 28
			AddComplexComponent( (BaseAddon) this, 7386, 0, 1, 3, 1266, -1, "water", 1);// 30
			AddComplexComponent( (BaseAddon) this, 7386, 1, 1, 3, 1266, -1, "water", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1824, 1, 2, 1, 0, -1, "Elven Woods Tub", 1);// 33
			AddComplexComponent( (BaseAddon) this, 9269, 0, 1, 1, 0, -1, "water", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1835, 2, 2, 1, 0, -1, "Elven Woods Tub", 1);// 39
			AddComplexComponent( (BaseAddon) this, 9269, 1, 1, 1, 0, -1, "water", 1);// 40
			AddComplexComponent( (BaseAddon) this, 1824, 2, 1, 1, 0, -1, "Elven Woods Tub", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1824, -1, 1, 1, 0, -1, "Elven Woods Tub", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1824, -1, 2, 1, 0, -1, "Elven Woods Tub", 1);// 44

		}

		public ElvenWoodsBathtubEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenWoodsBathtubEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenWoodsBathtubEastAddon();
			}
		}

		[Constructable]
		public ElvenWoodsBathtubEastAddonDeed()
		{
			Name = "ElvenWoodsBathtubEast";
		}

		public ElvenWoodsBathtubEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}