
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenWoodsCouchEastAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenWoodsCouchEastAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenWoodsCouchEastAddon()
		{



			AddComplexComponent( (BaseAddon) this, 2760, 0, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 1
			AddComplexComponent( (BaseAddon) this, 10699, -1, 0, 5, 0, -1, "Elven Woods Couch", 1);// 2
			AddComplexComponent( (BaseAddon) this, 11580, -2, -2, 5, 0, -1, "Elven Woods Couch", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1824, -1, -1, 0, 0, -1, "Elven Woods Couch", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3412, -2, -1, 9, 0, -1, "Elven Woods Couch", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2330, -1, -2, 13, 0, -1, "Elven Woods Couch", 1);// 6
			AddComplexComponent( (BaseAddon) this, 8755, -1, -2, 10, 0, -1, "Elven Woods Couch", 1);// 7
			AddComplexComponent( (BaseAddon) this, 8755, -1, 1, 10, 0, -1, "Elven Woods Couch", 1);// 8
			AddComplexComponent( (BaseAddon) this, 5168, -1, -2, 11, 0, 1, "Elven Woods Couch", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3473, 0, 1, 5, 0, -1, "Elven Woods Couch", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2915, 0, -1, 0, 2107, -1, "Elven Woods Couch", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3473, 0, -2, 5, 0, -1, "Elven Woods Couch", 1);// 12
			AddComplexComponent( (BaseAddon) this, 11580, -2, 1, 5, 0, -1, "Elven Woods Couch", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1824, 0, -2, 0, 0, -1, "Elven Woods Couch", 1);// 14
			AddComplexComponent( (BaseAddon) this, 5168, -1, 1, 11, 0, 1, "Elven Woods Couch", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3412, -2, 0, 8, 0, -1, "Elven Woods Couch", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2330, -1, 1, 13, 0, -1, "Elven Woods Couch", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3459, -2, 2, 0, 0, -1, "Elven Woods Couch", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 19
			AddComplexComponent( (BaseAddon) this, 11580, -2, 0, 5, 0, -1, "Elven Woods Couch", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1824, 0, 1, 0, 0, -1, "Elven Woods Couch", 1);// 21
			AddComplexComponent( (BaseAddon) this, 3473, -2, -2, 6, 0, -1, "Elven Woods Couch", 1);// 22
			AddComplexComponent( (BaseAddon) this, 3673, -1, -2, 1, 0, -1, "Elven Woods Couch", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2914, 0, 0, 0, 2107, -1, "Elven Woods Couch", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2760, 1, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 26
			AddComplexComponent( (BaseAddon) this, 3473, -1, 0, 15, 0, -1, "Elven Woods Couch", 1);// 27
			AddComplexComponent( (BaseAddon) this, 7949, -1, -1, 5, 0, -1, "Elven Woods Couch", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2760, 1, -2, 0, 1368, -1, "Elven Woods Couch", 1);// 29
			AddComplexComponent( (BaseAddon) this, 7949, -1, 0, 5, 0, -1, "Elven Woods Couch", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1824, -1, -2, 0, 0, -1, "Elven Woods Couch", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3671, -1, 1, 1, 0, -1, "Elven Woods Couch", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1824, -1, 0, 0, 0, -1, "Elven Woods Couch", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1824, -1, 1, 0, 0, -1, "Elven Woods Couch", 1);// 34
			AddComplexComponent( (BaseAddon) this, 11580, -2, -1, 5, 0, -1, "Elven Woods Couch", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 0, 1368, -1, "Elven Woods Couch", 1);// 36
			AddComplexComponent( (BaseAddon) this, 10699, -1, -1, 5, 0, -1, "Elven Woods Couch", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2767, 2, 1, 0, 1368, -1, "Elven Woods Couch", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2767, 2, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2767, 2, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2767, 2, -2, 0, 1368, -1, "Elven Woods Couch", 1);// 41

		}

		public ElvenWoodsCouchEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenWoodsCouchEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenWoodsCouchEastAddon();
			}
		}

		[Constructable]
		public ElvenWoodsCouchEastAddonDeed()
		{
			Name = "ElvenWoodsCouchEast";
		}

		public ElvenWoodsCouchEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}