
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenBedNorthAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenBedNorthAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenBedNorthAddon()
		{



			AddComplexComponent( (BaseAddon) this, 3125, 1, -2, 0, 2218, -1, "ElvenBedNorth", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3125, 1, -1, 0, 2218, -1, "ElvenBedNorth", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3125, 1, 0, 0, 2218, -1, "ElvenBedNorth", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3125, 1, 1, 0, 2218, -1, "ElvenBedNorth", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4583, -1, -2, 2, 0, -1, "ElvenBedNorth", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4583, -1, -1, 2, 0, -1, "ElvenBedNorth", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4583, -1, 0, 2, 0, -1, "ElvenBedNorth", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4583, -1, 1, 2, 0, -1, "ElvenBedNorth", 1);// 8
			AddComplexComponent( (BaseAddon) this, 4583, 0, -2, 2, 0, -1, "ElvenBedNorth", 1);// 9
			AddComplexComponent( (BaseAddon) this, 4583, 0, -1, 2, 0, -1, "ElvenBedNorth", 1);// 10
			AddComplexComponent( (BaseAddon) this, 4583, 0, 0, 2, 0, -1, "ElvenBedNorth", 1);// 11
			AddComplexComponent( (BaseAddon) this, 4583, 0, 1, 2, 0, -1, "ElvenBedNorth", 1);// 12
			AddComplexComponent( (BaseAddon) this, 4583, 1, -2, 2, 0, -1, "ElvenBedNorth", 1);// 13
			AddComplexComponent( (BaseAddon) this, 4583, 1, -1, 2, 0, -1, "ElvenBedNorth", 1);// 14
			AddComplexComponent( (BaseAddon) this, 4583, 1, 0, 2, 0, -1, "ElvenBedNorth", 1);// 15
			AddComplexComponent( (BaseAddon) this, 4583, 1, 1, 2, 0, -1, "ElvenBedNorth", 1);// 16
			AddComplexComponent( (BaseAddon) this, 4586, 1, 2, 2, 0, -1, "ElvenBedNorth", 1);// 17
			AddComplexComponent( (BaseAddon) this, 4586, 0, 2, 2, 0, -1, "ElvenBedNorth", 1);// 18
			AddComplexComponent( (BaseAddon) this, 4586, -1, 2, 2, 0, -1, "ElvenBedNorth", 1);// 19
			AddComplexComponent( (BaseAddon) this, 7138, -1, 2, 0, 0, -1, "ElvenBedNorth", 1);// 20
			AddComplexComponent( (BaseAddon) this, 7138, 1, 2, 0, 0, -1, "ElvenBedNorth", 1);// 21
			AddComplexComponent( (BaseAddon) this, 7138, 0, 2, 0, 0, -1, "ElvenBedNorth", 1);// 22
			AddComplexComponent( (BaseAddon) this, 3377, -2, 2, 0, 0, -1, "ElvenBedNorth", 1);// 23
			AddComplexComponent( (BaseAddon) this, 3377, 2, 2, 0, 0, -1, "ElvenBedNorth", 1);// 24
			AddComplexComponent( (BaseAddon) this, 3235, 2, -2, 0, 0, -1, "ElvenBedNorth", 1);// 25
			AddComplexComponent( (BaseAddon) this, 3234, -2, -2, 0, 0, -1, "ElvenBedNorth", 1);// 26
			AddComplexComponent( (BaseAddon) this, 3380, 1, 0, 3, 0, -1, "ElvenBedNorth", 1);// 27
			AddComplexComponent( (BaseAddon) this, 3380, 0, 1, 3, 0, -1, "ElvenBedNorth", 1);// 28
			AddComplexComponent( (BaseAddon) this, 7949, -1, -1, 5, 0, -1, "ElvenBedNorth", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3239, -1, -3, 0, 0, -1, "ElvenBedNorth", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3239, 1, -3, 0, 0, -1, "ElvenBedNorth", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3239, 0, -3, 0, 0, -1, "ElvenBedNorth", 1);// 32
			AddComplexComponent( (BaseAddon) this, 3257, 0, 3, 0, 0, -1, "ElvenBedNorth", 1);// 33
			AddComplexComponent( (BaseAddon) this, 3257, 1, 3, 0, 0, -1, "ElvenBedNorth", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3257, -1, 3, 0, 0, -1, "ElvenBedNorth", 1);// 35

		}

		public ElvenBedNorthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenBedNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenBedNorthAddon();
			}
		}

		[Constructable]
		public ElvenBedNorthAddonDeed()
		{
			Name = "ElvenBedNorth";
		}

		public ElvenBedNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}