
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenWoodsKitchenTableSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2931, 0, 0, 1}, {2931, 0, 1, 1}, {12479, -2, 2, 1}// 5	6	9	
			, {6869, -2, 2, 7}, {2903, -1, -1, 0}, {2903, 0, -1, 0}// 10	12	13	
			, {2905, -1, 2, 0}, {2905, 0, 2, 0}, {12479, 2, 1, 1}// 14	15	20	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenWoodsKitchenTableSouthAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenWoodsKitchenTableSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 933, -2, 1, 0, 0, -1, "Elven Woods Table", 1);// 1
			AddComplexComponent( (BaseAddon) this, 933, -2, 0, 0, 0, -1, "Elven Woods Table", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2931, -1, 0, 1, 0, -1, "Elven Woods Table", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2931, -1, 1, 1, 0, -1, "Elven Woods Table", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2931, -2, 0, 1, 0, -1, "Elven Woods Table", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2931, -2, 1, 1, 0, -1, "Elven Woods Table", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6943, -2, 2, 11, 1371, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 933, 1, 1, 0, 0, -1, "Elven Woods Table", 1);// 16
			AddComplexComponent( (BaseAddon) this, 933, 1, 0, 0, 0, -1, "Elven Woods Table", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2931, 1, 0, 1, 0, -1, "Elven Woods Table", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2931, 1, 1, 1, 0, -1, "Elven Woods Table", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6943, 2, 1, 14, 1371, -1, "", 1);// 21

		}

		public ElvenWoodsKitchenTableSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenWoodsKitchenTableSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenWoodsKitchenTableSouthAddon();
			}
		}

		[Constructable]
		public ElvenWoodsKitchenTableSouthAddonDeed()
		{
			Name = "ElvenWoodsKitchenTableSouth";
		}

		public ElvenWoodsKitchenTableSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}