
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenWoodsCouchNorthAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenWoodsCouchNorthAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenWoodsCouchNorthAddon()
		{



			AddComplexComponent( (BaseAddon) this, 2760, -2, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2760, -1, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2766, -1, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2766, -2, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2760, -2, 1, 0, 1370, -1, "Elven Woods Couch", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2760, -1, 1, 0, 1368, -1, "Elven Woods Couch", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2760, -1, 2, 0, 1370, -1, "Elven Woods Couch", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1824, -2, 2, 0, 0, -1, "Elven Woods Couch", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2922, -1, 1, 0, 2107, -1, "Elven Woods Couch", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1824, -1, 2, 0, 0, -1, "Elven Woods Couch", 1);// 10
			AddComplexComponent( (BaseAddon) this, 11581, -1, 2, 4, 0, -1, "Elven Woods Couch", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1824, -2, 1, 0, 0, -1, "Elven Woods Couch", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3673, -2, 2, 0, 0, -1, "Elven Woods Couch", 1);// 13
			AddComplexComponent( (BaseAddon) this, 8755, -2, 2, 9, 0, -1, "Elven Woods Couch", 1);// 14
			AddComplexComponent( (BaseAddon) this, 5168, -2, 2, 10, 0, 1, "Elven Woods Couch", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2330, -2, 2, 12, 0, -1, "Elven Woods Couch", 1);// 16
			AddComplexComponent( (BaseAddon) this, 7949, -1, 2, 6, 0, -1, "Elven Woods Couch", 1);// 17
			AddComplexComponent( (BaseAddon) this, 10699, -1, 2, 5, 0, -1, "Elven Woods Couch", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3473, -2, 1, 5, 0, -1, "Elven Woods Couch", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2760, 2, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2760, 3, 0, 0, 1368, -1, "Elven Woods Couch", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2766, 3, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2766, 2, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2766, 1, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2766, 0, -1, 0, 1368, -1, "Elven Woods Couch", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2760, 0, 1, 0, 1368, -1, "Elven Woods Couch", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2760, 0, 2, 0, 1370, -1, "Elven Woods Couch", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 0, 1368, -1, "Elven Woods Couch", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2760, 1, 2, 0, 1370, -1, "Elven Woods Couch", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2760, 2, 1, 0, 1368, -1, "Elven Woods Couch", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2760, 2, 2, 0, 1370, -1, "Elven Woods Couch", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2760, 3, 1, 0, 1370, -1, "Elven Woods Couch", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1824, 3, 1, 0, 0, -1, "Elven Woods Couch", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2922, 0, 1, 0, 2107, -1, "Elven Woods Couch", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2922, 1, 1, 0, 2107, -1, "Elven Woods Couch", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1824, 2, 2, 0, 0, -1, "Elven Woods Couch", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1824, 1, 2, 0, 0, -1, "Elven Woods Couch", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1824, 0, 2, 0, 0, -1, "Elven Woods Couch", 1);// 40
			AddComplexComponent( (BaseAddon) this, 11581, 0, 2, 4, 0, -1, "Elven Woods Couch", 1);// 41
			AddComplexComponent( (BaseAddon) this, 11581, 1, 2, 4, 0, -1, "Elven Woods Couch", 1);// 42
			AddComplexComponent( (BaseAddon) this, 11544, 2, 2, 4, 0, -1, "Elven Woods Couch", 1);// 43
			AddComplexComponent( (BaseAddon) this, 1824, 3, 2, 0, 0, -1, "Elven Woods Couch", 1);// 44
			AddComplexComponent( (BaseAddon) this, 3671, 3, 2, 0, 0, -1, "Elven Woods Couch", 1);// 45
			AddComplexComponent( (BaseAddon) this, 8755, 3, 2, 9, 0, -1, "Elven Woods Couch", 1);// 46
			AddComplexComponent( (BaseAddon) this, 5168, 3, 2, 9, 0, 1, "Elven Woods Couch", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2330, 3, 2, 11, 0, -1, "Elven Woods Couch", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2920, 2, 1, 0, 2107, -1, "Elven Woods Couch", 1);// 49
			AddComplexComponent( (BaseAddon) this, 7949, 1, 2, 6, 0, -1, "Elven Woods Couch", 1);// 50
			AddComplexComponent( (BaseAddon) this, 7949, 0, 2, 6, 0, -1, "Elven Woods Couch", 1);// 51
			AddComplexComponent( (BaseAddon) this, 10699, 1, 2, 5, 0, -1, "Elven Woods Couch", 1);// 52
			AddComplexComponent( (BaseAddon) this, 10699, 2, 2, 5, 0, -1, "Elven Woods Couch", 1);// 53
			AddComplexComponent( (BaseAddon) this, 10699, 0, 2, 5, 0, -1, "Elven Woods Couch", 1);// 54
			AddComplexComponent( (BaseAddon) this, 3412, 2, 2, 8, 0, -1, "Elven Woods Couch", 1);// 55
			AddComplexComponent( (BaseAddon) this, 3473, 2, 2, 7, 0, -1, "Elven Woods Couch", 1);// 56
			AddComplexComponent( (BaseAddon) this, 3473, 3, 1, 5, 0, -1, "Elven Woods Couch", 1);// 57

		}

		public ElvenWoodsCouchNorthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenWoodsCouchNorthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenWoodsCouchNorthAddon();
			}
		}

		[Constructable]
		public ElvenWoodsCouchNorthAddonDeed()
		{
			Name = "ElvenWoodsCouchNorth";
		}

		public ElvenWoodsCouchNorthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}