
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ElvenWoodsGrillSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11581, 0, 0, 0}, {11581, 1, 0, 0}, {1305, 0, 1, 0}// 1	2	9	
			, {1305, -1, 1, 0}, {1305, 1, 1, 0}, {190, -2, 1, 0}// 10	11	18	
			, {7828, 1, 1, 6}, {3136, 2, 1, 6}, {3132, -1, 1, 6}// 22	23	24	
			, {3458, 1, 1, 15}, {3473, 0, 0, 6}// 25	26	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ElvenWoodsGrillSouthAddonDeed();
			}
		}

		[ Constructable ]
		public ElvenWoodsGrillSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 11587, 2, 0, 0, 0, 1, "Elven Woods Grill", 1);// 3
			AddComplexComponent( (BaseAddon) this, 11587, -1, 0, 0, 0, 1, "Elven Woods Grill", 1);// 4
			AddComplexComponent( (BaseAddon) this, 11542, 0, 0, 0, 0, -1, "Elven Woods Grill", 1);// 5
			AddComplexComponent( (BaseAddon) this, 11543, 1, 0, 0, 0, -1, "Elven Woods Grill", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1305, 2, 1, 6, 0, -1, "Elven Woods Grill", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1305, -1, 1, 6, 0, -1, "Elven Woods Grill", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6571, 1, 1, 6, 0, 1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6571, 0, 1, 5, 0, 1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 7386, 1, 1, 7, 991, -1, "Grill", 1);// 14
			AddComplexComponent( (BaseAddon) this, 7386, 0, 1, 7, 991, -1, "Grill", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2528, -1, 1, 6, 991, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 189, 2, 1, 0, 0, -1, "Elven Woods Grill", 1);// 17
			AddComplexComponent( (BaseAddon) this, 191, 0, 1, 0, 0, -1, "Elven Woods Grill", 1);// 19
			AddComplexComponent( (BaseAddon) this, 191, 1, 1, 0, 0, -1, "Elven Woods Grill", 1);// 20
			AddComplexComponent( (BaseAddon) this, 189, -1, 1, 0, 0, -1, "Elven Woods Grill", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6943, 2, 1, 6, 1371, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 11518, 0, 1, 3, 0, 1, "", 1);// 28

		}

		public ElvenWoodsGrillSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ElvenWoodsGrillSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ElvenWoodsGrillSouthAddon();
			}
		}

		[Constructable]
		public ElvenWoodsGrillSouthAddonDeed()
		{
			Name = "ElvenWoodsGrillSouth";
		}

		public ElvenWoodsGrillSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}