
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class EvilTableEastWestAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EvilTableEastWestAddonDeed();
			}
		}

		[ Constructable ]
		public EvilTableEastWestAddon()
		{



			AddComplexComponent( (BaseAddon) this, 13900, -2, 1, 0, 0, -1, "EvilTable", 1);// 1
			AddComplexComponent( (BaseAddon) this, 13900, -2, 0, 0, 0, -1, "EvilTable", 1);// 2
			AddComplexComponent( (BaseAddon) this, 4614, -1, 0, 0, 1109, -1, "EvilTable", 1);// 3
			AddComplexComponent( (BaseAddon) this, 4614, 0, 0, 0, 1109, -1, "EvilTable", 1);// 4
			AddComplexComponent( (BaseAddon) this, 4614, 1, 0, 0, 1109, -1, "EvilTable", 1);// 5
			AddComplexComponent( (BaseAddon) this, 4614, -1, 1, 0, 1109, -1, "EvilTable", 1);// 6
			AddComplexComponent( (BaseAddon) this, 4614, 0, 1, 0, 1109, -1, "EvilTable", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4614, 1, 1, 0, 1109, -1, "EvilTable", 1);// 8
			AddComplexComponent( (BaseAddon) this, 13854, 1, 1, 6, 1102, -1, "EvilTable", 1);// 9
			AddComplexComponent( (BaseAddon) this, 13854, 0, 1, 6, 1102, -1, "EvilTable", 1);// 10
			AddComplexComponent( (BaseAddon) this, 13854, -1, 1, 6, 1102, -1, "EvilTable", 1);// 11
			AddComplexComponent( (BaseAddon) this, 8707, 1, 1, 16, 0, -1, "EvilTable", 1);// 12
			AddComplexComponent( (BaseAddon) this, 13854, 1, 0, 6, 1102, -1, "EvilTable", 1);// 13
			AddComplexComponent( (BaseAddon) this, 13854, 0, 0, 6, 1102, -1, "EvilTable", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13854, -1, 0, 6, 1102, -1, "EvilTable", 1);// 15
			AddComplexComponent( (BaseAddon) this, 13900, 2, 1, 1, 0, -1, "EvilTable", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2921, -1, 2, 0, 1109, -1, "EvilTable", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2921, -1, -1, 0, 1109, -1, "EvilTable", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2920, 1, 2, 0, 1109, -1, "EvilTable", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2920, 1, -1, 0, 1109, -1, "EvilTable", 1);// 20
			AddComplexComponent( (BaseAddon) this, 13900, 2, 0, 1, 0, -1, "EvilTable", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2922, 0, 2, 0, 1109, -1, "EvilTable", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2922, 0, -1, 0, 1109, -1, "EvilTable", 1);// 23
			AddComplexComponent( (BaseAddon) this, 4650, 1, 1, 15, 0, -1, "EvilTable", 1);// 24
			AddComplexComponent( (BaseAddon) this, 4654, 0, 1, 6, 0, -1, "EvilTable", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6929, 0, 1, 6, 0, -1, "EvilTable", 1);// 26

		}

		public EvilTableEastWestAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EvilTableEastWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EvilTableEastWestAddon();
			}
		}

		[Constructable]
		public EvilTableEastWestAddonDeed()
		{
			Name = "EvilTableEastWest";
		}

		public EvilTableEastWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}