
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FountainRuinSmallAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {954, 0, -1, 0}, {6039, 1, 0, 0}, {6039, 1, 1, 0}// 8	10	11	
			, {6039, 0, 0, 0}, {6039, 0, 1, 0}, {955, 0, 0, 7}// 12	13	14	
			, {13488, 2, 2, 28}, {3233, 1, -1, 3}, {964, -1, 0, 0}// 16	17	19	
			, {957, 0, 0, 10}, {13455, 2, 2, 21}, {3220, -1, 0, 2}// 21	23	24	
			, {3332, 0, 1, 5}// 25	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FountainRuinSmallAddonDeed();
			}
		}

		[ Constructable ]
		public FountainRuinSmallAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2416, 0, 0, 16, 95, -1, "water", 1);// 1
			AddComplexComponent( (BaseAddon) this, 4551, 0, 0, 13, 0, -1, "fountain", 1);// 2
			AddComplexComponent( (BaseAddon) this, 956, 0, -1, 4, 0, -1, "fountain", 1);// 3
			AddComplexComponent( (BaseAddon) this, 959, 1, 1, 0, 0, -1, "fountain", 1);// 4
			AddComplexComponent( (BaseAddon) this, 963, 1, -1, 0, 0, -1, "fountain", 1);// 5
			AddComplexComponent( (BaseAddon) this, 966, -1, 1, 0, 0, -1, "fountain", 1);// 6
			AddComplexComponent( (BaseAddon) this, 954, 0, 1, 0, 0, -1, "fountain", 1);// 7
			AddComplexComponent( (BaseAddon) this, 953, 1, 0, 0, 0, -1, "fountain", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6209, 1, 1, 13, 0, -1, "water", 1);// 15
			AddComplexComponent( (BaseAddon) this, 10807, 0, -1, 0, 0, -1, "fountain", 1);// 18
			AddComplexComponent( (BaseAddon) this, 10808, -2, -1, 0, 0, -1, "fountain", 1);// 20
			AddComplexComponent( (BaseAddon) this, 952, 1, 1, 13, 0, -1, "fountain", 1);// 22

		}

		public FountainRuinSmallAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FountainRuinSmallAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FountainRuinSmallAddon();
			}
		}

		[Constructable]
		public FountainRuinSmallAddonDeed()
		{
			Name = "FountainRuinSmall";
		}

		public FountainRuinSmallAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}