
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GrillLargeSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7134, 1, 1, 3}, {7134, 2, 1, 3}, {7134, 0, 1, 3}// 2	3	7	
			, {2450, 3, 1, 6}, {66, 2, 0, 0}, {7828, 0, 1, 6}// 11	19	29	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GrillLargeSouthAddonDeed();
			}
		}

		[ Constructable ]
		public GrillLargeSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1184, 0, 1, 0, 2102, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 66, 1, 0, 0, 0, -1, "Grill", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7386, 2, 1, 6, 961, -1, "Grill", 1);// 5
			AddComplexComponent( (BaseAddon) this, 83, 1, 0, 18, 0, -1, "Grill", 1);// 6
			AddComplexComponent( (BaseAddon) this, 66, 0, 0, 0, 0, -1, "Grill", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1184, 3, 1, 0, 2102, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6571, 2, 1, 5, 0, 1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1184, 2, 1, 0, 2102, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1184, 3, 1, 6, 2102, -1, "Grill", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1184, 1, 1, 0, 2102, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 83, 0, 0, 18, 0, -1, "Grill", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1184, -1, 1, 0, 2102, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 7386, 1, 1, 6, 961, -1, "Grill", 1);// 17
			AddComplexComponent( (BaseAddon) this, 66, 0, 1, 0, 0, -1, "Grill", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1184, -1, 1, 6, 2102, -1, "Grill", 1);// 20
			AddComplexComponent( (BaseAddon) this, 67, -2, 1, 0, 0, -1, "Grill", 1);// 21
			AddComplexComponent( (BaseAddon) this, 59, -1, 0, 0, 0, 1, "Grill", 1);// 22
			AddComplexComponent( (BaseAddon) this, 66, -1, 1, 0, 0, -1, "Grill", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6571, 1, 1, 5, 0, 1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 65, 3, 1, 0, 0, -1, "Grill", 1);// 25
			AddComplexComponent( (BaseAddon) this, 66, 2, 1, 0, 0, -1, "Grill", 1);// 26
			AddComplexComponent( (BaseAddon) this, 66, 1, 1, 0, 0, -1, "Grill", 1);// 27
			AddComplexComponent( (BaseAddon) this, 71, 0, 0, 0, 0, -1, "Grill", 1);// 28
			AddComplexComponent( (BaseAddon) this, 59, 3, 0, 0, 0, 1, "Grill", 1);// 30
			AddComplexComponent( (BaseAddon) this, 72, 2, 0, 0, 0, -1, "Grill", 1);// 31
			AddComplexComponent( (BaseAddon) this, 6571, 0, 1, 5, 0, 1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 7386, 0, 1, 6, 961, -1, "Grill", 1);// 33

		}

		public GrillLargeSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GrillLargeSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GrillLargeSouthAddon();
			}
		}

		[Constructable]
		public GrillLargeSouthAddonDeed()
		{
			Name = "GrillLargeSouth";
		}

		public GrillLargeSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}