
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Jackolantern3decoAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3166, 0, 0, 7}// 5	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Jackolantern3decoAddonDeed();
			}
		}

		[ Constructable ]
		public Jackolantern3decoAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 14267, 1, 1, 5, 1260, -1, "pumpkin", 1);// 1
			AddComplexComponent( (BaseAddon) this, 4963, 0, 0, 2, 1259, -1, "Pumpkin", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3884, 0, 0, 5, 1360, -1, "eye", 1);// 3
			AddComplexComponent( (BaseAddon) this, 9777, 1, 1, 13, 1102, -1, "Bat", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3883, 0, 0, 2, 1360, -1, "nose", 1);// 6
			AddComplexComponent( (BaseAddon) this, 14271, 1, 1, 0, 1260, -1, "mouth", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3885, 1, 0, 4, 1260, -1, "mouth", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3875, 1, 0, 7, 1260, -1, "mouth", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3202, 0, 0, 4, 1360, -1, "mouth", 1);// 10
			AddComplexComponent( (BaseAddon) this, 3886, 0, 0, 2, 1360, -1, "eye", 1);// 11

		}

		public Jackolantern3decoAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Jackolantern3decoAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Jackolantern3decoAddon();
			}
		}

		[Constructable]
		public Jackolantern3decoAddonDeed()
		{
			Name = "Jackolantern3deco";
		}

		public Jackolantern3decoAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}