
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class JapaneseCouchSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10813, 1, 0, 0}, {10813, 0, 0, 0}, {10813, 2, 1, 0}// 8	36	37	
			, {10813, 1, 1, 0}, {10813, 0, 1, 0}, {10813, -1, 1, 0}// 38	39	41	
			, {10813, -2, 1, 0}, {10813, -1, 0, 0}, {9443, -2, 0, 4}// 43	52	54	
			, {6468, 0, -1, 7}// 55	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new JapaneseCouchSouthAddonDeed();
			}
		}

		[ Constructable ]
		public JapaneseCouchSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1824, -2, -1, 0, 1510, -1, "Japanese Couch", 1);// 1
			AddComplexComponent( (BaseAddon) this, 1824, 1, -1, 0, 1510, -1, "Japanese Couch", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1824, -1, -1, 0, 1510, -1, "Japanese Couch", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2921, -1, 0, 0, 1510, -1, "Japanese Couch", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1824, 0, -1, 0, 1510, -1, "Japanese Couch", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2768, 1, 2, 0, 1510, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2832, 2, -1, 7, 1510, -1, "Japanese Couch", 1);// 7
			AddComplexComponent( (BaseAddon) this, 10759, 1, -2, 0, 0, -1, "Japanese Couch", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1824, 2, -1, 0, 1510, -1, "Japanese Couch", 1);// 10
			AddComplexComponent( (BaseAddon) this, 10759, 0, -2, 0, 0, -1, "Japanese Couch", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2768, 2, 2, 0, 1510, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6422, -2, -1, 2, 1510, -1, "Japanese Couch", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2831, 2, 0, 0, 1510, -1, "Japanese Couch", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2920, 1, 0, 0, 1510, -1, "Japanese Couch", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2814, -1, -1, 2, 0, -1, "Japanese Couch", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2768, -1, 2, 0, 1510, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2814, 1, -1, 2, 0, -1, "Japanese Couch", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2763, -3, 2, 0, 1510, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2831, -2, 0, 0, 1510, -1, "Japanese Couch", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2832, -2, -1, 7, 1510, -1, "Japanese Couch", 1);// 21
			AddComplexComponent( (BaseAddon) this, 6423, -2, 0, 0, 1510, -1, "Japanese Couch", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6469, 2, -2, 0, 1510, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6423, 2, 0, 0, 1510, -1, "Japanese Couch", 1);// 24
			AddComplexComponent( (BaseAddon) this, 5690, 0, -1, 6, 1510, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2922, 0, 0, 0, 1510, -1, "Japanese Couch", 1);// 26
			AddComplexComponent( (BaseAddon) this, 5690, -1, -1, 6, 1510, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2768, 0, 2, 0, 1510, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2761, 3, 2, 0, 1510, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2765, -3, 0, 0, 1510, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2767, 3, -1, 0, 1510, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 10759, -1, -2, 0, 0, -1, "Japanese Couch", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2765, -3, 1, 0, 1510, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2766, 2, -2, 0, 1510, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 6469, -2, -2, 0, 1510, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2814, 0, -1, 2, 0, -1, "Japanese Couch", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2767, 3, 0, 0, 1510, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 9417, 2, -1, 10, 0, 1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2767, 3, 1, 0, 1510, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6422, 2, -1, 2, 1510, -1, "Japanese Couch", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2768, -2, 2, 0, 1510, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 5034, -1, 0, 1, 1510, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 5034, 0, 0, 1, 1510, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 9417, -2, -1, 10, 0, 1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 5034, 1, 0, 1, 1510, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 10409, 2, 0, 4, 0, -1, "Japanese Couch", 1);// 53
			AddComplexComponent( (BaseAddon) this, 10409, -2, 0, 4, 0, -1, "Japanese Couch", 1);// 56
			AddComplexComponent( (BaseAddon) this, 5690, 1, -1, 6, 1510, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2764, 3, -2, 0, 1510, -1, "", 1);// 58

		}

		public JapaneseCouchSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class JapaneseCouchSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new JapaneseCouchSouthAddon();
			}
		}

		[Constructable]
		public JapaneseCouchSouthAddonDeed()
		{
			Name = "JapaneseCouchSouth";
		}

		public JapaneseCouchSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}