
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class JapaneseGateLargeEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {9398, -1, 3, 0}, {9396, 1, 3, 0}, {9397, 0, 3, 0}// 1	2	3	
			, {9399, 1, 2, 0}, {9400, 1, 0, 0}, {9401, 1, -1, 0}// 4	5	6	
			, {9402, 1, -2, 0}// 7	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new JapaneseGateLargeEastAddonDeed();
			}
		}

		[ Constructable ]
		public JapaneseGateLargeEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public JapaneseGateLargeEastAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class JapaneseGateLargeEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new JapaneseGateLargeEastAddon();
			}
		}

		[Constructable]
		public JapaneseGateLargeEastAddonDeed()
		{
			Name = "JapaneseGateLargeEast";
		}

		public JapaneseGateLargeEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}