
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class JapaneseTableSmallrockAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {9312, 1, 1, 4}, {9313, 0, 1, 4}, {9311, 0, 0, 4}// 5	6	7	
			, {9310, 1, 0, 4}, {9316, 0, 0, 4}, {9318, 1, 1, 4}// 8	9	10	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new JapaneseTableSmallrockAddonDeed();
			}
		}

		[ Constructable ]
		public JapaneseTableSmallrockAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2831, 1, 1, 0, 1510, -1, "Japanese Table", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2831, 0, 0, 0, 1510, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2831, 1, 0, 0, 1510, -1, "Japanese Table", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2831, 0, 1, 0, 1510, -1, "Japanese Table", 1);// 4

		}

		public JapaneseTableSmallrockAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class JapaneseTableSmallrockAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new JapaneseTableSmallrockAddon();
			}
		}

		[Constructable]
		public JapaneseTableSmallrockAddonDeed()
		{
			Name = "JapaneseTableSmallrock";
		}

		public JapaneseTableSmallrockAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}