
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class JapaneseStairsSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10159, 0, 1, 5}, {10147, 1, 1, 5}// 2	8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new JapaneseStairsSouthAddonDeed();
			}
		}

		[ Constructable ]
		public JapaneseStairsSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 10406, 1, 1, 5, 0, -1, "Japanese Table", 1);// 1
			AddComplexComponent( (BaseAddon) this, 10393, 0, 1, 0, 0, -1, "Japanese Table", 1);// 3
			AddComplexComponent( (BaseAddon) this, 9452, 0, 0, 0, 0, -1, "Japanese Stairs", 1);// 4
			AddComplexComponent( (BaseAddon) this, 9456, 2, 0, 0, 0, -1, "Japanese Stairs", 1);// 5
			AddComplexComponent( (BaseAddon) this, 9457, 1, 0, 0, 0, -1, "Japanese Stairs", 1);// 6
			AddComplexComponent( (BaseAddon) this, 9453, -1, 0, 0, 0, -1, "Japanese Stairs", 1);// 7
			AddComplexComponent( (BaseAddon) this, 10406, 0, 1, 5, 0, -1, "Japanese Table", 1);// 9
			AddComplexComponent( (BaseAddon) this, 10390, 1, 1, 0, 0, -1, "Japanese Table", 1);// 10
			AddComplexComponent( (BaseAddon) this, 10396, -1, 1, 0, 0, -1, "Japanese Table", 1);// 11

		}

		public JapaneseStairsSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class JapaneseStairsSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new JapaneseStairsSouthAddon();
			}
		}

		[Constructable]
		public JapaneseStairsSouthAddonDeed()
		{
			Name = "JapaneseStairsSouth";
		}

		public JapaneseStairsSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}