
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarbleSinkWestAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarbleSinkWestAddonDeed();
			}
		}

		[ Constructable ]
		public MarbleSinkWestAddon()
		{



			AddComplexComponent( (BaseAddon) this, 3459, -1, 2, 0, 0, -1, "MarbleSink", 1);// 1
			AddComplexComponent( (BaseAddon) this, 267, 2, 2, 0, 0, -1, "MarbleSink", 1);// 2
			AddComplexComponent( (BaseAddon) this, 267, 2, -1, 0, 0, -1, "MarbleSink", 1);// 3
			AddComplexComponent( (BaseAddon) this, 281, 1, 0, 5, 0, -1, "MarbleSink", 1);// 4
			AddComplexComponent( (BaseAddon) this, 281, 1, 1, 5, 0, -1, "MarbleSink", 1);// 5
			AddComplexComponent( (BaseAddon) this, 281, 1, 2, 5, 0, -1, "MarbleSink", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2881, 2, 1, 6, 0, -1, "MarbleSink", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1294, 2, 0, 8, 0, -1, "MarbleSink", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1294, 2, 2, 8, 0, -1, "MarbleSink", 1);// 9
			AddComplexComponent( (BaseAddon) this, 268, 2, 0, 0, 0, -1, "MarbleSink", 1);// 10
			AddComplexComponent( (BaseAddon) this, 268, 2, 2, 0, 0, -1, "MarbleSink", 1);// 11
			AddComplexComponent( (BaseAddon) this, 268, 2, 1, 0, 0, -1, "MarbleSink", 1);// 12
			AddComplexComponent( (BaseAddon) this, 272, 2, 2, 8, 0, -1, "MarbleSink", 1);// 13
			AddComplexComponent( (BaseAddon) this, 272, 2, 1, 8, 0, -1, "MarbleSink", 1);// 14
			AddComplexComponent( (BaseAddon) this, 272, 2, 0, 8, 0, -1, "MarbleSink", 1);// 15
			AddComplexComponent( (BaseAddon) this, 271, 2, -1, 10, 0, -1, "MarbleSink", 1);// 16
			AddComplexComponent( (BaseAddon) this, 271, 2, 2, 10, 0, -1, "MarbleSink", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6197, 2, 1, 7, 0, -1, "MarbleSink", 1);// 18

		}

		public MarbleSinkWestAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarbleSinkWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarbleSinkWestAddon();
			}
		}

		[Constructable]
		public MarbleSinkWestAddonDeed()
		{
			Name = "MarbleSinkWest";
		}

		public MarbleSinkWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}