
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NightSkyBedAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new NightSkyBedAddonDeed();
			}
		}

		[ Constructable ]
		public NightSkyBedAddon()
		{



			AddComplexComponent( (BaseAddon) this, 13842, -2, 3, 2, 2030, -1, "NightSkyBed", 1);// 1
			AddComplexComponent( (BaseAddon) this, 13842, 1, -2, 1, 2030, -1, "NightSkyBed", 1);// 2
			AddComplexComponent( (BaseAddon) this, 13842, -2, -2, 1, 2030, -1, "NightSkyBed", 1);// 3
			AddComplexComponent( (BaseAddon) this, 13842, 2, 3, 2, 2030, -1, "NightSkyBed", 1);// 4
			AddComplexComponent( (BaseAddon) this, 11200, 1, -2, 1, 1983, 1, "NightSkyBed", 1);// 5
			AddComplexComponent( (BaseAddon) this, 11200, 0, -2, 1, 1983, 1, "NightSkyBed", 1);// 6
			AddComplexComponent( (BaseAddon) this, 11200, -1, -2, 1, 1983, 1, "NightSkyBed", 1);// 7
			AddComplexComponent( (BaseAddon) this, 11196, 0, 3, 2, 1983, -1, "NightSkyBed", 1);// 8
			AddComplexComponent( (BaseAddon) this, 11196, 1, 3, 2, 1983, -1, "NightSkyBed", 1);// 9
			AddComplexComponent( (BaseAddon) this, 11196, 2, 3, 2, 1983, -1, "NightSkyBed", 1);// 10
			AddComplexComponent( (BaseAddon) this, 8512, 0, 1, 3, 0, -1, "NightSkyBed", 1);// 11
			AddComplexComponent( (BaseAddon) this, 8512, 0, 2, 3, 0, -1, "NightSkyBed", 1);// 12
			AddComplexComponent( (BaseAddon) this, 8512, 1, 1, 3, 0, -1, "NightSkyBed", 1);// 13
			AddComplexComponent( (BaseAddon) this, 8512, 1, 2, 3, 0, -1, "NightSkyBed", 1);// 14
			AddComplexComponent( (BaseAddon) this, 8512, -1, -1, 4, 0, -1, "NightSkyBed", 1);// 15
			AddComplexComponent( (BaseAddon) this, 8512, -1, 0, 4, 0, -1, "NightSkyBed", 1);// 16
			AddComplexComponent( (BaseAddon) this, 8512, -1, 1, 4, 0, -1, "NightSkyBed", 1);// 17
			AddComplexComponent( (BaseAddon) this, 8512, -1, 2, 4, 0, -1, "NightSkyBed", 1);// 18
			AddComplexComponent( (BaseAddon) this, 8512, 0, -1, 4, 0, -1, "NightSkyBed", 1);// 19
			AddComplexComponent( (BaseAddon) this, 8512, 0, 0, 4, 0, -1, "NightSkyBed", 1);// 20
			AddComplexComponent( (BaseAddon) this, 8512, 0, 1, 4, 0, -1, "NightSkyBed", 1);// 21
			AddComplexComponent( (BaseAddon) this, 8512, 0, 2, 4, 0, -1, "NightSkyBed", 1);// 22
			AddComplexComponent( (BaseAddon) this, 8512, 1, -1, 4, 0, -1, "NightSkyBed", 1);// 23
			AddComplexComponent( (BaseAddon) this, 8512, 1, 0, 4, 0, -1, "NightSkyBed", 1);// 24
			AddComplexComponent( (BaseAddon) this, 8512, 1, 1, 4, 0, -1, "NightSkyBed", 1);// 25
			AddComplexComponent( (BaseAddon) this, 8512, 1, 2, 4, 0, -1, "NightSkyBed", 1);// 26
			AddComplexComponent( (BaseAddon) this, 11727, 1, -1, 1, 1983, -1, "NightSkyBed", 1);// 27
			AddComplexComponent( (BaseAddon) this, 11727, 1, 0, 1, 1983, -1, "NightSkyBed", 1);// 28
			AddComplexComponent( (BaseAddon) this, 11727, 1, 1, 1, 1983, -1, "NightSkyBed", 1);// 29
			AddComplexComponent( (BaseAddon) this, 11727, 1, 2, 1, 1983, -1, "NightSkyBed", 1);// 30
			AddComplexComponent( (BaseAddon) this, 11196, -1, 3, 2, 1983, -1, "NightSkyBed", 1);// 31
			AddComplexComponent( (BaseAddon) this, 11194, -1, 2, 1, 1983, -1, "NightSkyBed", 1);// 32
			AddComplexComponent( (BaseAddon) this, 11193, -2, 2, 0, 1983, -1, "NightSkyBed", 1);// 33
			AddComplexComponent( (BaseAddon) this, 11193, -2, 1, 0, 1983, -1, "NightSkyBed", 1);// 34
			AddComplexComponent( (BaseAddon) this, 11193, -2, 0, 0, 1983, -1, "NightSkyBed", 1);// 35
			AddComplexComponent( (BaseAddon) this, 11193, -2, -1, 0, 1983, -1, "NightSkyBed", 1);// 36
			AddComplexComponent( (BaseAddon) this, 5029, -1, -1, 6, 2761, -1, "NightSkyBed", 1);// 37
			AddComplexComponent( (BaseAddon) this, 5029, 0, -1, 6, 2761, -1, "NightSkyBed", 1);// 38
			AddComplexComponent( (BaseAddon) this, 5029, 1, -1, 6, 2761, -1, "NightSkyBed", 1);// 39
			AddComplexComponent( (BaseAddon) this, 5035, 0, 0, 8, 2761, -1, "NightSkyBed", 1);// 40
			AddComplexComponent( (BaseAddon) this, 5035, -1, 0, 8, 2761, -1, "NightSkyBed", 1);// 41
			AddComplexComponent( (BaseAddon) this, 5035, 1, 0, 8, 2761, -1, "NightSkyBed", 1);// 42
			AddComplexComponent( (BaseAddon) this, 5690, -1, -1, 4, 2995, -1, "NightSkyBed", 1);// 43
			AddComplexComponent( (BaseAddon) this, 5690, 0, -1, 4, 2995, -1, "NightSkyBed", 1);// 44
			AddComplexComponent( (BaseAddon) this, 5690, 1, -1, 4, 2995, -1, "NightSkyBed", 1);// 45

		}

		public NightSkyBedAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class NightSkyBedAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new NightSkyBedAddon();
			}
		}

		[Constructable]
		public NightSkyBedAddonDeed()
		{
			Name = "NightSkyBed";
		}

		public NightSkyBedAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}