
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ParrotCageDonationAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {9347, -4, 0, 6}, {9347, -4, -1, 6}, {9347, -4, -2, 6}// 1	2	3	
			, {9348, -3, -4, 6}, {9348, -2, -4, 6}, {9348, -1, -4, 6}// 4	5	6	
			, {9348, 0, -4, 6}, {9354, -4, -4, 7}, {9269, -3, -2, 6}// 7	8	9	
			, {9269, -2, -2, 6}, {9269, -2, -1, 6}, {9269, -1, -2, 6}// 10	11	12	
			, {9269, 0, -2, 6}, {9354, -4, 0, 6}, {9354, -1, -4, 7}// 13	14	15	
			, {9347, -4, -3, 6}, {9269, -3, -2, 6}, {9269, -2, -2, 6}// 16	18	19	
			, {9269, -1, -2, 6}, {9269, 0, -2, 6}, {6039, 0, 0, 6}// 20	21	22	
			, {6039, -1, 0, 6}, {13450, -1, -1, 6}, {6052, -2, 0, 6}// 23	24	25	
			, {3308, -3, -3, 8}, {3312, -3, 0, 6}, {2211, -3, 0, 6}// 26	27	28	
			, {2208, -2, -2, 6}, {3412, -1, 0, 8}, {9989, -3, -3, 32}// 29	35	45	
			, {9978, -3, 0, 33}, {9978, -3, -1, 33}, {9978, -3, -2, 33}// 46	47	48	
			, {9994, -2, -3, 33}, {9994, -1, -3, 33}, {9994, 0, -3, 33}// 49	50	51	
			, {9993, 0, 0, 36}, {9993, -1, 0, 36}, {9994, 0, -2, 36}// 52	53	54	
			, {9994, -1, -2, 36}, {9978, -2, -1, 36}, {9989, -2, -2, 35}// 55	56	57	
			, {9990, -2, 0, 36}, {1981, -3, 0, 6}, {9269, -2, 0, 6}// 58	64	65	
			, {1981, -2, -2, 6}, {6039, -1, -1, 6}, {6039, 0, -1, 6}// 68	71	72	
			, {9992, 0, -1, 39}, {9992, -1, -1, 39}, {924, -2, -1, 13}// 75	76	77	
			, {924, -2, -3, 13}, {6664, 0, -2, 2}, {3312, -3, -1, 8}// 78	79	80	
			, {3312, -3, -2, 8}, {3308, -2, -3, 8}, {5953, 0, 0, 7}// 81	82	83	
			, {925, -2, -2, 13}, {9347, -4, 2, 6}, {9347, -4, 1, 6}// 85	86	87	
			, {9347, -4, 3, 6}, {9348, -3, 3, 6}, {9348, -2, 3, 6}// 88	89	90	
			, {9354, -4, 3, 7}, {9269, -2, 1, 6}, {9269, -1, 1, 6}// 91	92	93	
			, {9269, -1, 2, 6}, {9269, 0, 1, 6}, {9269, 0, 2, 6}// 94	95	96	
			, {9354, -2, 3, 6}, {3308, -2, 4, 6}, {3312, -3, 1, 6}// 97	98	99	
			, {9990, -3, 1, 33}, {9993, 0, 1, 33}, {9993, -1, 1, 33}// 107	108	109	
			, {9993, -2, 1, 33}, {1981, -3, 3, 6}, {1981, -1, 2, 6}// 110	115	120	
			, {1981, 0, 2, 6}, {3458, -2, 4, 23}, {3233, -3, 2, 7}// 121	122	123	
			, {13001, -3, 2, 6}, {3219, -3, 2, 8}, {9348, 1, -4, 6}// 124	125	126	
			, {9348, 2, -4, 6}, {9347, 3, -2, 6}, {9347, 3, -1, 6}// 127	128	129	
			, {9347, 3, 0, 6}, {9354, 3, -4, 7}, {9269, 1, -2, 6}// 130	131	132	
			, {9269, 1, -1, 6}, {9269, 1, 0, 6}, {9269, 2, -2, 6}// 133	134	135	
			, {9269, 2, -1, 6}, {9354, 3, 0, 6}, {9347, 3, -3, 6}// 136	137	138	
			, {9269, 1, -2, 6}, {9269, 2, -2, 6}, {9348, 3, -4, 6}// 139	140	141	
			, {3308, 3, -3, 6}, {3312, 4, -1, 6}, {9977, 4, 0, 33}// 142	143	151	
			, {9977, 4, -1, 33}, {9991, 4, -3, 33}, {9994, 3, -3, 33}// 152	153	154	
			, {9994, 2, -3, 33}, {9994, 1, -3, 33}, {9991, 3, -2, 36}// 155	156	157	
			, {9994, 2, -2, 36}, {9994, 1, -2, 36}, {9977, 4, -2, 33}// 158	159	160	
			, {9988, 3, 0, 36}, {1981, 3, 0, 6}, {1981, 3, -1, 6}// 162	163	164	
			, {1981, 3, -2, 6}, {1981, 3, -3, 6}, {1981, 2, 0, 6}// 165	166	173	
			, {13001, 2, -3, 6}, {9992, 2, -1, 39}, {9992, 1, -1, 39}// 174	178	179	
			, {9977, 3, -1, 36}, {3434, 1, -1, 6}, {9993, 2, 0, 36}// 180	183	184	
			, {9993, 1, 0, 36}, {3233, 3, -3, 6}, {9325, 1, -3, 7}// 185	186	187	
			, {9347, 3, 1, 6}, {9347, 3, 2, 6}, {9346, 3, 3, 6}// 188	189	190	
			, {9348, 2, 3, 6}, {9354, 3, 3, 7}, {9269, 1, 1, 6}// 191	192	193	
			, {9354, 1, 3, 6}, {3308, 2, 4, 6}, {3312, 4, 1, 6}// 194	195	196	
			, {9988, 4, 1, 33}, {9993, 2, 1, 33}, {9993, 1, 1, 33}// 202	203	204	
			, {3473, 1, 2, 6}, {3473, 2, 2, 6}, {1981, 2, 3, 6}// 205	206	208	
			, {1981, 3, 3, 6}, {1981, 3, 2, 6}, {1981, 3, 1, 6}// 209	210	211	
			, {9993, 3, 1, 33}// 216	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ParrotCageDonationAddonDeed();
			}
		}

		[ Constructable ]
		public ParrotCageDonationAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 9269, -3, -3, 6, 0, -1, "parrot play stand", 1);// 17
			AddComplexComponent( (BaseAddon) this, 9269, -3, -1, 13, 2307, -1, "parrot play stand", 1);// 30
			AddComplexComponent( (BaseAddon) this, 9269, -3, -2, 13, 2307, -1, "parrot play stand", 1);// 31
			AddComplexComponent( (BaseAddon) this, 9269, -2, -1, 13, 2307, -1, "parrot play stand", 1);// 32
			AddComplexComponent( (BaseAddon) this, 9269, -3, -3, 13, 2307, -1, "parrot play stand", 1);// 33
			AddComplexComponent( (BaseAddon) this, 9269, -2, -3, 13, 2307, -1, "parrot play stand", 1);// 34
			AddComplexComponent( (BaseAddon) this, 6867, -3, -3, 15, 0, -1, "parrot food", 1);// 36
			AddComplexComponent( (BaseAddon) this, 925, -3, -4, 27, 0, -1, "parrot cage", 1);// 37
			AddComplexComponent( (BaseAddon) this, 925, -2, -4, 27, 0, -1, "parrot cage", 1);// 38
			AddComplexComponent( (BaseAddon) this, 925, -1, -4, 27, 0, -1, "parrot cage", 1);// 39
			AddComplexComponent( (BaseAddon) this, 925, 0, -4, 27, 0, -1, "parrot cage", 1);// 40
			AddComplexComponent( (BaseAddon) this, 926, -4, 0, 27, 0, -1, "parrot cage", 1);// 41
			AddComplexComponent( (BaseAddon) this, 926, -4, -3, 27, 0, -1, "parrot cage", 1);// 42
			AddComplexComponent( (BaseAddon) this, 926, -4, -2, 27, 0, -1, "parrot cage", 1);// 43
			AddComplexComponent( (BaseAddon) this, 926, -4, -1, 27, 0, -1, "parrot cage", 1);// 44
			AddComplexComponent( (BaseAddon) this, 14238, -1, -3, 10, 1360, -1, "parrot swing", 1);// 59
			AddComplexComponent( (BaseAddon) this, 1981, 0, -3, 6, 0, -1, "parrot cage", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1981, -1, -3, 6, 0, -1, "parrot cage", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1981, -2, -3, 6, 0, -1, "parrot cage", 1);// 62
			AddComplexComponent( (BaseAddon) this, 1981, -3, -1, 6, 0, -1, "parrot cage", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1981, -2, 0, 6, 0, -1, "parrot cage", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1981, -2, -1, 6, 0, -1, "parrot cage", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1981, -1, -2, 6, 0, -1, "parrot cage", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1981, 0, -2, 6, 0, -1, "parrot cage", 1);// 70
			AddComplexComponent( (BaseAddon) this, 892, 0, -2, 7, 1021, -1, "parrot swing", 1);// 73
			AddComplexComponent( (BaseAddon) this, 14238, 0, -3, 11, 1360, -1, "parrot swing", 1);// 74
			AddComplexComponent( (BaseAddon) this, 927, -4, -4, 27, 0, -1, "parrot cage", 1);// 84
			AddComplexComponent( (BaseAddon) this, 926, -4, 3, 27, 0, -1, "parrot cage", 1);// 100
			AddComplexComponent( (BaseAddon) this, 926, -4, 2, 27, 0, -1, "parrot cage", 1);// 101
			AddComplexComponent( (BaseAddon) this, 926, -4, 1, 27, 0, -1, "parrot cage", 1);// 102
			AddComplexComponent( (BaseAddon) this, 925, -3, 3, 27, 0, -1, "parrot cage", 1);// 103
			AddComplexComponent( (BaseAddon) this, 925, -2, 3, 27, 0, -1, "parrot cage", 1);// 104
			AddComplexComponent( (BaseAddon) this, 925, -1, 3, 27, 0, -1, "parrot cage", 1);// 105
			AddComplexComponent( (BaseAddon) this, 925, 0, 3, 27, 0, -1, "parrot cage", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1981, -1, 3, 6, 0, -1, "parrot cage", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1981, 0, 3, 6, 0, -1, "parrot cage", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1981, -3, 1, 6, 0, -1, "parrot cage", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1981, -2, 2, 6, 0, -1, "parrot cage", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1981, -2, 3, 6, 0, -1, "parrot cage", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1981, -1, 1, 6, 0, -1, "parrot cage", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1981, 0, 1, 6, 0, -1, "parrot cage", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1981, -2, 1, 6, 0, -1, "parrot cage", 1);// 119
			AddComplexComponent( (BaseAddon) this, 926, 3, 0, 27, 0, -1, "parrot cage", 1);// 144
			AddComplexComponent( (BaseAddon) this, 926, 3, -3, 27, 0, -1, "parrot cage", 1);// 145
			AddComplexComponent( (BaseAddon) this, 926, 3, -2, 27, 0, -1, "parrot cage", 1);// 146
			AddComplexComponent( (BaseAddon) this, 926, 3, -1, 27, 0, -1, "parrot cage", 1);// 147
			AddComplexComponent( (BaseAddon) this, 925, 3, -4, 27, 0, -1, "parrot cage", 1);// 148
			AddComplexComponent( (BaseAddon) this, 925, 1, -4, 27, 0, -1, "parrot cage", 1);// 149
			AddComplexComponent( (BaseAddon) this, 925, 2, -4, 27, 0, -1, "parrot cage", 1);// 150
			AddComplexComponent( (BaseAddon) this, 14238, 2, -1, 32, 1360, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1981, 1, -3, 6, 0, -1, "parrot cage", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1981, 1, 0, 6, 0, -1, "parrot cage", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1981, 2, -2, 6, 0, -1, "parrot cage", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1981, 1, -2, 6, 0, -1, "parrot cage", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1981, 2, -1, 6, 0, -1, "parrot cage", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1981, 1, -1, 6, 0, -1, "parrot cage", 1);// 172
			AddComplexComponent( (BaseAddon) this, 892, 1, -2, 7, 1021, -1, "parrot swing", 1);// 175
			AddComplexComponent( (BaseAddon) this, 892, 2, -2, 7, 1021, -1, "parrot swing", 1);// 176
			AddComplexComponent( (BaseAddon) this, 892, 1, -2, 0, 0, -1, "parrot swing", 1);// 177
			AddComplexComponent( (BaseAddon) this, 6663, 1, -2, 2, 0, -1, "parrot swing", 1);// 181
			AddComplexComponent( (BaseAddon) this, 6867, 1, -1, 10, 0, -1, "parrot food", 1);// 182
			AddComplexComponent( (BaseAddon) this, 926, 3, 1, 27, 0, -1, "parrot cage", 1);// 197
			AddComplexComponent( (BaseAddon) this, 926, 3, 2, 27, 0, -1, "parrot cage", 1);// 198
			AddComplexComponent( (BaseAddon) this, 924, 3, 3, 27, 0, -1, "parrot cage", 1);// 199
			AddComplexComponent( (BaseAddon) this, 925, 2, 3, 27, 0, -1, "parrot cage", 1);// 200
			AddComplexComponent( (BaseAddon) this, 925, 1, 3, 27, 0, -1, "parrot cage", 1);// 201
			AddComplexComponent( (BaseAddon) this, 1981, 1, 3, 6, 0, -1, "parrot cage", 1);// 207
			AddComplexComponent( (BaseAddon) this, 1981, 1, 1, 6, 0, -1, "parrot cage", 1);// 212
			AddComplexComponent( (BaseAddon) this, 1981, 1, 2, 6, 0, -1, "parrot cage", 1);// 213
			AddComplexComponent( (BaseAddon) this, 1981, 2, 2, 6, 0, -1, "parrot cage", 1);// 214
			AddComplexComponent( (BaseAddon) this, 1981, 2, 1, 6, 0, -1, "parrot cage", 1);// 215

		}

		public ParrotCageDonationAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ParrotCageDonationAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ParrotCageDonationAddon();
			}
		}

		[Constructable]
		public ParrotCageDonationAddonDeed()
		{
			Name = "ParrotCageDonation";
		}

		public ParrotCageDonationAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}