
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PlatformAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2170, 4, 0, 0}, {2170, 4, -1, 0}, {1982, 1, 1, 4}// 1	2	3	
			, {1982, 1, 2, 4}, {1982, 2, 1, 4}, {1982, 2, 2, 4}// 4	5	6	
			, {1982, 3, 1, 4}, {1982, -2, 0, 4}, {1982, -2, 1, 4}// 7	9	10	
			, {1982, -2, 2, 4}, {1982, -1, 0, 4}, {1982, -1, 1, 4}// 11	12	13	
			, {1982, -1, 2, 4}, {1982, -1, 0, 4}, {1982, -1, 1, 4}// 14	15	16	
			, {1982, -1, 2, 4}, {1982, 0, -1, 4}, {1982, 0, 0, 4}// 17	18	19	
			, {1982, 0, 1, 4}, {1982, 0, 2, 4}, {1982, 0, -2, 4}// 20	21	22	
			, {1982, 0, -1, 4}, {1982, 0, 0, 4}, {1982, 1, -2, 4}// 23	24	25	
			, {1982, 1, -1, 4}, {1982, 1, 0, 4}, {1982, 2, -2, 4}// 26	27	28	
			, {1982, 2, -1, 4}, {1982, 2, 0, 4}, {1982, 3, -2, 4}// 29	30	31	
			, {1982, 3, -1, 4}, {1982, 3, 0, 4}, {1982, -2, -2, 4}// 32	33	34	
			, {1982, -2, -1, 4}, {1982, -2, 0, 4}, {1982, -1, -2, 4}// 35	36	37	
			, {1982, -1, -1, 4}, {1982, -1, 0, 4}, {1982, 0, -2, 4}// 38	39	40	
			, {1982, 0, -1, 4}, {1982, 0, 0, 4}, {1987, -3, 1, 4}// 41	42	43	
			, {1985, -3, 2, 4}, {1986, 4, 2, 4}, {1984, 4, 1, 4}// 44	45	46	
			, {10075, -2, 2, 0}, {10075, 3, -2, 0}, {10075, 3, -2, 0}// 47	48	49	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PlatformAddonDeed();
			}
		}

		[ Constructable ]
		public PlatformAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1982, 3, 2, 4, 0, -1, "post", 1);// 8
			AddComplexComponent( (BaseAddon) this, 933, 3, -2, 0, 0, -1, "post", 1);// 50
			AddComplexComponent( (BaseAddon) this, 933, -2, 2, 0, 0, -1, "post", 1);// 51
			AddComplexComponent( (BaseAddon) this, 933, 3, 2, 0, 0, -1, "post", 1);// 52

		}

		public PlatformAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PlatformAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PlatformAddon();
			}
		}

		[Constructable]
		public PlatformAddonDeed()
		{
			Name = "Platform";
		}

		public PlatformAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}