
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PrincessBedAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PrincessBedAddonDeed();
			}
		}

		[ Constructable ]
		public PrincessBedAddon()
		{



			AddComplexComponent( (BaseAddon) this, 11727, 1, -1, 4, 1983, -1, "princessbed", 1);// 1
			AddComplexComponent( (BaseAddon) this, 4834, -4, 3, 1, 2640, -1, "princessbed", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3124, 1, 1, 4, 2584, -1, "princessbed", 1);// 3
			AddComplexComponent( (BaseAddon) this, 5028, -3, 1, 10, 2929, -1, "princessbed", 1);// 4
			AddComplexComponent( (BaseAddon) this, 5690, -2, -1, 19, 2929, -1, "princessbed", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2769, 1, -2, 10, 2042, -1, "princessbed", 1);// 6
			AddComplexComponent( (BaseAddon) this, 11727, -4, -1, 14, 1983, -1, "princessbed", 1);// 7
			AddComplexComponent( (BaseAddon) this, 5690, -2, 1, 19, 2929, -1, "princessbed", 1);// 8
			AddComplexComponent( (BaseAddon) this, 3124, 0, 1, 4, 2584, -1, "princessbed", 1);// 9
			AddComplexComponent( (BaseAddon) this, 10809, -5, 3, 4, 2044, -1, "princessbed", 1);// 10
			AddComplexComponent( (BaseAddon) this, 5028, -3, -1, 10, 2929, -1, "princessbed", 1);// 11
			AddComplexComponent( (BaseAddon) this, 5691, -2, -1, 14, 2044, -1, "princessbed", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2769, 1, -1, 10, 2042, -1, "princessbed", 1);// 13
			AddComplexComponent( (BaseAddon) this, 11727, 1, 1, 4, 1983, -1, "princessbed", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2769, -1, 0, 10, 2042, -1, "princessbed", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2769, -1, -1, 10, 2042, -1, "princessbed", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2769, -3, -1, 10, 2042, -1, "princessbed", 1);// 17
			AddComplexComponent( (BaseAddon) this, 2769, -3, -2, 10, 2042, -1, "princessbed", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3124, -1, 1, 4, 2584, -1, "princessbed", 1);// 19
			AddComplexComponent( (BaseAddon) this, 5028, -3, 0, 10, 2929, -1, "princessbed", 1);// 20
			AddComplexComponent( (BaseAddon) this, 3124, -2, 1, 4, 2584, -1, "princessbed", 1);// 21
			AddComplexComponent( (BaseAddon) this, 11727, 1, -2, 4, 1983, -1, "princessbed", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2769, -1, -2, 10, 2042, -1, "princessbed", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2769, 1, 1, 10, 2042, -1, "princessbed", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2769, 1, 0, 10, 2042, -1, "princessbed", 1);// 25
			AddComplexComponent( (BaseAddon) this, 5035, -3, 1, 11, 2044, -1, "princessbed", 1);// 26
			AddComplexComponent( (BaseAddon) this, 11727, 1, 0, 4, 1983, -1, "princessbed", 1);// 27
			AddComplexComponent( (BaseAddon) this, 11727, -4, 0, 14, 1983, -1, "princessbed", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2769, -2, 0, 10, 2042, -1, "princessbed", 1);// 29
			AddComplexComponent( (BaseAddon) this, 5035, -3, -1, 11, 2044, -1, "princessbed", 1);// 30
			AddComplexComponent( (BaseAddon) this, 5691, -2, 1, 14, 2044, -1, "princessbed", 1);// 31
			AddComplexComponent( (BaseAddon) this, 11195, -4, -1, 4, 1983, -1, "princessbed", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2769, -2, 1, 10, 2042, -1, "princessbed", 1);// 33
			AddComplexComponent( (BaseAddon) this, 11195, -4, -2, 4, 1983, -1, "princessbed", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3124, -3, 1, 4, 2584, -1, "princessbed", 1);// 35
			AddComplexComponent( (BaseAddon) this, 10809, -5, -4, 4, 2044, -1, "princessbed", 1);// 36
			AddComplexComponent( (BaseAddon) this, 4835, -4, -3, 0, 2640, -1, "princessbed", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2769, -3, 0, 10, 2042, -1, "princessbed", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2769, -3, 1, 10, 2042, -1, "princessbed", 1);// 39
			AddComplexComponent( (BaseAddon) this, 10809, 3, -4, 4, 2044, -1, "princessbed", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2769, -2, -1, 10, 2042, -1, "princessbed", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2769, -2, -2, 10, 2042, -1, "princessbed", 1);// 42
			AddComplexComponent( (BaseAddon) this, 10809, 3, 3, 4, 2044, -1, "princessbed", 1);// 43
			AddComplexComponent( (BaseAddon) this, 11195, -4, 0, 4, 1983, -1, "princessbed", 1);// 44
			AddComplexComponent( (BaseAddon) this, 11195, -4, 1, 4, 1983, -1, "princessbed", 1);// 45
			AddComplexComponent( (BaseAddon) this, 5028, -3, -2, 10, 2929, -1, "princessbed", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2769, 0, 1, 10, 2042, -1, "princessbed", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2769, 0, -1, 10, 2042, -1, "princessbed", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2769, 0, -2, 10, 2042, -1, "princessbed", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2769, 0, 0, 10, 2042, -1, "princessbed", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2769, -1, 1, 10, 2042, -1, "princessbed", 1);// 51
			AddComplexComponent( (BaseAddon) this, 5030, -3, -2, 11, 2522, -1, "princessbed", 1);// 52
			AddComplexComponent( (BaseAddon) this, 5030, -3, -1, 11, 2522, -1, "princessbed", 1);// 53
			AddComplexComponent( (BaseAddon) this, 5030, -3, 0, 11, 2522, -1, "princessbed", 1);// 54
			AddComplexComponent( (BaseAddon) this, 5030, -3, 1, 11, 2522, -1, "princessbed", 1);// 55
			AddComplexComponent( (BaseAddon) this, 5691, -2, 0, 14, 2044, -1, "princessbed", 1);// 56
			AddComplexComponent( (BaseAddon) this, 5692, -3, -2, 11, 2476, -1, "princessbed", 1);// 57
			AddComplexComponent( (BaseAddon) this, 5692, -3, -1, 11, 2476, -1, "princessbed", 1);// 58
			AddComplexComponent( (BaseAddon) this, 5692, -3, 0, 11, 2476, -1, "princessbed", 1);// 59
			AddComplexComponent( (BaseAddon) this, 5692, -3, 1, 11, 2476, -1, "princessbed", 1);// 60
			AddComplexComponent( (BaseAddon) this, 5645, -4, -3, 4, 1986, -1, "princessbed", 1);// 61
			AddComplexComponent( (BaseAddon) this, 5646, 3, -3, 4, 1986, -1, "princessbed", 1);// 62
			AddComplexComponent( (BaseAddon) this, 5645, 4, -3, 4, 1986, -1, "princessbed", 1);// 63
			AddComplexComponent( (BaseAddon) this, 9376, -4, -4, 20, 2044, -1, "princessbed", 1);// 64
			AddComplexComponent( (BaseAddon) this, 9376, -3, -4, 20, 2044, -1, "princessbed", 1);// 65
			AddComplexComponent( (BaseAddon) this, 9376, -2, -4, 20, 2044, -1, "princessbed", 1);// 66
			AddComplexComponent( (BaseAddon) this, 9376, -1, -4, 20, 2044, -1, "princessbed", 1);// 67
			AddComplexComponent( (BaseAddon) this, 9376, 0, -4, 20, 2044, -1, "princessbed", 1);// 68
			AddComplexComponent( (BaseAddon) this, 9376, 1, -4, 20, 2044, -1, "princessbed", 1);// 69
			AddComplexComponent( (BaseAddon) this, 9376, 2, -4, 20, 2044, -1, "princessbed", 1);// 70
			AddComplexComponent( (BaseAddon) this, 9376, 3, -4, 20, 2044, -1, "princessbed", 1);// 71
			AddComplexComponent( (BaseAddon) this, 9376, -4, 3, 20, 2044, -1, "princessbed", 1);// 72
			AddComplexComponent( (BaseAddon) this, 9376, -3, 3, 20, 2044, -1, "princessbed", 1);// 73
			AddComplexComponent( (BaseAddon) this, 9376, -2, 3, 20, 2044, -1, "princessbed", 1);// 74
			AddComplexComponent( (BaseAddon) this, 9376, -1, 3, 20, 2044, -1, "princessbed", 1);// 75
			AddComplexComponent( (BaseAddon) this, 9376, 0, 3, 20, 2044, -1, "princessbed", 1);// 76
			AddComplexComponent( (BaseAddon) this, 9376, 1, 3, 20, 2044, -1, "princessbed", 1);// 77
			AddComplexComponent( (BaseAddon) this, 9376, 2, 3, 20, 2044, -1, "princessbed", 1);// 78
			AddComplexComponent( (BaseAddon) this, 9376, 3, 3, 20, 2044, -1, "princessbed", 1);// 79
			AddComplexComponent( (BaseAddon) this, 9375, -5, -3, 20, 2044, -1, "princessbed", 1);// 80
			AddComplexComponent( (BaseAddon) this, 9375, -5, -2, 20, 2044, -1, "princessbed", 1);// 81
			AddComplexComponent( (BaseAddon) this, 9375, -5, -1, 20, 2044, -1, "princessbed", 1);// 82
			AddComplexComponent( (BaseAddon) this, 9375, -5, 0, 20, 2044, -1, "princessbed", 1);// 83
			AddComplexComponent( (BaseAddon) this, 9375, -5, 1, 20, 2044, -1, "princessbed", 1);// 84
			AddComplexComponent( (BaseAddon) this, 9375, -5, 2, 20, 2044, -1, "princessbed", 1);// 85
			AddComplexComponent( (BaseAddon) this, 9375, -5, 3, 20, 2044, -1, "princessbed", 1);// 86
			AddComplexComponent( (BaseAddon) this, 9375, 3, -3, 20, 2044, -1, "princessbed", 1);// 87
			AddComplexComponent( (BaseAddon) this, 9375, 3, -2, 20, 2044, -1, "princessbed", 1);// 88
			AddComplexComponent( (BaseAddon) this, 9375, 3, -1, 20, 2044, -1, "princessbed", 1);// 89
			AddComplexComponent( (BaseAddon) this, 9375, 3, 0, 20, 2044, -1, "princessbed", 1);// 90
			AddComplexComponent( (BaseAddon) this, 9375, 3, 1, 20, 2044, -1, "princessbed", 1);// 91
			AddComplexComponent( (BaseAddon) this, 9375, 3, 2, 20, 2044, -1, "princessbed", 1);// 92
			AddComplexComponent( (BaseAddon) this, 9375, 3, 3, 20, 2044, -1, "princessbed", 1);// 93
			AddComplexComponent( (BaseAddon) this, 4834, -4, 0, 2, 2640, -1, "princessbed", 1);// 94
			AddComplexComponent( (BaseAddon) this, 5646, -4, -3, 4, 1986, -1, "princessbed", 1);// 95
			AddComplexComponent( (BaseAddon) this, 5645, -4, 3, 4, 1986, -1, "princessbed", 1);// 96
			AddComplexComponent( (BaseAddon) this, 5645, 4, 3, 4, 1986, -1, "princessbed", 1);// 97
			AddComplexComponent( (BaseAddon) this, 4436, 4, -3, 4, 1986, -1, "princessbed", 1);// 98
			AddComplexComponent( (BaseAddon) this, 4436, -3, -4, 4, 1986, -1, "princessbed", 1);// 99
			AddComplexComponent( (BaseAddon) this, 4436, -5, -3, 4, 1986, -1, "princessbed", 1);// 100
			AddComplexComponent( (BaseAddon) this, 4436, 1, -4, 4, 1986, -1, "princessbed", 1);// 101
			AddComplexComponent( (BaseAddon) this, 4436, 2, -3, 4, 1986, -1, "princessbed", 1);// 102
			AddComplexComponent( (BaseAddon) this, 4436, 3, -3, 4, 1986, -1, "princessbed", 1);// 103
			AddComplexComponent( (BaseAddon) this, 4436, -2, -3, 4, 1986, -1, "princessbed", 1);// 104
			AddComplexComponent( (BaseAddon) this, 4436, 0, -3, 4, 1986, -1, "princessbed", 1);// 105
			AddComplexComponent( (BaseAddon) this, 4436, -4, 1, 4, 1986, -1, "princessbed", 1);// 106
			AddComplexComponent( (BaseAddon) this, 4436, -4, 1, 14, 1986, -1, "princessbed", 1);// 107
			AddComplexComponent( (BaseAddon) this, 4436, -2, 3, 4, 1986, -1, "princessbed", 1);// 108
			AddComplexComponent( (BaseAddon) this, 4436, 0, 3, 4, 1986, -1, "princessbed", 1);// 109
			AddComplexComponent( (BaseAddon) this, 4436, 3, 0, 4, 1986, -1, "princessbed", 1);// 110
			AddComplexComponent( (BaseAddon) this, 4436, 3, -1, 4, 1986, -1, "princessbed", 1);// 111
			AddComplexComponent( (BaseAddon) this, 4436, 4, -4, 4, 1986, -1, "princessbed", 1);// 112
			AddComplexComponent( (BaseAddon) this, 4436, 4, 1, 4, 1986, -1, "princessbed", 1);// 113
			AddComplexComponent( (BaseAddon) this, 4436, 4, -1, 4, 1986, -1, "princessbed", 1);// 114
			AddComplexComponent( (BaseAddon) this, 5646, -4, 4, 4, 1986, -1, "princessbed", 1);// 115
			AddComplexComponent( (BaseAddon) this, 5646, 3, 4, 4, 1986, -1, "princessbed", 1);// 116
			AddComplexComponent( (BaseAddon) this, 4436, 3, 4, 4, 1986, -1, "princessbed", 1);// 117
			AddComplexComponent( (BaseAddon) this, 4436, -4, 4, 4, 1986, -1, "princessbed", 1);// 118
			AddComplexComponent( (BaseAddon) this, 4436, -3, 4, 4, 1986, -1, "princessbed", 1);// 119
			AddComplexComponent( (BaseAddon) this, 4436, -2, 4, 4, 1986, -1, "princessbed", 1);// 120
			AddComplexComponent( (BaseAddon) this, 4436, 1, 4, 4, 1986, -1, "princessbed", 1);// 121
			AddComplexComponent( (BaseAddon) this, 4436, 4, 4, 4, 1986, -1, "princessbed", 1);// 122
			AddComplexComponent( (BaseAddon) this, 4436, 5, 4, 4, 1986, -1, "princessbed", 1);// 123

		}

		public PrincessBedAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PrincessBedAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PrincessBedAddon();
			}
		}

		[Constructable]
		public PrincessBedAddonDeed()
		{
			Name = "PrincessBed";
		}

		public PrincessBedAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}