
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ShadowCouchWestAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13842, 2, 3, 1}, {13842, 2, -2, 0}// 31	32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShadowCouchWestAddonDeed();
			}
		}

		[ Constructable ]
		public ShadowCouchWestAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2916, 1, 1, 0, 1108, -1, "shadow couch", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2914, 1, 2, 0, 1108, -1, "shadow couch", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2915, 1, 0, 0, 1108, -1, "shadow couch", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2760, 1, 2, 0, 1103, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 13855, 1, 3, 5, 1102, -1, "shadow couch", 1);// 5
			AddComplexComponent( (BaseAddon) this, 13855, 1, -1, 5, 1102, -1, "shadow couch", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2765, -1, 1, 0, 1103, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2765, -1, 3, 0, 1103, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2760, 0, 2, 0, 1103, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2594, 1, -1, 5, 1161, 1, "lamp", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 0, 1103, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 0, 1103, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2760, 0, 1, 0, 1103, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2760, 0, -1, 0, 1103, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 13833, 1, -1, 0, 0, -1, "Shadow Couch", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2765, -1, 0, 0, 1103, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2330, 1, 3, 8, 33, -1, "lamp", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6884, 1, -1, 9, 1161, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13833, 1, 3, 0, 0, -1, "Shadow Couch", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 0, 1103, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2330, 1, -1, 8, 33, -1, "lamp", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2594, 1, 3, 5, 1161, 1, "lamp", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2765, -1, 2, 0, 1103, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2765, -1, -1, 0, 1103, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 6884, 1, 3, 9, 1161, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2760, 0, 3, 0, 1103, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 13880, 2, -1, 1, 0, -1, "shadow couch", 1);// 27
			AddComplexComponent( (BaseAddon) this, 13880, 2, 3, 0, 0, -1, "shadow couch", 1);// 28
			AddComplexComponent( (BaseAddon) this, 13880, 2, 1, 1, 0, -1, "shadow couch", 1);// 29
			AddComplexComponent( (BaseAddon) this, 13833, 2, 0, 0, 0, -1, "Shadow Couch", 1);// 30
			AddComplexComponent( (BaseAddon) this, 13880, 2, 2, 1, 0, -1, "shadow couch", 1);// 33
			AddComplexComponent( (BaseAddon) this, 13833, 2, 2, 0, 0, -1, "Shadow Couch", 1);// 34
			AddComplexComponent( (BaseAddon) this, 13833, 2, 1, 0, 0, -1, "Shadow Couch", 1);// 35
			AddComplexComponent( (BaseAddon) this, 13833, 2, 3, 0, 0, -1, "Shadow Couch", 1);// 36
			AddComplexComponent( (BaseAddon) this, 13833, 2, -1, 0, 0, -1, "Shadow Couch", 1);// 37
			AddComplexComponent( (BaseAddon) this, 13880, 2, 0, 1, 0, -1, "shadow couch", 1);// 38

		}

		public ShadowCouchWestAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ShadowCouchWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShadowCouchWestAddon();
			}
		}

		[Constructable]
		public ShadowCouchWestAddonDeed()
		{
			Name = "ShadowCouchWest";
		}

		public ShadowCouchWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}