
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ShadowEvilFireplaceSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13895, -3, -1, 0}, {13898, -4, 0, 0}, {13897, -3, 0, 0}// 1	2	3	
			, {13883, -2, -1, 0}, {13883, -1, -1, 0}, {13849, -4, -1, 0}// 4	5	6	
			, {13838, 0, 0, 0}, {13840, -2, 0, 0}, {13883, 0, -1, 0}// 7	8	9	
			, {13850, 0, 1, 0}, {13854, -4, 1, 0}, {13850, -2, 1, 0}// 10	11	12	
			, {13850, -1, 1, 0}, {13850, -3, 1, 0}, {2541, -2, 0, 4}// 13	19	22	
			, {6658, -3, 2, 6}, {13854, -4, 0, 0}, {5701, 0, 1, 0}// 25	31	32	
			, {4652, 0, 1, 0}, {13882, 2, 0, 0}, {13895, 2, 0, 0}// 33	34	35	
			, {13895, 2, -1, 0}, {13897, 1, 0, 0}, {13897, 1, -1, 0}// 36	37	38	
			, {13854, 3, 1, 0}, {13850, 1, 1, 0}, {13850, 2, 1, 0}// 39	40	42	
			, {6660, 4, 2, 5}, {13854, 3, 0, 0}// 43	47	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShadowEvilFireplaceSouthAddonDeed();
			}
		}

		[ Constructable ]
		public ShadowEvilFireplaceSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1981, -3, 0, 0, 1109, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1981, -2, 0, 0, 1109, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1981, 0, 0, 0, 1109, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1981, -1, 0, 0, 1109, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 13842, -4, 1, 2, 1107, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 7138, -1, 0, 2, 1102, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 7137, -2, 0, 3, 1107, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2416, -2, 0, 10, 32, -1, "blood stew", 1);// 23
			AddComplexComponent( (BaseAddon) this, 4650, -2, 1, 0, 32, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 13850, 0, 0, 21, 1103, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 13850, -1, 0, 21, 1103, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 13850, -2, 0, 21, 1103, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 13850, -3, 0, 21, 1103, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 14733, -1, 1, 4, 0, 1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 13842, 3, 1, 2, 1107, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 13850, 2, 0, 21, 1103, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 13850, 1, 0, 21, 1103, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6232, 1, 1, 0, 0, 1, "", 1);// 46

		}

		public ShadowEvilFireplaceSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ShadowEvilFireplaceSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShadowEvilFireplaceSouthAddon();
			}
		}

		[Constructable]
		public ShadowEvilFireplaceSouthAddonDeed()
		{
			Name = "ShadowEvilFireplaceSouth";
		}

		public ShadowEvilFireplaceSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}