
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ShadowCouchSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13881, -2, -2, 0}, {13842, -3, -2, 0}, {13881, -1, -2, 0}// 1	2	3	
			, {13881, 0, -2, 0}, {13881, 2, -2, 0}, {13881, 1, -2, 0}// 4	30	31	
			, {13842, 2, -2, 1}// 32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShadowCouchSouthAddonDeed();
			}
		}

		[ Constructable ]
		public ShadowCouchSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2760, -2, 1, 0, 1103, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2760, -1, 1, 0, 1103, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 13853, -2, -1, 5, 1102, -1, "shadow couch", 1);// 7
			AddComplexComponent( (BaseAddon) this, 13833, -2, 0, 0, 0, -1, "Shadow Couch", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2330, -2, 0, 8, 33, -1, "lamp", 1);// 9
			AddComplexComponent( (BaseAddon) this, 13853, 0, -1, 5, 1102, -1, "shadow couch", 1);// 10
			AddComplexComponent( (BaseAddon) this, 5029, -2, -1, 5, 1103, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 13853, -1, -1, 5, 1102, -1, "shadow couch", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2768, -2, 2, 0, 1103, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2760, -1, 0, 0, 1103, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 5535, -1, 0, 12, 33, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 5029, 0, -1, 5, 1103, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2594, -2, 0, 5, 1161, 1, "lamp", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6884, -2, 0, 9, 1161, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 13855, -2, 0, 5, 1102, -1, "shadow couch", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2760, 0, 0, 0, 1103, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 5015, -1, -1, 5, 33, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 13833, -1, -1, 0, 0, -1, "Shadow Couch", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2768, -1, 2, 0, 1103, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2768, 0, 2, 0, 1103, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 13833, -2, -1, 0, 0, -1, "Shadow Couch", 1);// 25
			AddComplexComponent( (BaseAddon) this, 13833, 0, -1, 0, 0, -1, "Shadow Couch", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2760, 0, 1, 0, 1103, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2922, 0, 0, 0, 1108, -1, "shadow couch", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2921, -1, 0, 0, 1108, -1, "shadow couch", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2768, 1, 2, 0, 1103, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2760, 2, 1, 0, 1103, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2760, 1, 1, 0, 1103, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 13855, 2, 0, 5, 1102, -1, "shadow couch", 1);// 36
			AddComplexComponent( (BaseAddon) this, 13853, 1, -1, 5, 1102, -1, "shadow couch", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2330, 2, 0, 8, 33, -1, "lamp", 1);// 38
			AddComplexComponent( (BaseAddon) this, 2768, 2, 2, 0, 1103, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 13833, 1, -1, 0, 0, -1, "Shadow Couch", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2594, 2, 0, 5, 1161, 1, "lamp", 1);// 41
			AddComplexComponent( (BaseAddon) this, 5029, 2, -1, 5, 1103, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 2760, 1, 0, 0, 1103, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 5030, 1, -1, 5, 33, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 13853, 2, -1, 5, 1102, -1, "shadow couch", 1);// 45
			AddComplexComponent( (BaseAddon) this, 6884, 2, 0, 9, 1161, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 5535, 3, 0, 12, 33, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 13833, 2, 0, 0, 0, -1, "Shadow Couch", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2920, 1, 0, 0, 1108, -1, "shadow couch", 1);// 49
			AddComplexComponent( (BaseAddon) this, 13833, 2, -1, 0, 0, -1, "Shadow Couch", 1);// 50

		}

		public ShadowCouchSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ShadowCouchSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShadowCouchSouthAddon();
			}
		}

		[Constructable]
		public ShadowCouchSouthAddonDeed()
		{
			Name = "ShadowCouchSouth";
		}

		public ShadowCouchSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}