
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ShowEvilFireplaceEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {13896, 0, -3, 0}, {13896, 0, 1, 0}, {13898, 0, 2, 0}// 1	2	3	
			, {13882, -1, 2, 0}, {13882, -1, 1, 0}, {13882, -1, 0, 0}// 4	5	6	
			, {13882, -1, -1, 0}, {13882, -1, -2, 0}, {13883, 0, 2, 0}// 7	8	9	
			, {13839, 0, 0, 0}, {13841, 0, -2, 0}, {13878, 0, -1, 15}// 10	11	12	
			, {13883, 0, -4, 0}, {13882, -1, -3, 0}, {13849, -1, -4, 0}// 13	14	15	
			, {13854, 1, 3, 0}, {13854, 1, -4, 0}, {13850, 1, -2, 0}// 20	21	22	
			, {13850, 1, -3, 0}, {13850, 1, -1, 0}, {13850, 1, 0, 0}// 23	24	25	
			, {13850, 1, 1, 0}, {13850, 1, 2, 0}, {13854, 0, 3, 0}// 26	27	28	
			, {13854, 0, -4, 0}, {2541, 0, -2, 4}, {4650, 1, -2, 0}// 29	40	43	
			, {6657, 2, 4, 7}, {6659, 2, -3, 7}, {4652, 1, 0, 0}// 44	45	47	
			, {5701, 1, 0, 0}// 48	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShowEvilFireplaceEastAddonDeed();
			}
		}

		[ Constructable ]
		public ShowEvilFireplaceEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1981, 0, -3, 0, 1109, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1981, 0, -2, 0, 1109, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1981, 0, 0, 0, 1109, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1981, 0, -1, 0, 1109, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 13850, 0, 2, 21, 1103, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 13850, 0, 1, 21, 1103, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 13850, 0, 0, 21, 1103, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 13850, 0, -1, 21, 1103, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 13850, 0, -2, 21, 1103, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 13850, 0, -3, 21, 1103, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 13842, 1, 3, 1, 1107, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 13842, 1, -4, 1, 1107, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 7135, 0, -1, 2, 1102, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 7134, 0, -1, 2, 1102, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2416, 0, -2, 10, 32, -1, "blood stew", 1);// 41
			AddComplexComponent( (BaseAddon) this, 14742, 1, -1, 4, 0, 1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 6230, 1, 1, 0, 0, 1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 7134, 0, -2, 3, 1107, -1, "", 1);// 49

		}

		public ShowEvilFireplaceEastAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ShowEvilFireplaceEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShowEvilFireplaceEastAddon();
			}
		}

		[Constructable]
		public ShowEvilFireplaceEastAddonDeed()
		{
			Name = "ShowEvilFireplaceEast";
		}

		public ShowEvilFireplaceEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}