
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class StableAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10593, 7, 0, 20}, {10593, 7, 1, 20}, {2187, 7, -3, 20}// 231	232	273	
			, {10593, 7, -3, 20}, {10593, 7, -1, 20}, {10593, 7, -2, 20}// 288	294	299	
			, {2186, 7, -4, 20}, {2187, 7, -2, 20}, {2187, 7, 1, 20}// 306	308	340	
			, {2186, 7, 1, 20}, {2187, 7, -1, 20}, {2187, 7, 1, 20}// 379	402	419	
			, {2187, 7, 0, 20}, {147, 7, 1, 0}, {326, 7, -3, 0}// 421	498	499	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new StableAddonDeed();
			}
		}

		[ Constructable ]
		public StableAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 10592, -3, 2, 20, 0, -1, "Stable", 1);// 1
			AddComplexComponent( (BaseAddon) this, 9989, -1, -2, 48, 0, -1, "Stable", 1);// 2
			AddComplexComponent( (BaseAddon) this, 148, -4, 2, 20, 0, -1, "Stable", 1);// 3
			AddComplexComponent( (BaseAddon) this, 10592, -1, 6, 20, 0, -1, "Stable", 1);// 4
			AddComplexComponent( (BaseAddon) this, 145, -4, 3, 0, 0, -1, "Stable", 1);// 5
			AddComplexComponent( (BaseAddon) this, 10592, -1, 5, 20, 0, -1, "Stable", 1);// 6
			AddComplexComponent( (BaseAddon) this, 10592, -2, 0, 20, 0, -1, "Stable", 1);// 7
			AddComplexComponent( (BaseAddon) this, 9978, -3, -2, 42, 0, -1, "Stable", 1);// 8
			AddComplexComponent( (BaseAddon) this, 10597, -4, -2, 0, 0, -1, "Stable", 1);// 9
			AddComplexComponent( (BaseAddon) this, 152, -1, -5, 20, 0, 0, "Stable", 1);// 10
			AddComplexComponent( (BaseAddon) this, 148, -4, -4, 20, 0, -1, "Stable", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2147, -4, -3, 0, 0, -1, "Stable", 1);// 12
			AddComplexComponent( (BaseAddon) this, 10592, -1, -1, 20, 0, -1, "Stable", 1);// 13
			AddComplexComponent( (BaseAddon) this, 9990, -3, 4, 42, 0, -1, "Stable", 1);// 14
			AddComplexComponent( (BaseAddon) this, 10592, -2, 1, 20, 0, -1, "Stable", 1);// 15
			AddComplexComponent( (BaseAddon) this, 7977, -3, 3, 21, 0, -1, "Stable", 1);// 16
			AddComplexComponent( (BaseAddon) this, 10592, -2, -1, 20, 0, -1, "Stable", 1);// 17
			AddComplexComponent( (BaseAddon) this, 10597, -2, 2, 0, 0, -1, "Stable", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1850, -1, -3, 10, 0, -1, "Stable", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1850, -2, -4, 15, 0, -1, "Stable", 1);// 20
			AddComplexComponent( (BaseAddon) this, 10592, -3, 3, 0, 0, -1, "Stable", 1);// 21
			AddComplexComponent( (BaseAddon) this, 9994, -2, -4, 42, 0, -1, "Stable", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2148, -2, 4, 20, 0, -1, "Stable", 1);// 23
			AddComplexComponent( (BaseAddon) this, 146, -3, -5, 20, 0, -1, "Stable", 1);// 24
			AddComplexComponent( (BaseAddon) this, 10592, -3, -3, 15, 0, -1, "Stable", 1);// 25
			AddComplexComponent( (BaseAddon) this, 10597, -4, -1, 0, 0, -1, "Stable", 1);// 26
			AddComplexComponent( (BaseAddon) this, 10597, -4, 1, 0, 0, -1, "Stable", 1);// 27
			AddComplexComponent( (BaseAddon) this, 9994, -1, -3, 45, 0, -1, "Stable", 1);// 28
			AddComplexComponent( (BaseAddon) this, 10597, -3, 1, 0, 0, -1, "Stable", 1);// 29
			AddComplexComponent( (BaseAddon) this, 153, -4, 0, 20, 0, 1, "Stable", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1848, -2, -4, 5, 0, -1, "Stable", 1);// 31
			AddComplexComponent( (BaseAddon) this, 10597, -1, -2, 0, 0, -1, "Stable", 1);// 32
			AddComplexComponent( (BaseAddon) this, 147, -2, 3, 0, 0, -1, "Stable", 1);// 33
			AddComplexComponent( (BaseAddon) this, 10597, -3, -3, 0, 0, -1, "Stable", 1);// 34
			AddComplexComponent( (BaseAddon) this, 148, -4, -3, 20, 0, -1, "Stable", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1848, -3, -3, 15, 0, -1, "Stable", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2147, -5, -3, 0, 0, -1, "Stable", 1);// 37
			AddComplexComponent( (BaseAddon) this, 3894, -1, -3, 5, 0, -1, "Stable", 1);// 38
			AddComplexComponent( (BaseAddon) this, 10597, -2, -2, 0, 0, -1, "Stable", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1848, -1, -4, 5, 0, -1, "Stable", 1);// 40
			AddComplexComponent( (BaseAddon) this, 10597, -2, 0, 0, 0, -1, "Stable", 1);// 41
			AddComplexComponent( (BaseAddon) this, 3894, -3, -3, 7, 0, -1, "Stable", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1848, -3, -4, 15, 0, -1, "Stable", 1);// 43
			AddComplexComponent( (BaseAddon) this, 9978, -1, 1, 48, 0, -1, "Stable", 1);// 44
			AddComplexComponent( (BaseAddon) this, 3894, -2, -3, 5, 0, -1, "Stable", 1);// 45
			AddComplexComponent( (BaseAddon) this, 9978, -2, -2, 45, 0, -1, "Stable", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1850, -2, -3, 15, 0, -1, "Stable", 1);// 47
			AddComplexComponent( (BaseAddon) this, 9993, -1, 4, 42, 0, -1, "Stable", 1);// 48
			AddComplexComponent( (BaseAddon) this, 10592, -1, 1, 20, 0, -1, "Stable", 1);// 49
			AddComplexComponent( (BaseAddon) this, 10597, -3, -4, 0, 0, -1, "Stable", 1);// 50
			AddComplexComponent( (BaseAddon) this, 9978, -3, 2, 42, 0, -1, "Stable", 1);// 51
			AddComplexComponent( (BaseAddon) this, 148, -4, 3, 20, 0, -1, "Stable", 1);// 52
			AddComplexComponent( (BaseAddon) this, 9994, -1, -4, 42, 0, -1, "Stable", 1);// 53
			AddComplexComponent( (BaseAddon) this, 153, -4, -1, 20, 0, 1, "Stable", 1);// 54
			AddComplexComponent( (BaseAddon) this, 10597, -1, -3, 0, 0, -1, "Stable", 1);// 55
			AddComplexComponent( (BaseAddon) this, 10597, -5, -1, 0, 0, -1, "Stable", 1);// 56
			AddComplexComponent( (BaseAddon) this, 10593, -4, 1, 20, 0, -1, "Stable", 1);// 57
			AddComplexComponent( (BaseAddon) this, 148, -4, 3, 20, 0, -1, "Stable", 1);// 58
			AddComplexComponent( (BaseAddon) this, 2148, -6, 0, 0, 0, -1, "Stable", 1);// 59
			AddComplexComponent( (BaseAddon) this, 147, -4, 3, 0, 0, -1, "Stable", 1);// 60
			AddComplexComponent( (BaseAddon) this, 9978, -2, 1, 45, 0, -1, "Stable", 1);// 61
			AddComplexComponent( (BaseAddon) this, 9993, -1, 3, 45, 0, -1, "Stable", 1);// 62
			AddComplexComponent( (BaseAddon) this, 10592, -1, -2, 20, 0, -1, "Stable", 1);// 63
			AddComplexComponent( (BaseAddon) this, 9990, -2, 3, 45, 0, -1, "Stable", 1);// 64
			AddComplexComponent( (BaseAddon) this, 10592, -2, 2, 20, 0, -1, "Stable", 1);// 65
			AddComplexComponent( (BaseAddon) this, 3894, -3, -4, 0, 0, -1, "Stable", 1);// 66
			AddComplexComponent( (BaseAddon) this, 10592, -1, 3, 24, 0, -1, "Stable", 1);// 67
			AddComplexComponent( (BaseAddon) this, 10597, -5, 0, 0, 0, -1, "Stable", 1);// 68
			AddComplexComponent( (BaseAddon) this, 10597, -5, 1, 0, 0, -1, "Stable", 1);// 69
			AddComplexComponent( (BaseAddon) this, 10592, -2, -2, 20, 0, -1, "Stable", 1);// 70
			AddComplexComponent( (BaseAddon) this, 10597, -4, 0, 0, 0, -1, "Stable", 1);// 71
			AddComplexComponent( (BaseAddon) this, 10597, -1, -1, 0, 0, -1, "Stable", 1);// 72
			AddComplexComponent( (BaseAddon) this, 2148, -6, 1, 0, 0, -1, "Stable", 1);// 73
			AddComplexComponent( (BaseAddon) this, 9978, -3, -1, 42, 0, -1, "Stable", 1);// 74
			AddComplexComponent( (BaseAddon) this, 10592, -2, 3, 20, 0, -1, "Stable", 1);// 75
			AddComplexComponent( (BaseAddon) this, 9990, -1, 2, 48, 0, -1, "Stable", 1);// 76
			AddComplexComponent( (BaseAddon) this, 9993, -2, 4, 42, 0, -1, "Stable", 1);// 77
			AddComplexComponent( (BaseAddon) this, 146, -3, 3, 20, 0, -1, "Stable", 1);// 78
			AddComplexComponent( (BaseAddon) this, 10597, -2, -4, 0, 0, -1, "Stable", 1);// 79
			AddComplexComponent( (BaseAddon) this, 147, -4, 3, 20, 0, -1, "Stable", 1);// 80
			AddComplexComponent( (BaseAddon) this, 9978, -2, -1, 45, 0, -1, "Stable", 1);// 81
			AddComplexComponent( (BaseAddon) this, 147, -4, -5, 20, 0, -1, "Stable", 1);// 82
			AddComplexComponent( (BaseAddon) this, 9978, -2, 0, 45, 0, -1, "Stable", 1);// 83
			AddComplexComponent( (BaseAddon) this, 10597, -5, -2, 0, 0, -1, "Stable", 1);// 84
			AddComplexComponent( (BaseAddon) this, 9978, -1, 0, 48, 0, -1, "Stable", 1);// 85
			AddComplexComponent( (BaseAddon) this, 10592, -1, 4, 20, 0, -1, "Stable", 1);// 86
			AddComplexComponent( (BaseAddon) this, 145, -4, -3, 0, 0, -1, "Stable", 1);// 87
			AddComplexComponent( (BaseAddon) this, 10592, -1, 3, 20, 0, -1, "Stable", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1848, -2, -4, 10, 0, -1, "Stable", 1);// 89
			AddComplexComponent( (BaseAddon) this, 9978, -3, 1, 42, 0, -1, "Stable", 1);// 90
			AddComplexComponent( (BaseAddon) this, 10597, -3, -2, 0, 0, -1, "Stable", 1);// 91
			AddComplexComponent( (BaseAddon) this, 10597, -5, 0, 0, 0, -1, "Stable", 1);// 92
			AddComplexComponent( (BaseAddon) this, 9978, -3, 3, 42, 0, -1, "Stable", 1);// 93
			AddComplexComponent( (BaseAddon) this, 10592, -3, 1, 20, 0, -1, "Stable", 1);// 94
			AddComplexComponent( (BaseAddon) this, 10592, -3, 3, 20, 0, -1, "Stable", 1);// 95
			AddComplexComponent( (BaseAddon) this, 10592, -3, -2, 20, 0, -1, "Stable", 1);// 96
			AddComplexComponent( (BaseAddon) this, 146, -1, -5, 0, 0, -1, "Stable", 1);// 97
			AddComplexComponent( (BaseAddon) this, 2147, -1, 6, 20, 0, -1, "Stable", 1);// 98
			AddComplexComponent( (BaseAddon) this, 10597, -4, 0, 0, 0, -1, "Stable", 1);// 99
			AddComplexComponent( (BaseAddon) this, 148, -4, 1, 20, 0, -1, "Stable", 1);// 100
			AddComplexComponent( (BaseAddon) this, 10593, -3, -2, 20, 0, -1, "Stable", 1);// 101
			AddComplexComponent( (BaseAddon) this, 10592, -3, 2, 0, 0, -1, "Stable", 1);// 102
			AddComplexComponent( (BaseAddon) this, 2148, -6, -2, 0, 0, -1, "Stable", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1848, -3, -4, 10, 0, -1, "Stable", 1);// 104
			AddComplexComponent( (BaseAddon) this, 10597, -2, -1, 0, 0, -1, "Stable", 1);// 105
			AddComplexComponent( (BaseAddon) this, 9978, -3, 0, 42, 0, -1, "Stable", 1);// 106
			AddComplexComponent( (BaseAddon) this, 10597, -1, 2, 0, 0, -1, "Stable", 1);// 107
			AddComplexComponent( (BaseAddon) this, 10592, -2, -3, 0, 0, -1, "Stable", 1);// 108
			AddComplexComponent( (BaseAddon) this, 145, -4, -4, 0, 0, -1, "Stable", 1);// 109
			AddComplexComponent( (BaseAddon) this, 10592, -3, 0, 20, 0, -1, "Stable", 1);// 110
			AddComplexComponent( (BaseAddon) this, 10597, -3, 0, 0, 0, -1, "Stable", 1);// 111
			AddComplexComponent( (BaseAddon) this, 7836, -1, 4, 31, 0, -1, "Stable", 1);// 112
			AddComplexComponent( (BaseAddon) this, 148, -4, 1, 20, 0, -1, "Stable", 1);// 113
			AddComplexComponent( (BaseAddon) this, 10593, -3, 0, 20, 0, -1, "Stable", 1);// 114
			AddComplexComponent( (BaseAddon) this, 10593, -3, -1, 20, 0, -1, "Stable", 1);// 115
			AddComplexComponent( (BaseAddon) this, 2148, -6, -1, 0, 0, -1, "Stable", 1);// 116
			AddComplexComponent( (BaseAddon) this, 10597, -3, 2, 0, 0, -1, "Stable", 1);// 117
			AddComplexComponent( (BaseAddon) this, 9978, -3, -3, 42, 0, -1, "Stable", 1);// 118
			AddComplexComponent( (BaseAddon) this, 10597, -2, 3, 0, 0, -1, "Stable", 1);// 119
			AddComplexComponent( (BaseAddon) this, 146, -3, -5, 0, 0, -1, "Stable", 1);// 120
			AddComplexComponent( (BaseAddon) this, 10593, -4, 1, 20, 0, -1, "Stable", 1);// 121
			AddComplexComponent( (BaseAddon) this, 3894, -1, -3, 0, 0, -1, "Stable", 1);// 122
			AddComplexComponent( (BaseAddon) this, 3894, -2, -3, 0, 0, -1, "Stable", 1);// 123
			AddComplexComponent( (BaseAddon) this, 147, -4, -5, 0, 0, -1, "Stable", 1);// 124
			AddComplexComponent( (BaseAddon) this, 10592, -3, -1, 20, 0, -1, "Stable", 1);// 125
			AddComplexComponent( (BaseAddon) this, 3894, -3, -3, 2, 0, -1, "Stable", 1);// 126
			AddComplexComponent( (BaseAddon) this, 146, -2, -5, 20, 0, -1, "Stable", 1);// 127
			AddComplexComponent( (BaseAddon) this, 10597, -2, 1, 0, 0, -1, "Stable", 1);// 128
			AddComplexComponent( (BaseAddon) this, 152, -2, 3, 20, 0, 1, "Stable", 1);// 129
			AddComplexComponent( (BaseAddon) this, 10597, -1, -4, 0, 0, -1, "Stable", 1);// 130
			AddComplexComponent( (BaseAddon) this, 10593, -4, 2, 20, 0, -1, "Stable", 1);// 131
			AddComplexComponent( (BaseAddon) this, 3894, -3, 0, 26, 0, -1, "Stable", 1);// 132
			AddComplexComponent( (BaseAddon) this, 4109, -1, 1, 25, 0, -1, "Stable", 1);// 133
			AddComplexComponent( (BaseAddon) this, 10597, -1, 1, 0, 0, -1, "Stable", 1);// 134
			AddComplexComponent( (BaseAddon) this, 10593, -3, 1, 20, 0, -1, "Stable", 1);// 135
			AddComplexComponent( (BaseAddon) this, 3894, -3, 0, 20, 0, -1, "Stable", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1848, -3, -4, 5, 0, -1, "Stable", 1);// 137
			AddComplexComponent( (BaseAddon) this, 10555, -2, 3, 0, 0, -1, "Stable", 1);// 138
			AddComplexComponent( (BaseAddon) this, 10597, -1, 0, 0, 0, -1, "Stable", 1);// 139
			AddComplexComponent( (BaseAddon) this, 152, -1, 3, 1, 0, 1, "Stable", 1);// 140
			AddComplexComponent( (BaseAddon) this, 2252, -1, 5, 20, 0, -1, "Stable", 1);// 141
			AddComplexComponent( (BaseAddon) this, 3894, -3, 1, 25, 0, -1, "Stable", 1);// 142
			AddComplexComponent( (BaseAddon) this, 3894, -3, 1, 20, 0, -1, "Stable", 1);// 143
			AddComplexComponent( (BaseAddon) this, 10593, -3, 2, 20, 0, -1, "Stable", 1);// 144
			AddComplexComponent( (BaseAddon) this, 2148, -2, 5, 20, 0, -1, "Stable", 1);// 145
			AddComplexComponent( (BaseAddon) this, 9978, -2, 2, 45, 0, -1, "Stable", 1);// 146
			AddComplexComponent( (BaseAddon) this, 146, -2, -5, 0, 0, -1, "Stable", 1);// 147
			AddComplexComponent( (BaseAddon) this, 9989, -3, -4, 42, 0, -1, "Stable", 1);// 148
			AddComplexComponent( (BaseAddon) this, 10597, -3, -1, 0, 0, -1, "Stable", 1);// 149
			AddComplexComponent( (BaseAddon) this, 10597, -1, 3, 0, 0, -1, "Stable", 1);// 150
			AddComplexComponent( (BaseAddon) this, 10592, -2, 3, 0, 0, -1, "Stable", 1);// 151
			AddComplexComponent( (BaseAddon) this, 2147, -5, 1, 0, 0, -1, "Stable", 1);// 152
			AddComplexComponent( (BaseAddon) this, 10592, -1, 2, 20, 0, -1, "Stable", 1);// 153
			AddComplexComponent( (BaseAddon) this, 9989, -2, -3, 45, 0, -1, "Stable", 1);// 154
			AddComplexComponent( (BaseAddon) this, 2148, -2, 6, 20, 0, -1, "Stable", 1);// 155
			AddComplexComponent( (BaseAddon) this, 148, -4, -2, 20, 0, -1, "Stable", 1);// 156
			AddComplexComponent( (BaseAddon) this, 10593, -3, 1, 20, 0, -1, "Stable", 1);// 157
			AddComplexComponent( (BaseAddon) this, 9978, -1, -1, 48, 0, -1, "Stable", 1);// 158
			AddComplexComponent( (BaseAddon) this, 4150, -2, 0, 0, 0, -1, "Stable", 1);// 159
			AddComplexComponent( (BaseAddon) this, 2177, -1, -2, 20, 0, -1, "Stable", 1);// 160
			AddComplexComponent( (BaseAddon) this, 2177, -2, -2, 20, 0, -1, "Stable", 1);// 161
			AddComplexComponent( (BaseAddon) this, 10592, -4, 2, 0, 0, -1, "Stable", 1);// 162
			AddComplexComponent( (BaseAddon) this, 2923, -5, -1, 0, 0, -1, "Stable", 1);// 163
			AddComplexComponent( (BaseAddon) this, 2924, -5, -2, 0, 0, -1, "Stable", 1);// 164
			AddComplexComponent( (BaseAddon) this, 4976, -5, -2, 6, 0, -1, "Stable", 1);// 165
			AddComplexComponent( (BaseAddon) this, 4979, -5, -2, 6, 0, -1, "Stable", 1);// 166
			AddComplexComponent( (BaseAddon) this, 4981, -5, -1, 6, 0, -1, "Stable", 1);// 167
			AddComplexComponent( (BaseAddon) this, 3896, -4, 1, 4, 0, -1, "Stable", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1850, -1, -4, 10, 0, -1, "Stable", 1);// 169
			AddComplexComponent( (BaseAddon) this, 4022, -3, -1, 0, 0, -1, "Stable", 1);// 170
			AddComplexComponent( (BaseAddon) this, 10592, -3, -1, 20, 0, -1, "Stable", 1);// 171
			AddComplexComponent( (BaseAddon) this, 10592, -3, 0, 20, 0, -1, "Stable", 1);// 172
			AddComplexComponent( (BaseAddon) this, 10592, -3, 1, 20, 0, -1, "Stable", 1);// 173
			AddComplexComponent( (BaseAddon) this, 10592, -2, -1, 20, 0, -1, "Stable", 1);// 174
			AddComplexComponent( (BaseAddon) this, 10592, -2, 0, 20, 0, -1, "Stable", 1);// 175
			AddComplexComponent( (BaseAddon) this, 10592, -2, 1, 20, 0, -1, "Stable", 1);// 176
			AddComplexComponent( (BaseAddon) this, 10592, -1, -1, 20, 0, -1, "Stable", 1);// 177
			AddComplexComponent( (BaseAddon) this, 10592, -1, 0, 20, 0, -1, "Stable", 1);// 178
			AddComplexComponent( (BaseAddon) this, 10592, -1, 1, 20, 0, -1, "Stable", 1);// 179
			AddComplexComponent( (BaseAddon) this, 325, -1, 6, 0, 0, -1, "Stable", 1);// 180
			AddComplexComponent( (BaseAddon) this, 10597, 3, 1, 0, 0, -1, "Stable", 1);// 181
			AddComplexComponent( (BaseAddon) this, 10597, 1, -1, 0, 0, -1, "Stable", 1);// 182
			AddComplexComponent( (BaseAddon) this, 10597, 3, -1, 0, 0, -1, "Stable", 1);// 183
			AddComplexComponent( (BaseAddon) this, 10597, 3, 0, 0, 0, -1, "Stable", 1);// 184
			AddComplexComponent( (BaseAddon) this, 144, 4, 3, 0, 0, -1, "Stable", 1);// 185
			AddComplexComponent( (BaseAddon) this, 10597, 2, -1, 0, 0, -1, "Stable", 1);// 186
			AddComplexComponent( (BaseAddon) this, 148, 4, -4, 20, 0, -1, "Stable", 1);// 187
			AddComplexComponent( (BaseAddon) this, 10597, 3, -2, 0, 0, -1, "Stable", 1);// 188
			AddComplexComponent( (BaseAddon) this, 9993, 3, 4, 42, 0, -1, "Stable", 1);// 189
			AddComplexComponent( (BaseAddon) this, 1850, 0, -4, 5, 0, -1, "Stable", 1);// 190
			AddComplexComponent( (BaseAddon) this, 152, 1, -5, 20, 0, 0, "Stable", 1);// 191
			AddComplexComponent( (BaseAddon) this, 152, 1, 3, 0, 0, 1, "Stable", 1);// 192
			AddComplexComponent( (BaseAddon) this, 10597, 5, -2, 0, 0, -1, "Stable", 1);// 193
			AddComplexComponent( (BaseAddon) this, 10597, 5, -3, 0, 0, -1, "Stable", 1);// 194
			AddComplexComponent( (BaseAddon) this, 10592, 2, 4, 20, 0, -1, "Stable", 1);// 195
			AddComplexComponent( (BaseAddon) this, 10592, 2, 3, 20, 0, -1, "Stable", 1);// 196
			AddComplexComponent( (BaseAddon) this, 10592, 1, 6, 20, 0, -1, "Stable", 1);// 197
			AddComplexComponent( (BaseAddon) this, 3892, 1, 6, 8, 0, -1, "Stable", 1);// 198
			AddComplexComponent( (BaseAddon) this, 10597, 4, 2, 0, 0, -1, "Stable", 1);// 199
			AddComplexComponent( (BaseAddon) this, 10597, 4, -2, 0, 0, -1, "Stable", 1);// 200
			AddComplexComponent( (BaseAddon) this, 10597, 4, 0, 0, 0, -1, "Stable", 1);// 201
			AddComplexComponent( (BaseAddon) this, 10597, 4, 1, 0, 0, -1, "Stable", 1);// 202
			AddComplexComponent( (BaseAddon) this, 10597, 4, -1, 0, 0, -1, "Stable", 1);// 203
			AddComplexComponent( (BaseAddon) this, 10592, 0, 0, 20, 0, -1, "Stable", 1);// 204
			AddComplexComponent( (BaseAddon) this, 152, 0, 3, 0, 0, 1, "Stable", 1);// 205
			AddComplexComponent( (BaseAddon) this, 2147, 0, 6, 20, 0, -1, "Stable", 1);// 206
			AddComplexComponent( (BaseAddon) this, 10597, 6, 0, 0, 0, -1, "Stable", 1);// 207
			AddComplexComponent( (BaseAddon) this, 10592, 1, 3, 20, 0, -1, "Stable", 1);// 208
			AddComplexComponent( (BaseAddon) this, 10592, 0, 0, 20, 0, -1, "Stable", 1);// 209
			AddComplexComponent( (BaseAddon) this, 1850, 1, -3, 0, 0, -1, "Stable", 1);// 210
			AddComplexComponent( (BaseAddon) this, 148, 4, 3, 20, 0, -1, "Stable", 1);// 211
			AddComplexComponent( (BaseAddon) this, 10597, 6, -2, 0, 0, -1, "Stable", 1);// 212
			AddComplexComponent( (BaseAddon) this, 10597, 6, -3, 0, 0, -1, "Stable", 1);// 213
			AddComplexComponent( (BaseAddon) this, 3894, 1, 5, 0, 0, -1, "Stable", 1);// 214
			AddComplexComponent( (BaseAddon) this, 10592, 1, 4, 20, 0, -1, "Stable", 1);// 215
			AddComplexComponent( (BaseAddon) this, 9993, 3, 3, 45, 0, -1, "Stable", 1);// 216
			AddComplexComponent( (BaseAddon) this, 6963, 1, 6, 11, 1172, -1, "Stable", 1);// 217
			AddComplexComponent( (BaseAddon) this, 10597, 5, 1, 0, 0, -1, "Stable", 1);// 218
			AddComplexComponent( (BaseAddon) this, 147, 4, -5, 0, 0, -1, "Stable", 1);// 219
			AddComplexComponent( (BaseAddon) this, 10592, 4, -1, 20, 0, -1, "Stable", 1);// 220
			AddComplexComponent( (BaseAddon) this, 152, 0, -5, 20, 0, 0, "Stable", 1);// 221
			AddComplexComponent( (BaseAddon) this, 9991, 4, -3, 45, 0, -1, "Stable", 1);// 222
			AddComplexComponent( (BaseAddon) this, 10597, 5, 0, 0, 0, -1, "Stable", 1);// 223
			AddComplexComponent( (BaseAddon) this, 1850, 0, -3, 5, 0, -1, "Stable", 1);// 224
			AddComplexComponent( (BaseAddon) this, 147, 4, -4, 20, 0, -1, "Stable", 1);// 225
			AddComplexComponent( (BaseAddon) this, 145, 4, -4, 0, 0, -1, "Stable", 1);// 226
			AddComplexComponent( (BaseAddon) this, 146, 3, -5, 20, 0, -1, "Stable", 1);// 227
			AddComplexComponent( (BaseAddon) this, 2147, 4, 1, 20, 0, -1, "Stable", 1);// 228
			AddComplexComponent( (BaseAddon) this, 4150, 5, -2, 20, 0, -1, "Stable", 1);// 229
			AddComplexComponent( (BaseAddon) this, 9977, 2, 0, 51, 0, -1, "Stable", 1);// 230
			AddComplexComponent( (BaseAddon) this, 10592, 2, -1, 20, 0, -1, "Stable", 1);// 233
			AddComplexComponent( (BaseAddon) this, 9977, 3, -1, 48, 0, -1, "Stable", 1);// 234
			AddComplexComponent( (BaseAddon) this, 9990, 0, 1, 51, 0, -1, "Stable", 1);// 235
			AddComplexComponent( (BaseAddon) this, 10597, 6, 1, 0, 0, -1, "Stable", 1);// 236
			AddComplexComponent( (BaseAddon) this, 10592, 0, 4, 20, 0, -1, "Stable", 1);// 237
			AddComplexComponent( (BaseAddon) this, 9977, 3, 0, 48, 0, -1, "Stable", 1);// 238
			AddComplexComponent( (BaseAddon) this, 10592, 4, -3, 20, 0, -1, "Stable", 1);// 239
			AddComplexComponent( (BaseAddon) this, 10597, 1, 3, 0, 0, -1, "Stable", 1);// 240
			AddComplexComponent( (BaseAddon) this, 10597, 1, 2, 0, 0, -1, "Stable", 1);// 241
			AddComplexComponent( (BaseAddon) this, 10592, 3, -2, 20, 0, -1, "Stable", 1);// 242
			AddComplexComponent( (BaseAddon) this, 10593, 1, 3, 20, 0, -1, "Stable", 1);// 243
			AddComplexComponent( (BaseAddon) this, 9977, 4, -2, 45, 0, -1, "Stable", 1);// 244
			AddComplexComponent( (BaseAddon) this, 10597, 2, 3, 0, 0, -1, "Stable", 1);// 245
			AddComplexComponent( (BaseAddon) this, 146, 4, -5, 20, 0, -1, "Stable", 1);// 246
			AddComplexComponent( (BaseAddon) this, 10592, 4, 2, 20, 0, -1, "Stable", 1);// 247
			AddComplexComponent( (BaseAddon) this, 9993, 1, 3, 45, 0, -1, "Stable", 1);// 248
			AddComplexComponent( (BaseAddon) this, 10597, 3, 2, 0, 0, -1, "Stable", 1);// 249
			AddComplexComponent( (BaseAddon) this, 10597, 3, 3, 0, 0, -1, "Stable", 1);// 250
			AddComplexComponent( (BaseAddon) this, 10593, 4, -1, 20, 0, -1, "Stable", 1);// 251
			AddComplexComponent( (BaseAddon) this, 10592, 2, 3, 20, 0, -1, "Stable", 1);// 252
			AddComplexComponent( (BaseAddon) this, 1850, 1, -4, 0, 0, -1, "Stable", 1);// 253
			AddComplexComponent( (BaseAddon) this, 10597, 4, 2, 0, 0, -1, "Stable", 1);// 254
			AddComplexComponent( (BaseAddon) this, 10597, 2, -4, 0, 0, -1, "Stable", 1);// 255
			AddComplexComponent( (BaseAddon) this, 10597, 4, 3, 0, 0, -1, "Stable", 1);// 256
			AddComplexComponent( (BaseAddon) this, 10597, 2, 2, 0, 0, -1, "Stable", 1);// 257
			AddComplexComponent( (BaseAddon) this, 10592, 2, 6, 20, 0, -1, "Stable", 1);// 258
			AddComplexComponent( (BaseAddon) this, 10592, 2, 5, 20, 0, -1, "Stable", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1848, 0, -4, 0, 0, -1, "Stable", 1);// 260
			AddComplexComponent( (BaseAddon) this, 10592, 0, 3, 20, 0, -1, "Stable", 1);// 261
			AddComplexComponent( (BaseAddon) this, 10597, 2, 1, 0, 0, -1, "Stable", 1);// 262
			AddComplexComponent( (BaseAddon) this, 10593, 4, 1, 20, 0, -1, "Stable", 1);// 263
			AddComplexComponent( (BaseAddon) this, 10597, 1, 0, 0, 0, -1, "Stable", 1);// 264
			AddComplexComponent( (BaseAddon) this, 10593, 6, -2, 20, 0, -1, "Stable", 1);// 265
			AddComplexComponent( (BaseAddon) this, 9994, 1, -3, 45, 0, -1, "Stable", 1);// 266
			AddComplexComponent( (BaseAddon) this, 10597, 2, -2, 0, 0, -1, "Stable", 1);// 267
			AddComplexComponent( (BaseAddon) this, 2148, 2, 6, 20, 0, -1, "Stable", 1);// 268
			AddComplexComponent( (BaseAddon) this, 14238, 0, 5, 20, 1045, -1, "Stable", 1);// 269
			AddComplexComponent( (BaseAddon) this, 10592, 3, 1, 20, 0, -1, "Stable", 1);// 270
			AddComplexComponent( (BaseAddon) this, 9994, 0, -3, 45, 0, -1, "Stable", 1);// 271
			AddComplexComponent( (BaseAddon) this, 9993, 2, 4, 42, 0, -1, "Stable", 1);// 272
			AddComplexComponent( (BaseAddon) this, 9977, 3, 1, 48, 0, -1, "Stable", 1);// 274
			AddComplexComponent( (BaseAddon) this, 10592, 4, -4, 20, 0, -1, "Stable", 1);// 275
			AddComplexComponent( (BaseAddon) this, 10597, 1, 2, 0, 0, -1, "Stable", 1);// 276
			AddComplexComponent( (BaseAddon) this, 10592, 2, 2, 20, 0, -1, "Stable", 1);// 277
			AddComplexComponent( (BaseAddon) this, 10592, 3, -4, 20, 0, -1, "Stable", 1);// 278
			AddComplexComponent( (BaseAddon) this, 9989, 0, -1, 51, 0, -1, "Stable", 1);// 279
			AddComplexComponent( (BaseAddon) this, 146, 2, -5, 0, 0, -1, "Stable", 1);// 280
			AddComplexComponent( (BaseAddon) this, 893, 0, 5, 14, 1037, -1, "Stable", 1);// 281
			AddComplexComponent( (BaseAddon) this, 14238, 0, 5, 24, 1045, -1, "Stable", 1);// 282
			AddComplexComponent( (BaseAddon) this, 152, 3, 3, 20, 0, 1, "Stable", 1);// 283
			AddComplexComponent( (BaseAddon) this, 152, 0, -5, 0, 0, 1, "Stable", 1);// 284
			AddComplexComponent( (BaseAddon) this, 10597, 4, -3, 0, 0, -1, "Stable", 1);// 285
			AddComplexComponent( (BaseAddon) this, 10597, 0, -4, 0, 0, -1, "Stable", 1);// 286
			AddComplexComponent( (BaseAddon) this, 9994, 1, -2, 48, 0, -1, "Stable", 1);// 287
			AddComplexComponent( (BaseAddon) this, 10593, 6, -3, 20, 0, -1, "Stable", 1);// 289
			AddComplexComponent( (BaseAddon) this, 10597, 2, -3, 0, 0, -1, "Stable", 1);// 290
			AddComplexComponent( (BaseAddon) this, 10597, 3, -3, 0, 0, -1, "Stable", 1);// 291
			AddComplexComponent( (BaseAddon) this, 9977, 4, 1, 45, 0, -1, "Stable", 1);// 292
			AddComplexComponent( (BaseAddon) this, 146, 4, -5, 0, 0, -1, "Stable", 1);// 293
			AddComplexComponent( (BaseAddon) this, 5368, 1, 5, 32, 0, -1, "Stable", 1);// 295
			AddComplexComponent( (BaseAddon) this, 9993, 2, 3, 45, 0, -1, "Stable", 1);// 296
			AddComplexComponent( (BaseAddon) this, 10593, 6, -2, 20, 0, -1, "Stable", 1);// 297
			AddComplexComponent( (BaseAddon) this, 10592, 2, 0, 20, 0, -1, "Stable", 1);// 298
			AddComplexComponent( (BaseAddon) this, 9993, 1, 4, 42, 0, -1, "Stable", 1);// 300
			AddComplexComponent( (BaseAddon) this, 10592, 1, 6, 20, 0, -1, "Stable", 1);// 301
			AddComplexComponent( (BaseAddon) this, 2186, 6, -4, 20, 0, -1, "Stable", 1);// 302
			AddComplexComponent( (BaseAddon) this, 9988, 4, 3, 45, 0, -1, "Stable", 1);// 303
			AddComplexComponent( (BaseAddon) this, 9993, 4, 4, 42, 0, -1, "Stable", 1);// 304
			AddComplexComponent( (BaseAddon) this, 10592, 3, -4, 20, 0, -1, "Stable", 1);// 305
			AddComplexComponent( (BaseAddon) this, 3892, 1, 6, 8, 0, -1, "Stable", 1);// 307
			AddComplexComponent( (BaseAddon) this, 9994, 1, -1, 51, 0, -1, "Stable", 1);// 309
			AddComplexComponent( (BaseAddon) this, 10592, 0, 4, 20, 0, -1, "Stable", 1);// 310
			AddComplexComponent( (BaseAddon) this, 10593, 5, -1, 20, 0, -1, "Stable", 1);// 311
			AddComplexComponent( (BaseAddon) this, 153, 4, -1, 0, 0, 1, "Stable", 1);// 312
			AddComplexComponent( (BaseAddon) this, 10593, 5, -3, 20, 0, -1, "Stable", 1);// 313
			AddComplexComponent( (BaseAddon) this, 9991, 3, -2, 48, 0, -1, "Stable", 1);// 314
			AddComplexComponent( (BaseAddon) this, 2147, 6, -1, 0, 0, -1, "Stable", 1);// 315
			AddComplexComponent( (BaseAddon) this, 9993, 0, 4, 42, 0, -1, "Stable", 1);// 316
			AddComplexComponent( (BaseAddon) this, 9977, 4, 2, 45, 0, -1, "Stable", 1);// 317
			AddComplexComponent( (BaseAddon) this, 2148, 2, 4, 20, 0, -1, "Stable", 1);// 318
			AddComplexComponent( (BaseAddon) this, 10597, 3, -4, 0, 0, -1, "Stable", 1);// 319
			AddComplexComponent( (BaseAddon) this, 2148, 2, 5, 20, 0, -1, "Stable", 1);// 320
			AddComplexComponent( (BaseAddon) this, 9994, 0, -4, 42, 0, -1, "Stable", 1);// 321
			AddComplexComponent( (BaseAddon) this, 9977, 4, 0, 45, 0, -1, "Stable", 1);// 322
			AddComplexComponent( (BaseAddon) this, 9977, 4, -1, 45, 0, -1, "Stable", 1);// 323
			AddComplexComponent( (BaseAddon) this, 2883, 0, 1, 0, 0, -1, "Stable", 1);// 324
			AddComplexComponent( (BaseAddon) this, 9977, 5, 1, 42, 0, -1, "Stable", 1);// 325
			AddComplexComponent( (BaseAddon) this, 10592, 3, -3, 20, 0, -1, "Stable", 1);// 326
			AddComplexComponent( (BaseAddon) this, 9994, 1, -4, 42, 0, -1, "Stable", 1);// 327
			AddComplexComponent( (BaseAddon) this, 145, 4, 2, 0, 0, -1, "Stable", 1);// 328
			AddComplexComponent( (BaseAddon) this, 10593, 5, 1, 20, 0, -1, "Stable", 1);// 329
			AddComplexComponent( (BaseAddon) this, 2147, 5, -4, 0, 0, -1, "Stable", 1);// 330
			AddComplexComponent( (BaseAddon) this, 9977, 5, 0, 42, 0, -1, "Stable", 1);// 331
			AddComplexComponent( (BaseAddon) this, 9977, 5, -1, 42, 0, -1, "Stable", 1);// 332
			AddComplexComponent( (BaseAddon) this, 9977, 5, -2, 42, 0, -1, "Stable", 1);// 333
			AddComplexComponent( (BaseAddon) this, 9978, 0, 0, 51, 0, -1, "Stable", 1);// 334
			AddComplexComponent( (BaseAddon) this, 10592, 3, -2, 20, 0, -1, "Stable", 1);// 335
			AddComplexComponent( (BaseAddon) this, 10597, 3, 2, 0, 0, -1, "Stable", 1);// 336
			AddComplexComponent( (BaseAddon) this, 10592, 3, -1, 20, 0, -1, "Stable", 1);// 337
			AddComplexComponent( (BaseAddon) this, 10593, 1, 4, 20, 0, -1, "Stable", 1);// 338
			AddComplexComponent( (BaseAddon) this, 10597, 4, -4, 0, 0, -1, "Stable", 1);// 339
			AddComplexComponent( (BaseAddon) this, 10592, 0, 2, 20, 0, -1, "Stable", 1);// 341
			AddComplexComponent( (BaseAddon) this, 2148, 6, -3, 0, 0, -1, "Stable", 1);// 342
			AddComplexComponent( (BaseAddon) this, 2147, 6, -4, 0, 0, -1, "Stable", 1);// 343
			AddComplexComponent( (BaseAddon) this, 146, 3, -5, 0, 0, -1, "Stable", 1);// 344
			AddComplexComponent( (BaseAddon) this, 2186, 5, 1, 20, 0, -1, "Stable", 1);// 345
			AddComplexComponent( (BaseAddon) this, 10592, 1, 0, 20, 0, -1, "Stable", 1);// 346
			AddComplexComponent( (BaseAddon) this, 2147, 5, -2, 0, 0, -1, "Stable", 1);// 347
			AddComplexComponent( (BaseAddon) this, 10597, 1, 3, 0, 0, -1, "Stable", 1);// 348
			AddComplexComponent( (BaseAddon) this, 10593, 0, 3, 20, 0, -1, "Stable", 1);// 349
			AddComplexComponent( (BaseAddon) this, 10593, 4, -2, 20, 0, -1, "Stable", 1);// 350
			AddComplexComponent( (BaseAddon) this, 10592, 1, 3, 20, 0, -1, "Stable", 1);// 351
			AddComplexComponent( (BaseAddon) this, 10592, 2, -4, 20, 0, -1, "Stable", 1);// 352
			AddComplexComponent( (BaseAddon) this, 2147, 5, -1, 0, 0, -1, "Stable", 1);// 353
			AddComplexComponent( (BaseAddon) this, 10593, 6, -1, 20, 0, -1, "Stable", 1);// 354
			AddComplexComponent( (BaseAddon) this, 10592, 3, 0, 20, 0, -1, "Stable", 1);// 355
			AddComplexComponent( (BaseAddon) this, 2186, 6, 1, 20, 0, -1, "Stable", 1);// 356
			AddComplexComponent( (BaseAddon) this, 10593, 4, -3, 20, 0, -1, "Stable", 1);// 357
			AddComplexComponent( (BaseAddon) this, 2146, 6, 1, 0, 0, -1, "Stable", 1);// 358
			AddComplexComponent( (BaseAddon) this, 14238, 0, 5, 9, 1045, -1, "Stable", 1);// 359
			AddComplexComponent( (BaseAddon) this, 9994, 2, -3, 45, 0, -1, "Stable", 1);// 360
			AddComplexComponent( (BaseAddon) this, 9991, 5, -4, 42, 0, -1, "Stable", 1);// 361
			AddComplexComponent( (BaseAddon) this, 2148, 6, 0, 4, 0, -1, "Stable", 1);// 362
			AddComplexComponent( (BaseAddon) this, 9988, 2, 1, 51, 0, -1, "Stable", 1);// 363
			AddComplexComponent( (BaseAddon) this, 9993, 1, 1, 51, 0, -1, "Stable", 1);// 364
			AddComplexComponent( (BaseAddon) this, 9993, 2, 2, 48, 0, -1, "Stable", 1);// 365
			AddComplexComponent( (BaseAddon) this, 14238, 0, 5, 13, 1045, -1, "Stable", 1);// 366
			AddComplexComponent( (BaseAddon) this, 14238, 0, 5, 17, 1045, -1, "Stable", 1);// 367
			AddComplexComponent( (BaseAddon) this, 10593, 6, 1, 20, 0, -1, "Stable", 1);// 368
			AddComplexComponent( (BaseAddon) this, 10597, 0, -3, 0, 0, -1, "Stable", 1);// 369
			AddComplexComponent( (BaseAddon) this, 4150, 6, 0, 20, 0, -1, "Stable", 1);// 370
			AddComplexComponent( (BaseAddon) this, 9993, 0, 3, 45, 0, -1, "Stable", 1);// 371
			AddComplexComponent( (BaseAddon) this, 14238, 0, 5, 29, 1045, -1, "Stable", 1);// 372
			AddComplexComponent( (BaseAddon) this, 9994, 3, -3, 45, 0, -1, "Stable", 1);// 373
			AddComplexComponent( (BaseAddon) this, 10597, 0, 2, 0, 0, -1, "Stable", 1);// 374
			AddComplexComponent( (BaseAddon) this, 147, 4, 2, 20, 0, -1, "Stable", 1);// 375
			AddComplexComponent( (BaseAddon) this, 10597, 2, 0, 0, 0, -1, "Stable", 1);// 376
			AddComplexComponent( (BaseAddon) this, 152, 2, -5, 20, 0, 0, "Stable", 1);// 377
			AddComplexComponent( (BaseAddon) this, 3894, 0, -3, 0, 0, -1, "Stable", 1);// 378
			AddComplexComponent( (BaseAddon) this, 10592, 0, -1, 20, 0, -1, "Stable", 1);// 380
			AddComplexComponent( (BaseAddon) this, 10592, 1, -1, 20, 0, -1, "Stable", 1);// 381
			AddComplexComponent( (BaseAddon) this, 10592, 3, 2, 20, 0, -1, "Stable", 1);// 382
			AddComplexComponent( (BaseAddon) this, 10075, 0, 3, 20, 1037, -1, "Stable", 1);// 383
			AddComplexComponent( (BaseAddon) this, 10592, 1, 3, 20, 0, -1, "Stable", 1);// 384
			AddComplexComponent( (BaseAddon) this, 10592, 1, 4, 20, 0, -1, "Stable", 1);// 385
			AddComplexComponent( (BaseAddon) this, 10592, 2, -2, 20, 0, -1, "Stable", 1);// 386
			AddComplexComponent( (BaseAddon) this, 10597, 0, 0, 0, 0, -1, "Stable", 1);// 387
			AddComplexComponent( (BaseAddon) this, 14238, 0, 5, 27, 1045, -1, "Stable", 1);// 388
			AddComplexComponent( (BaseAddon) this, 2186, 5, -4, 20, 0, -1, "Stable", 1);// 389
			AddComplexComponent( (BaseAddon) this, 10597, 0, 3, 0, 0, -1, "Stable", 1);// 390
			AddComplexComponent( (BaseAddon) this, 10592, 4, 3, 20, 0, -1, "Stable", 1);// 391
			AddComplexComponent( (BaseAddon) this, 10597, 2, 2, 0, 0, -1, "Stable", 1);// 392
			AddComplexComponent( (BaseAddon) this, 10597, 1, 1, 0, 0, -1, "Stable", 1);// 393
			AddComplexComponent( (BaseAddon) this, 9983, 1, 0, 51, 0, -1, "Stable", 1);// 394
			AddComplexComponent( (BaseAddon) this, 10593, 0, 4, 20, 0, -1, "Stable", 1);// 395
			AddComplexComponent( (BaseAddon) this, 10597, 1, -4, 0, 0, -1, "Stable", 1);// 396
			AddComplexComponent( (BaseAddon) this, 10593, 6, -1, 20, 0, -1, "Stable", 1);// 397
			AddComplexComponent( (BaseAddon) this, 10592, 1, 2, 20, 0, -1, "Stable", 1);// 398
			AddComplexComponent( (BaseAddon) this, 10592, 1, 1, 20, 0, -1, "Stable", 1);// 399
			AddComplexComponent( (BaseAddon) this, 10593, 4, 2, 20, 0, -1, "Stable", 1);// 400
			AddComplexComponent( (BaseAddon) this, 2146, 6, -2, 0, 0, -1, "Stable", 1);// 401
			AddComplexComponent( (BaseAddon) this, 10593, 6, 0, 20, 0, -1, "Stable", 1);// 403
			AddComplexComponent( (BaseAddon) this, 2147, 5, 1, 0, 0, -1, "Stable", 1);// 404
			AddComplexComponent( (BaseAddon) this, 152, 2, 3, 0, 0, 1, "Stable", 1);// 405
			AddComplexComponent( (BaseAddon) this, 10592, 2, -1, 20, 0, -1, "Stable", 1);// 406
			AddComplexComponent( (BaseAddon) this, 10593, 6, 0, 20, 0, -1, "Stable", 1);// 407
			AddComplexComponent( (BaseAddon) this, 10593, 5, 0, 20, 0, -1, "Stable", 1);// 408
			AddComplexComponent( (BaseAddon) this, 152, 3, 3, 0, 0, 1, "Stable", 1);// 409
			AddComplexComponent( (BaseAddon) this, 10597, 0, -1, 0, 0, -1, "Stable", 1);// 410
			AddComplexComponent( (BaseAddon) this, 9988, 3, 2, 48, 0, -1, "Stable", 1);// 411
			AddComplexComponent( (BaseAddon) this, 2884, 1, 1, 0, 0, -1, "Stable", 1);// 412
			AddComplexComponent( (BaseAddon) this, 147, 4, 3, 20, 0, -1, "Stable", 1);// 413
			AddComplexComponent( (BaseAddon) this, 10593, 6, -3, 20, 0, -1, "Stable", 1);// 414
			AddComplexComponent( (BaseAddon) this, 10597, 0, -2, 0, 0, -1, "Stable", 1);// 415
			AddComplexComponent( (BaseAddon) this, 9977, 5, 2, 42, 0, -1, "Stable", 1);// 416
			AddComplexComponent( (BaseAddon) this, 147, 2, 6, 0, 0, -1, "Stable", 1);// 417
			AddComplexComponent( (BaseAddon) this, 10597, 1, -3, 0, 0, -1, "Stable", 1);// 418
			AddComplexComponent( (BaseAddon) this, 10592, 2, 1, 20, 0, -1, "Stable", 1);// 420
			AddComplexComponent( (BaseAddon) this, 10592, 3, 3, 20, 0, -1, "Stable", 1);// 422
			AddComplexComponent( (BaseAddon) this, 10593, 4, 0, 20, 0, -1, "Stable", 1);// 423
			AddComplexComponent( (BaseAddon) this, 146, 4, 3, 20, 0, -1, "Stable", 1);// 424
			AddComplexComponent( (BaseAddon) this, 10592, 2, -2, 20, 0, -1, "Stable", 1);// 425
			AddComplexComponent( (BaseAddon) this, 10592, 1, -2, 20, 0, -1, "Stable", 1);// 426
			AddComplexComponent( (BaseAddon) this, 10592, 0, -2, 20, 0, -1, "Stable", 1);// 427
			AddComplexComponent( (BaseAddon) this, 10592, 0, -2, 20, 0, -1, "Stable", 1);// 428
			AddComplexComponent( (BaseAddon) this, 9994, 0, -2, 48, 0, -1, "Stable", 1);// 429
			AddComplexComponent( (BaseAddon) this, 10592, 4, 1, 20, 0, -1, "Stable", 1);// 430
			AddComplexComponent( (BaseAddon) this, 9994, 2, -2, 48, 0, -1, "Stable", 1);// 431
			AddComplexComponent( (BaseAddon) this, 10592, 2, -3, 20, 0, -1, "Stable", 1);// 432
			AddComplexComponent( (BaseAddon) this, 10592, 4, 0, 20, 0, -1, "Stable", 1);// 433
			AddComplexComponent( (BaseAddon) this, 10592, 0, 3, 20, 0, -1, "Stable", 1);// 434
			AddComplexComponent( (BaseAddon) this, 10592, 1, 4, 20, 0, -1, "Stable", 1);// 435
			AddComplexComponent( (BaseAddon) this, 10597, 1, -2, 0, 0, -1, "Stable", 1);// 436
			AddComplexComponent( (BaseAddon) this, 10592, 0, 6, 20, 0, -1, "Stable", 1);// 437
			AddComplexComponent( (BaseAddon) this, 10592, 0, 1, 20, 0, -1, "Stable", 1);// 438
			AddComplexComponent( (BaseAddon) this, 2147, 1, 6, 20, 0, -1, "Stable", 1);// 439
			AddComplexComponent( (BaseAddon) this, 147, 4, -5, 20, 0, -1, "Stable", 1);// 440
			AddComplexComponent( (BaseAddon) this, 3892, 1, 6, 6, 0, -1, "Stable", 1);// 441
			AddComplexComponent( (BaseAddon) this, 10592, 4, -2, 20, 0, -1, "Stable", 1);// 442
			AddComplexComponent( (BaseAddon) this, 9977, 5, 3, 42, 0, -1, "Stable", 1);// 443
			AddComplexComponent( (BaseAddon) this, 9993, 0, 2, 48, 0, -1, "Stable", 1);// 444
			AddComplexComponent( (BaseAddon) this, 9993, 1, 2, 48, 0, -1, "Stable", 1);// 445
			AddComplexComponent( (BaseAddon) this, 4150, 4, 0, 20, 0, -1, "Stable", 1);// 446
			AddComplexComponent( (BaseAddon) this, 10592, 0, 3, 20, 0, -1, "Stable", 1);// 447
			AddComplexComponent( (BaseAddon) this, 3892, 1, 6, 8, 0, -1, "Stable", 1);// 448
			AddComplexComponent( (BaseAddon) this, 9994, 4, -4, 42, 0, -1, "Stable", 1);// 449
			AddComplexComponent( (BaseAddon) this, 2147, 2, 6, 20, 0, -1, "Stable", 1);// 450
			AddComplexComponent( (BaseAddon) this, 9994, 3, -4, 42, 0, -1, "Stable", 1);// 451
			AddComplexComponent( (BaseAddon) this, 893, 1, 5, 25, 1037, -1, "Stable", 1);// 452
			AddComplexComponent( (BaseAddon) this, 10593, 5, -2, 20, 0, -1, "Stable", 1);// 453
			AddComplexComponent( (BaseAddon) this, 10597, 0, 1, 0, 0, -1, "Stable", 1);// 454
			AddComplexComponent( (BaseAddon) this, 9994, 2, -4, 42, 0, -1, "Stable", 1);// 455
			AddComplexComponent( (BaseAddon) this, 9988, 5, 4, 42, 0, -1, "Stable", 1);// 456
			AddComplexComponent( (BaseAddon) this, 7841, 2, 6, 45, 0, -1, "Stable", 1);// 457
			AddComplexComponent( (BaseAddon) this, 9977, 5, -3, 42, 0, -1, "Stable", 1);// 458
			AddComplexComponent( (BaseAddon) this, 10075, 0, 3, 24, 1037, -1, "Stable", 1);// 459
			AddComplexComponent( (BaseAddon) this, 10593, 6, 1, 20, 0, -1, "Stable", 1);// 460
			AddComplexComponent( (BaseAddon) this, 9991, 2, -1, 51, 0, -1, "Stable", 1);// 461
			AddComplexComponent( (BaseAddon) this, 3892, 5, -3, 0, 0, -1, "Stable", 1);// 462
			AddComplexComponent( (BaseAddon) this, 3893, 2, -1, 0, 0, -1, "Stable", 1);// 463
			AddComplexComponent( (BaseAddon) this, 3893, 5, 0, 0, 0, -1, "Stable", 1);// 464
			AddComplexComponent( (BaseAddon) this, 3893, 2, -4, 0, 0, -1, "Stable", 1);// 465
			AddComplexComponent( (BaseAddon) this, 3893, 0, -1, 0, 0, -1, "Stable", 1);// 466
			AddComplexComponent( (BaseAddon) this, 2881, 2, -4, 20, 0, -1, "Stable", 1);// 467
			AddComplexComponent( (BaseAddon) this, 2882, 2, -3, 20, 0, -1, "Stable", 1);// 468
			AddComplexComponent( (BaseAddon) this, 2176, 1, -3, 20, 0, -1, "Stable", 1);// 469
			AddComplexComponent( (BaseAddon) this, 2177, 0, -2, 20, 0, -1, "Stable", 1);// 470
			AddComplexComponent( (BaseAddon) this, 3899, 3, -1, 0, 0, -1, "Stable", 1);// 471
			AddComplexComponent( (BaseAddon) this, 3900, 5, -3, 0, 0, -1, "Stable", 1);// 472
			AddComplexComponent( (BaseAddon) this, 146, 1, -5, 0, 0, -1, "Stable", 1);// 473
			AddComplexComponent( (BaseAddon) this, 4022, 4, 6, 0, 0, -1, "Stable", 1);// 474
			AddComplexComponent( (BaseAddon) this, 4022, 1, 0, 0, 0, -1, "Stable", 1);// 475
			AddComplexComponent( (BaseAddon) this, 4020, 5, 3, 6, 2955, -1, "Stable", 1);// 476
			AddComplexComponent( (BaseAddon) this, 7160, 5, 2, 6, 0, -1, "Stable", 1);// 477
			AddComplexComponent( (BaseAddon) this, 2923, 5, 3, 0, 0, -1, "Stable", 1);// 478
			AddComplexComponent( (BaseAddon) this, 2924, 5, 2, 0, 0, -1, "Stable", 1);// 479
			AddComplexComponent( (BaseAddon) this, 4022, 6, 3, 14, 0, -1, "Stable", 1);// 480
			AddComplexComponent( (BaseAddon) this, 4022, 5, 5, 0, 0, -1, "Stable", 1);// 481
			AddComplexComponent( (BaseAddon) this, 10075, 1, 0, 64, 1281, -1, "Stable", 1);// 482
			AddComplexComponent( (BaseAddon) this, 10592, 0, -1, 20, 0, -1, "Stable", 1);// 483
			AddComplexComponent( (BaseAddon) this, 10592, 0, 0, 20, 0, -1, "Stable", 1);// 484
			AddComplexComponent( (BaseAddon) this, 10592, 0, 1, 20, 0, -1, "Stable", 1);// 485
			AddComplexComponent( (BaseAddon) this, 10592, 0, 2, 20, 0, -1, "Stable", 1);// 486
			AddComplexComponent( (BaseAddon) this, 10592, 1, -1, 20, 0, -1, "Stable", 1);// 487
			AddComplexComponent( (BaseAddon) this, 10592, 1, 0, 20, 0, -1, "Stable", 1);// 488
			AddComplexComponent( (BaseAddon) this, 10592, 1, 1, 20, 0, -1, "Stable", 1);// 489
			AddComplexComponent( (BaseAddon) this, 10592, 1, 2, 20, 0, -1, "Stable", 1);// 490
			AddComplexComponent( (BaseAddon) this, 10592, 2, -1, 20, 0, -1, "Stable", 1);// 491
			AddComplexComponent( (BaseAddon) this, 10592, 2, 0, 20, 0, -1, "Stable", 1);// 492
			AddComplexComponent( (BaseAddon) this, 10592, 2, 1, 20, 0, -1, "Stable", 1);// 493
			AddComplexComponent( (BaseAddon) this, 10592, 2, 2, 20, 0, -1, "Stable", 1);// 494
			AddComplexComponent( (BaseAddon) this, 10592, 0, -1, 20, 0, -1, "Stable", 1);// 495
			AddComplexComponent( (BaseAddon) this, 10592, 0, 0, 20, 0, -1, "Stable", 1);// 496
			AddComplexComponent( (BaseAddon) this, 10592, 0, 1, 20, 0, -1, "Stable", 1);// 497

		}

		public StableAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class StableAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new StableAddon();
			}
		}

		[Constructable]
		public StableAddonDeed()
		{
			Name = "Stable";
		}

		public StableAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}