
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SteamRoomAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SteamRoomAddonDeed();
			}
		}

		[ Constructable ]
		public SteamRoomAddon()
		{



			AddComplexComponent( (BaseAddon) this, 11192, -3, -2, 1, 0, -1, "steamroom", 1);// 1
			AddComplexComponent( (BaseAddon) this, 11192, -3, -1, 1, 0, -1, "steamroom", 1);// 2
			AddComplexComponent( (BaseAddon) this, 11192, -2, -2, 1, 0, -1, "steamroom", 1);// 3
			AddComplexComponent( (BaseAddon) this, 11192, -2, -1, 1, 0, -1, "steamroom", 1);// 4
			AddComplexComponent( (BaseAddon) this, 11192, -1, -2, 1, 0, -1, "steamroom", 1);// 5
			AddComplexComponent( (BaseAddon) this, 11192, -1, -1, 1, 0, -1, "steamroom", 1);// 6
			AddComplexComponent( (BaseAddon) this, 11192, 0, -2, 1, 0, -1, "steamroom", 1);// 7
			AddComplexComponent( (BaseAddon) this, 11192, 0, -1, 1, 0, -1, "steamroom", 1);// 8
			AddComplexComponent( (BaseAddon) this, 11192, 1, -2, 1, 0, -1, "steamroom", 1);// 9
			AddComplexComponent( (BaseAddon) this, 11192, 1, -1, 1, 0, -1, "steamroom", 1);// 10
			AddComplexComponent( (BaseAddon) this, 11192, 2, -2, 1, 0, -1, "steamroom", 1);// 11
			AddComplexComponent( (BaseAddon) this, 11192, 2, -1, 1, 0, -1, "steamroom", 1);// 12
			AddComplexComponent( (BaseAddon) this, 11192, 3, -2, 1, 0, -1, "steamroom", 1);// 13
			AddComplexComponent( (BaseAddon) this, 11192, 3, -1, 1, 0, -1, "steamroom", 1);// 14
			AddComplexComponent( (BaseAddon) this, 11192, 4, -2, 1, 0, -1, "steamroom", 1);// 15
			AddComplexComponent( (BaseAddon) this, 11192, 4, -1, 1, 0, -1, "steamroom", 1);// 16
			AddComplexComponent( (BaseAddon) this, 10387, -3, -3, 1, 0, -1, "steamroom", 1);// 17
			AddComplexComponent( (BaseAddon) this, 10387, -2, -3, 1, 0, -1, "steamroom", 1);// 18
			AddComplexComponent( (BaseAddon) this, 10387, -1, -3, 1, 0, -1, "steamroom", 1);// 19
			AddComplexComponent( (BaseAddon) this, 10387, 0, -3, 1, 0, -1, "steamroom", 1);// 20
			AddComplexComponent( (BaseAddon) this, 10387, 1, -3, 1, 0, -1, "steamroom", 1);// 21
			AddComplexComponent( (BaseAddon) this, 10387, 2, -3, 1, 0, -1, "steamroom", 1);// 22
			AddComplexComponent( (BaseAddon) this, 10387, 3, -3, 1, 0, -1, "steamroom", 1);// 23
			AddComplexComponent( (BaseAddon) this, 10387, 4, -3, 1, 0, -1, "steamroom", 1);// 24
			AddComplexComponent( (BaseAddon) this, 10384, -4, -2, 1, 0, -1, "steamroom", 1);// 25
			AddComplexComponent( (BaseAddon) this, 10384, -4, -1, 1, 0, -1, "steamroom", 1);// 26
			AddComplexComponent( (BaseAddon) this, 10384, 4, -2, 0, 0, -1, "steamroom", 1);// 27
			AddComplexComponent( (BaseAddon) this, 10384, 4, -1, 0, 0, -1, "steamroom", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2920, 2, -2, 1, 1509, -1, "steamroom", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2922, -1, -2, 1, 1509, -1, "steamroom", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2922, 0, -2, 1, 1509, -1, "steamroom", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2922, 1, -2, 1, 1509, -1, "steamroom", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2921, -2, -2, 1, 1509, -1, "steamroom", 1);// 33
			AddComplexComponent( (BaseAddon) this, 14213, 0, -2, 2, 1150, -1, "steamroom", 1);// 34
			AddComplexComponent( (BaseAddon) this, 4436, -4, -1, 21, 1150, -1, "steamroom", 1);// 35
			AddComplexComponent( (BaseAddon) this, 4436, 1, -2, 2, 1150, -1, "steamroom", 1);// 36
			AddComplexComponent( (BaseAddon) this, 11192, -3, 0, 1, 0, -1, "steamroom", 1);// 37
			AddComplexComponent( (BaseAddon) this, 11192, -3, 1, 1, 0, -1, "steamroom", 1);// 38
			AddComplexComponent( (BaseAddon) this, 11192, -3, 2, 1, 0, -1, "steamroom", 1);// 39
			AddComplexComponent( (BaseAddon) this, 11192, -3, 3, 1, 0, -1, "steamroom", 1);// 40
			AddComplexComponent( (BaseAddon) this, 11192, -2, 0, 1, 0, -1, "steamroom", 1);// 41
			AddComplexComponent( (BaseAddon) this, 11192, -2, 1, 1, 0, -1, "steamroom", 1);// 42
			AddComplexComponent( (BaseAddon) this, 11192, -2, 2, 1, 0, -1, "steamroom", 1);// 43
			AddComplexComponent( (BaseAddon) this, 11192, -2, 3, 1, 0, -1, "steamroom", 1);// 44
			AddComplexComponent( (BaseAddon) this, 11192, -1, 0, 1, 0, -1, "steamroom", 1);// 45
			AddComplexComponent( (BaseAddon) this, 11192, -1, 1, 1, 0, -1, "steamroom", 1);// 46
			AddComplexComponent( (BaseAddon) this, 11192, -1, 2, 1, 0, -1, "steamroom", 1);// 47
			AddComplexComponent( (BaseAddon) this, 11192, -1, 3, 1, 0, -1, "steamroom", 1);// 48
			AddComplexComponent( (BaseAddon) this, 11192, 0, 0, 1, 0, -1, "steamroom", 1);// 49
			AddComplexComponent( (BaseAddon) this, 11192, 0, 1, 1, 0, -1, "steamroom", 1);// 50
			AddComplexComponent( (BaseAddon) this, 11192, 0, 2, 1, 0, -1, "steamroom", 1);// 51
			AddComplexComponent( (BaseAddon) this, 11192, 0, 3, 1, 0, -1, "steamroom", 1);// 52
			AddComplexComponent( (BaseAddon) this, 11192, 1, 0, 1, 0, -1, "steamroom", 1);// 53
			AddComplexComponent( (BaseAddon) this, 11192, 1, 1, 1, 0, -1, "steamroom", 1);// 54
			AddComplexComponent( (BaseAddon) this, 11192, 1, 2, 1, 0, -1, "steamroom", 1);// 55
			AddComplexComponent( (BaseAddon) this, 11192, 1, 3, 1, 0, -1, "steamroom", 1);// 56
			AddComplexComponent( (BaseAddon) this, 11192, 2, 0, 1, 0, -1, "steamroom", 1);// 57
			AddComplexComponent( (BaseAddon) this, 11192, 2, 1, 1, 0, -1, "steamroom", 1);// 58
			AddComplexComponent( (BaseAddon) this, 11192, 2, 2, 1, 0, -1, "steamroom", 1);// 59
			AddComplexComponent( (BaseAddon) this, 11192, 2, 3, 1, 0, -1, "steamroom", 1);// 60
			AddComplexComponent( (BaseAddon) this, 11192, 3, 0, 1, 0, -1, "steamroom", 1);// 61
			AddComplexComponent( (BaseAddon) this, 11192, 3, 1, 1, 0, -1, "steamroom", 1);// 62
			AddComplexComponent( (BaseAddon) this, 11192, 3, 2, 1, 0, -1, "steamroom", 1);// 63
			AddComplexComponent( (BaseAddon) this, 11192, 3, 3, 1, 0, -1, "steamroom", 1);// 64
			AddComplexComponent( (BaseAddon) this, 11192, 4, 0, 1, 0, -1, "steamroom", 1);// 65
			AddComplexComponent( (BaseAddon) this, 11192, 4, 1, 1, 0, -1, "steamroom", 1);// 66
			AddComplexComponent( (BaseAddon) this, 11192, 4, 2, 1, 0, -1, "steamroom", 1);// 67
			AddComplexComponent( (BaseAddon) this, 11192, 4, 3, 1, 0, -1, "steamroom", 1);// 68
			AddComplexComponent( (BaseAddon) this, 10384, -4, 0, 1, 0, -1, "steamroom", 1);// 69
			AddComplexComponent( (BaseAddon) this, 10384, -4, 1, 1, 0, -1, "steamroom", 1);// 70
			AddComplexComponent( (BaseAddon) this, 10384, -4, 2, 1, 0, -1, "steamroom", 1);// 71
			AddComplexComponent( (BaseAddon) this, 10384, -4, 3, 1, 0, -1, "steamroom", 1);// 72
			AddComplexComponent( (BaseAddon) this, 10387, -3, 3, 1, 0, -1, "steamroom", 1);// 73
			AddComplexComponent( (BaseAddon) this, 10387, -2, 3, 1, 0, -1, "steamroom", 1);// 74
			AddComplexComponent( (BaseAddon) this, 10387, -1, 3, 1, 0, -1, "steamroom", 1);// 75
			AddComplexComponent( (BaseAddon) this, 10387, 0, 3, 1, 0, -1, "steamroom", 1);// 76
			AddComplexComponent( (BaseAddon) this, 10387, 1, 3, 1, 0, -1, "steamroom", 1);// 77
			AddComplexComponent( (BaseAddon) this, 10387, 2, 3, 1, 0, -1, "steamroom", 1);// 78
			AddComplexComponent( (BaseAddon) this, 10387, 3, 3, 1, 0, -1, "steamroom", 1);// 79
			AddComplexComponent( (BaseAddon) this, 10387, 4, 3, 1, 0, -1, "steamroom", 1);// 80
			AddComplexComponent( (BaseAddon) this, 10384, 4, 3, 0, 0, -1, "steamroom", 1);// 81
			AddComplexComponent( (BaseAddon) this, 10384, 4, 2, 0, 0, -1, "steamroom", 1);// 82
			AddComplexComponent( (BaseAddon) this, 2921, -2, 1, 1, 1509, -1, "steamroom", 1);// 83
			AddComplexComponent( (BaseAddon) this, 2922, -1, 1, 1, 1509, -1, "steamroom", 1);// 84
			AddComplexComponent( (BaseAddon) this, 2922, 0, 1, 1, 1509, -1, "steamroom", 1);// 85
			AddComplexComponent( (BaseAddon) this, 2922, 1, 1, 1, 1509, -1, "steamroom", 1);// 86
			AddComplexComponent( (BaseAddon) this, 2920, 2, 1, 1, 1509, -1, "steamroom", 1);// 87
			AddComplexComponent( (BaseAddon) this, 14120, -3, 0, 1, 0, -1, "steamroom", 1);// 88
			AddComplexComponent( (BaseAddon) this, 14213, 2, 1, 5, 1150, -1, "steamroom", 1);// 89
			AddComplexComponent( (BaseAddon) this, 14213, -1, 1, 2, 1150, -1, "steamroom", 1);// 90
			AddComplexComponent( (BaseAddon) this, 4435, 2, 0, 1, 1150, -1, "steamroom", 1);// 91
			AddComplexComponent( (BaseAddon) this, 4435, 0, 1, 2, 1150, -1, "steamroom", 1);// 92
			AddComplexComponent( (BaseAddon) this, 4436, 4, 2, 20, 1150, -1, "steamroom", 1);// 93
			AddComplexComponent( (BaseAddon) this, 4436, 0, 1, 2, 1150, -1, "steamroom", 1);// 94

		}

		public SteamRoomAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SteamRoomAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SteamRoomAddon();
			}
		}

		[Constructable]
		public SteamRoomAddonDeed()
		{
			Name = "SteamRoom";
		}

		public SteamRoomAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}