
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class VineBedAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new VineBedAddonDeed();
			}
		}

		[ Constructable ]
		public VineBedAddon()
		{



			AddComplexComponent( (BaseAddon) this, 3166, -2, -1, 6, 0, -1, "VineBed", 1);// 1
			AddComplexComponent( (BaseAddon) this, 9375, -4, -1, 16, 2263, -1, "VineBed", 1);// 2
			AddComplexComponent( (BaseAddon) this, 9375, -4, -2, 16, 2263, -1, "VineBed", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2749, 0, 0, 6, 2094, -1, "VineBed", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7950, -4, -1, 0, 0, -1, "VineBed", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7954, -2, -4, 0, 0, -1, "VineBed", 1);// 6
			AddComplexComponent( (BaseAddon) this, 9375, -4, 2, 16, 2263, -1, "VineBed", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6817, -3, 5, 0, 0, -1, "VineBed", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6817, -3, -4, 0, 0, -1, "VineBed", 1);// 9
			AddComplexComponent( (BaseAddon) this, 3310, -1, 5, 0, 2635, -1, "VineBed", 1);// 10
			AddComplexComponent( (BaseAddon) this, 5036, -1, 2, 12, 2820, -1, "VineBed", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3166, -2, 0, 6, 0, -1, "VineBed", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3311, -3, -4, 0, 2820, -1, "VineBed", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3166, -1, -3, 6, 0, -1, "VineBed", 1);// 14
			AddComplexComponent( (BaseAddon) this, 5032, -1, 1, 6, 2820, -1, "VineBed", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3167, 0, -5, 16, 0, -1, "VineBed", 1);// 16
			AddComplexComponent( (BaseAddon) this, 3166, 0, -1, 9, 0, -1, "VineBed", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3311, -3, 4, 0, 2820, -1, "VineBed", 1);// 18
			AddComplexComponent( (BaseAddon) this, 9375, -4, 1, 16, 2263, -1, "VineBed", 1);// 19
			AddComplexComponent( (BaseAddon) this, 5036, 0, 2, 12, 2820, -1, "VineBed", 1);// 20
			AddComplexComponent( (BaseAddon) this, 3167, -3, 4, 16, 0, -1, "VineBed", 1);// 21
			AddComplexComponent( (BaseAddon) this, 11196, -1, 2, 0, 2761, -1, "VineBed", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2749, 0, 2, 6, 2094, -1, "VineBed", 1);// 23
			AddComplexComponent( (BaseAddon) this, 5029, -2, 2, 6, 2581, -1, "VineBed", 1);// 24
			AddComplexComponent( (BaseAddon) this, 11504, 0, 2, 7, 2761, -1, "VineBed", 1);// 25
			AddComplexComponent( (BaseAddon) this, 3167, -1, 4, 16, 0, -1, "VineBed", 1);// 26
			AddComplexComponent( (BaseAddon) this, 9376, 0, -5, 16, 2263, -1, "VineBed", 1);// 27
			AddComplexComponent( (BaseAddon) this, 9376, -1, -5, 16, 2263, -1, "VineBed", 1);// 28
			AddComplexComponent( (BaseAddon) this, 9376, -2, -5, 16, 2263, -1, "VineBed", 1);// 29
			AddComplexComponent( (BaseAddon) this, 11504, -1, 2, 7, 2761, -1, "VineBed", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3168, 0, -3, 6, 0, -1, "VineBed", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3167, -2, 4, 16, 0, -1, "VineBed", 1);// 32
			AddComplexComponent( (BaseAddon) this, 3168, -4, 2, 16, 0, -1, "VineBed", 1);// 33
			AddComplexComponent( (BaseAddon) this, 3167, -4, -5, 16, 0, -1, "VineBed", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3167, -3, -5, 16, 0, -1, "VineBed", 1);// 35
			AddComplexComponent( (BaseAddon) this, 9375, -4, 0, 16, 2263, -1, "VineBed", 1);// 36
			AddComplexComponent( (BaseAddon) this, 10806, -4, -5, 0, 2263, -1, "VineBed", 1);// 37
			AddComplexComponent( (BaseAddon) this, 3310, -3, 5, 0, 2820, -1, "VineBed", 1);// 38
			AddComplexComponent( (BaseAddon) this, 3168, -4, 1, 16, 0, -1, "VineBed", 1);// 39
			AddComplexComponent( (BaseAddon) this, 10806, -4, 4, 0, 2263, -1, "VineBed", 1);// 40
			AddComplexComponent( (BaseAddon) this, 3168, -4, 0, 16, 0, -1, "VineBed", 1);// 41
			AddComplexComponent( (BaseAddon) this, 3168, -4, -1, 16, 0, -1, "VineBed", 1);// 42
			AddComplexComponent( (BaseAddon) this, 9375, -4, 4, 16, 2263, -1, "VineBed", 1);// 43
			AddComplexComponent( (BaseAddon) this, 3310, -2, 5, 0, 0, -1, "VineBed", 1);// 44
			AddComplexComponent( (BaseAddon) this, 2749, -1, -1, 6, 2094, -1, "VineBed", 1);// 45
			AddComplexComponent( (BaseAddon) this, 3168, -2, -3, 6, 0, -1, "VineBed", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2749, -1, 1, 6, 2094, -1, "VineBed", 1);// 47
			AddComplexComponent( (BaseAddon) this, 7954, -4, 0, 0, 0, -1, "VineBed", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2749, -1, -3, 6, 2094, -1, "VineBed", 1);// 49
			AddComplexComponent( (BaseAddon) this, 5035, 0, 1, 9, 2761, -1, "VineBed", 1);// 50
			AddComplexComponent( (BaseAddon) this, 3166, -1, 0, 9, 0, -1, "VineBed", 1);// 51
			AddComplexComponent( (BaseAddon) this, 5035, -1, 1, 9, 2761, -1, "VineBed", 1);// 52
			AddComplexComponent( (BaseAddon) this, 7951, -3, 0, 0, 0, -1, "VineBed", 1);// 53
			AddComplexComponent( (BaseAddon) this, 11504, -2, 2, 7, 2761, -1, "VineBed", 1);// 54
			AddComplexComponent( (BaseAddon) this, 3167, -4, 4, 16, 0, -1, "VineBed", 1);// 55
			AddComplexComponent( (BaseAddon) this, 3168, -4, -2, 16, 0, -1, "VineBed", 1);// 56
			AddComplexComponent( (BaseAddon) this, 3168, -4, -3, 16, 0, -1, "VineBed", 1);// 57
			AddComplexComponent( (BaseAddon) this, 3168, -4, 4, 16, 0, -1, "VineBed", 1);// 58
			AddComplexComponent( (BaseAddon) this, 7950, -3, -1, 0, 0, -1, "VineBed", 1);// 59
			AddComplexComponent( (BaseAddon) this, 3167, 0, 4, 16, 0, -1, "VineBed", 1);// 60
			AddComplexComponent( (BaseAddon) this, 3168, -4, -4, 16, 0, -1, "VineBed", 1);// 61
			AddComplexComponent( (BaseAddon) this, 3167, -1, -5, 16, 0, -1, "VineBed", 1);// 62
			AddComplexComponent( (BaseAddon) this, 3380, -3, -2, 0, 0, -1, "VineBed", 1);// 63
			AddComplexComponent( (BaseAddon) this, 3166, -1, -2, 9, 0, -1, "VineBed", 1);// 64
			AddComplexComponent( (BaseAddon) this, 2749, 0, 1, 6, 2094, -1, "VineBed", 1);// 65
			AddComplexComponent( (BaseAddon) this, 2749, -2, 2, 6, 2094, -1, "VineBed", 1);// 66
			AddComplexComponent( (BaseAddon) this, 3168, -4, -5, 16, 0, -1, "VineBed", 1);// 67
			AddComplexComponent( (BaseAddon) this, 11196, 0, 2, 0, 2761, -1, "VineBed", 1);// 68
			AddComplexComponent( (BaseAddon) this, 7954, -5, -1, 0, 0, -1, "VineBed", 1);// 69
			AddComplexComponent( (BaseAddon) this, 7954, -3, 1, 0, 0, -1, "VineBed", 1);// 70
			AddComplexComponent( (BaseAddon) this, 5691, 0, 2, 9, 2071, -1, "VineBed", 1);// 71
			AddComplexComponent( (BaseAddon) this, 5691, -1, 2, 9, 2071, -1, "VineBed", 1);// 72
			AddComplexComponent( (BaseAddon) this, 5691, -2, 2, 9, 2071, -1, "VineBed", 1);// 73
			AddComplexComponent( (BaseAddon) this, 5690, -2, 2, 6, 2827, -1, "VineBed", 1);// 74
			AddComplexComponent( (BaseAddon) this, 5690, -1, 2, 6, 2827, -1, "VineBed", 1);// 75
			AddComplexComponent( (BaseAddon) this, 5690, 0, 2, 6, 2827, -1, "VineBed", 1);// 76
			AddComplexComponent( (BaseAddon) this, 7954, -4, 1, 0, 0, -1, "VineBed", 1);// 77
			AddComplexComponent( (BaseAddon) this, 2749, -1, 0, 6, 2094, -1, "VineBed", 1);// 78
			AddComplexComponent( (BaseAddon) this, 5029, 0, 1, 6, 2827, -1, "VineBed", 1);// 79
			AddComplexComponent( (BaseAddon) this, 5029, -1, 1, 6, 2827, -1, "VineBed", 1);// 80
			AddComplexComponent( (BaseAddon) this, 5029, -2, 1, 6, 2827, -1, "VineBed", 1);// 81
			AddComplexComponent( (BaseAddon) this, 5030, 0, 2, 6, 2827, -1, "VineBed", 1);// 82
			AddComplexComponent( (BaseAddon) this, 5030, -1, 2, 6, 2827, -1, "VineBed", 1);// 83
			AddComplexComponent( (BaseAddon) this, 5030, -2, 2, 6, 2827, -1, "VineBed", 1);// 84
			AddComplexComponent( (BaseAddon) this, 3166, 0, 0, 6, 0, -1, "VineBed", 1);// 85
			AddComplexComponent( (BaseAddon) this, 2749, 0, -1, 6, 2094, -1, "VineBed", 1);// 86
			AddComplexComponent( (BaseAddon) this, 9375, -4, 3, 16, 2263, -1, "VineBed", 1);// 87
			AddComplexComponent( (BaseAddon) this, 11196, -2, 2, 0, 2761, -1, "VineBed", 1);// 88
			AddComplexComponent( (BaseAddon) this, 9376, 0, 4, 16, 2263, -1, "VineBed", 1);// 89
			AddComplexComponent( (BaseAddon) this, 9376, -3, 4, 16, 2263, -1, "VineBed", 1);// 90
			AddComplexComponent( (BaseAddon) this, 9376, -1, 4, 16, 2263, -1, "VineBed", 1);// 91
			AddComplexComponent( (BaseAddon) this, 9376, -2, 4, 16, 2263, -1, "VineBed", 1);// 92
			AddComplexComponent( (BaseAddon) this, 2749, -1, -2, 6, 2094, -1, "VineBed", 1);// 93
			AddComplexComponent( (BaseAddon) this, 2749, -1, 2, 6, 2094, -1, "VineBed", 1);// 94
			AddComplexComponent( (BaseAddon) this, 2749, 0, -3, 6, 2094, -1, "VineBed", 1);// 95
			AddComplexComponent( (BaseAddon) this, 2749, 0, -2, 6, 2094, -1, "VineBed", 1);// 96
			AddComplexComponent( (BaseAddon) this, 2749, -2, -3, 6, 2094, -1, "VineBed", 1);// 97
			AddComplexComponent( (BaseAddon) this, 2749, -2, -2, 6, 2094, -1, "VineBed", 1);// 98
			AddComplexComponent( (BaseAddon) this, 2749, -2, -1, 6, 2094, -1, "VineBed", 1);// 99
			AddComplexComponent( (BaseAddon) this, 2749, -2, 0, 6, 2094, -1, "VineBed", 1);// 100
			AddComplexComponent( (BaseAddon) this, 2749, -2, 1, 6, 2094, -1, "VineBed", 1);// 101
			AddComplexComponent( (BaseAddon) this, 2749, -2, 1, 6, 2094, -1, "VineBed", 1);// 102
			AddComplexComponent( (BaseAddon) this, 3167, -2, -5, 16, 0, -1, "VineBed", 1);// 103
			AddComplexComponent( (BaseAddon) this, 3166, 0, -2, 6, 0, -1, "VineBed", 1);// 104
			AddComplexComponent( (BaseAddon) this, 3168, -4, 3, 16, 0, -1, "VineBed", 1);// 105
			AddComplexComponent( (BaseAddon) this, 3166, -2, -2, 6, 0, -1, "VineBed", 1);// 106
			AddComplexComponent( (BaseAddon) this, 3166, -1, -1, 6, 0, -1, "VineBed", 1);// 107
			AddComplexComponent( (BaseAddon) this, 3309, -3, -4, 0, 2820, -1, "VineBed", 1);// 108
			AddComplexComponent( (BaseAddon) this, 3310, 1, 5, 0, 2635, -1, "VineBed", 1);// 109
			AddComplexComponent( (BaseAddon) this, 3166, 1, 0, 6, 0, -1, "VineBed", 1);// 110
			AddComplexComponent( (BaseAddon) this, 3168, 2, -3, 6, 0, -1, "VineBed", 1);// 111
			AddComplexComponent( (BaseAddon) this, 3167, 5, -3, 16, 0, -1, "VineBed", 1);// 112
			AddComplexComponent( (BaseAddon) this, 3167, 4, -5, 16, 0, -1, "VineBed", 1);// 113
			AddComplexComponent( (BaseAddon) this, 9375, 5, -4, 16, 2263, -1, "VineBed", 1);// 114
			AddComplexComponent( (BaseAddon) this, 3166, 2, -1, 11, 0, -1, "VineBed", 1);// 115
			AddComplexComponent( (BaseAddon) this, 10806, 5, -5, 0, 2263, -1, "VineBed", 1);// 116
			AddComplexComponent( (BaseAddon) this, 3167, 3, -5, 16, 0, -1, "VineBed", 1);// 117
			AddComplexComponent( (BaseAddon) this, 10806, 5, 4, 0, 2263, -1, "VineBed", 1);// 118
			AddComplexComponent( (BaseAddon) this, 3167, 2, -5, 16, 0, -1, "VineBed", 1);// 119
			AddComplexComponent( (BaseAddon) this, 2749, 2, 1, 6, 2094, -1, "VineBed", 1);// 120
			AddComplexComponent( (BaseAddon) this, 2749, 2, 2, 6, 2094, -1, "VineBed", 1);// 121
			AddComplexComponent( (BaseAddon) this, 3166, 5, -3, 16, 0, -1, "VineBed", 1);// 122
			AddComplexComponent( (BaseAddon) this, 3233, 3, -3, 0, 0, -1, "VineBed", 1);// 123
			AddComplexComponent( (BaseAddon) this, 6817, 6, -5, 0, 0, -1, "VineBed", 1);// 124
			AddComplexComponent( (BaseAddon) this, 3167, 3, -5, 16, 0, -1, "VineBed", 1);// 125
			AddComplexComponent( (BaseAddon) this, 3167, 5, 4, 16, 0, -1, "VineBed", 1);// 126
			AddComplexComponent( (BaseAddon) this, 9376, 4, 4, 16, 2263, -1, "VineBed", 1);// 127
			AddComplexComponent( (BaseAddon) this, 3122, 2, -3, 0, 2094, -1, "VineBed", 1);// 128
			AddComplexComponent( (BaseAddon) this, 3122, 2, -2, 0, 2094, -1, "VineBed", 1);// 129
			AddComplexComponent( (BaseAddon) this, 5032, 1, 1, 6, 2820, -1, "VineBed", 1);// 130
			AddComplexComponent( (BaseAddon) this, 3307, 5, -4, 0, 2820, -1, "VineBed", 1);// 131
			AddComplexComponent( (BaseAddon) this, 3167, 5, -4, 16, 0, -1, "VineBed", 1);// 132
			AddComplexComponent( (BaseAddon) this, 2749, 1, -3, 6, 2094, -1, "VineBed", 1);// 133
			AddComplexComponent( (BaseAddon) this, 2749, 2, -2, 6, 2094, -1, "VineBed", 1);// 134
			AddComplexComponent( (BaseAddon) this, 2749, 2, -3, 6, 2094, -1, "VineBed", 1);// 135
			AddComplexComponent( (BaseAddon) this, 3167, 1, -1, 6, 0, -1, "VineBed", 1);// 136
			AddComplexComponent( (BaseAddon) this, 9376, 3, -5, 16, 2263, -1, "VineBed", 1);// 137
			AddComplexComponent( (BaseAddon) this, 3166, 2, 0, 6, 0, -1, "VineBed", 1);// 138
			AddComplexComponent( (BaseAddon) this, 5036, 1, 2, 12, 2820, -1, "VineBed", 1);// 139
			AddComplexComponent( (BaseAddon) this, 9376, 2, -5, 16, 2263, -1, "VineBed", 1);// 140
			AddComplexComponent( (BaseAddon) this, 9376, 1, -5, 16, 2263, -1, "VineBed", 1);// 141
			AddComplexComponent( (BaseAddon) this, 5036, 2, 2, 12, 2820, -1, "VineBed", 1);// 142
			AddComplexComponent( (BaseAddon) this, 2749, 1, 1, 6, 2094, -1, "VineBed", 1);// 143
			AddComplexComponent( (BaseAddon) this, 3310, 3, 5, 0, 0, -1, "VineBed", 1);// 144
			AddComplexComponent( (BaseAddon) this, 5029, 2, 2, 6, 2581, -1, "VineBed", 1);// 145
			AddComplexComponent( (BaseAddon) this, 3167, 1, 4, 16, 0, -1, "VineBed", 1);// 146
			AddComplexComponent( (BaseAddon) this, 2749, 1, 0, 6, 2094, -1, "VineBed", 1);// 147
			AddComplexComponent( (BaseAddon) this, 2749, 1, -1, 6, 2094, -1, "VineBed", 1);// 148
			AddComplexComponent( (BaseAddon) this, 9375, 5, -1, 16, 2263, -1, "VineBed", 1);// 149
			AddComplexComponent( (BaseAddon) this, 2749, 1, -2, 6, 2094, -1, "VineBed", 1);// 150
			AddComplexComponent( (BaseAddon) this, 3122, 2, 1, 0, 2094, -1, "VineBed", 1);// 151
			AddComplexComponent( (BaseAddon) this, 3122, 2, 0, 0, 2094, -1, "VineBed", 1);// 152
			AddComplexComponent( (BaseAddon) this, 3122, 2, -1, 0, 2094, -1, "VineBed", 1);// 153
			AddComplexComponent( (BaseAddon) this, 9376, 5, 4, 16, 2263, -1, "VineBed", 1);// 154
			AddComplexComponent( (BaseAddon) this, 3311, 6, 4, 0, 0, -1, "VineBed", 1);// 155
			AddComplexComponent( (BaseAddon) this, 9376, 4, -5, 16, 2263, -1, "VineBed", 1);// 156
			AddComplexComponent( (BaseAddon) this, 3167, 1, -5, 16, 0, -1, "VineBed", 1);// 157
			AddComplexComponent( (BaseAddon) this, 11504, 2, 2, 7, 2761, -1, "VineBed", 1);// 158
			AddComplexComponent( (BaseAddon) this, 9376, 2, 4, 16, 2263, -1, "VineBed", 1);// 159
			AddComplexComponent( (BaseAddon) this, 2749, 2, 0, 6, 2094, -1, "VineBed", 1);// 160
			AddComplexComponent( (BaseAddon) this, 3167, 4, -5, 16, 0, -1, "VineBed", 1);// 161
			AddComplexComponent( (BaseAddon) this, 9375, 5, 0, 16, 2263, -1, "VineBed", 1);// 162
			AddComplexComponent( (BaseAddon) this, 3167, 3, 4, 16, 0, -1, "VineBed", 1);// 163
			AddComplexComponent( (BaseAddon) this, 3166, 5, -1, 16, 0, -1, "VineBed", 1);// 164
			AddComplexComponent( (BaseAddon) this, 3166, 2, -2, 6, 0, -1, "VineBed", 1);// 165
			AddComplexComponent( (BaseAddon) this, 3166, 5, 4, 16, 0, -1, "VineBed", 1);// 166
			AddComplexComponent( (BaseAddon) this, 5035, 2, 1, 9, 2761, -1, "VineBed", 1);// 167
			AddComplexComponent( (BaseAddon) this, 3167, 3, -5, 16, 0, -1, "VineBed", 1);// 168
			AddComplexComponent( (BaseAddon) this, 3166, 5, 3, 16, 0, -1, "VineBed", 1);// 169
			AddComplexComponent( (BaseAddon) this, 3166, 5, -5, 20, 0, -1, "VineBed", 1);// 170
			AddComplexComponent( (BaseAddon) this, 3167, 2, 4, 16, 0, -1, "VineBed", 1);// 171
			AddComplexComponent( (BaseAddon) this, 3166, 5, 1, 16, 0, -1, "VineBed", 1);// 172
			AddComplexComponent( (BaseAddon) this, 3166, 5, 2, 16, 0, -1, "VineBed", 1);// 173
			AddComplexComponent( (BaseAddon) this, 3311, 6, 4, 0, 0, -1, "VineBed", 1);// 174
			AddComplexComponent( (BaseAddon) this, 5035, 1, 1, 9, 2761, -1, "VineBed", 1);// 175
			AddComplexComponent( (BaseAddon) this, 11196, 1, 2, 0, 2761, -1, "VineBed", 1);// 176
			AddComplexComponent( (BaseAddon) this, 3167, 4, 4, 16, 0, -1, "VineBed", 1);// 177
			AddComplexComponent( (BaseAddon) this, 2749, 1, 2, 6, 2094, -1, "VineBed", 1);// 178
			AddComplexComponent( (BaseAddon) this, 3166, 5, -2, 16, 0, -1, "VineBed", 1);// 179
			AddComplexComponent( (BaseAddon) this, 9375, 5, -2, 16, 2263, -1, "VineBed", 1);// 180
			AddComplexComponent( (BaseAddon) this, 9376, 4, 4, 16, 2263, -1, "VineBed", 1);// 181
			AddComplexComponent( (BaseAddon) this, 3166, 1, -3, 6, 0, -1, "VineBed", 1);// 182
			AddComplexComponent( (BaseAddon) this, 9375, 5, 2, 16, 2263, -1, "VineBed", 1);// 183
			AddComplexComponent( (BaseAddon) this, 9375, 5, 1, 16, 2263, -1, "VineBed", 1);// 184
			AddComplexComponent( (BaseAddon) this, 9375, 5, 4, 16, 2263, -1, "VineBed", 1);// 185
			AddComplexComponent( (BaseAddon) this, 9375, 5, 3, 16, 2263, -1, "VineBed", 1);// 186
			AddComplexComponent( (BaseAddon) this, 11504, 1, 2, 7, 2761, -1, "VineBed", 1);// 187
			AddComplexComponent( (BaseAddon) this, 11196, 2, 2, 0, 2094, -1, "VineBed", 1);// 188
			AddComplexComponent( (BaseAddon) this, 3311, 6, -4, 0, 2820, -1, "VineBed", 1);// 189
			AddComplexComponent( (BaseAddon) this, 3167, 5, -5, 16, 0, -1, "VineBed", 1);// 190
			AddComplexComponent( (BaseAddon) this, 3166, 5, -5, 16, 0, -1, "VineBed", 1);// 191
			AddComplexComponent( (BaseAddon) this, 3166, 5, -4, 16, 0, -1, "VineBed", 1);// 192
			AddComplexComponent( (BaseAddon) this, 3310, 4, 5, 0, 2820, -1, "VineBed", 1);// 193
			AddComplexComponent( (BaseAddon) this, 9375, 5, -3, 16, 2263, -1, "VineBed", 1);// 194
			AddComplexComponent( (BaseAddon) this, 9376, 1, 4, 16, 2263, -1, "VineBed", 1);// 195
			AddComplexComponent( (BaseAddon) this, 9376, 3, 4, 16, 2263, -1, "VineBed", 1);// 196
			AddComplexComponent( (BaseAddon) this, 6817, 6, 5, 0, 0, -1, "VineBed", 1);// 197
			AddComplexComponent( (BaseAddon) this, 3166, 1, -2, 9, 0, -1, "VineBed", 1);// 198
			AddComplexComponent( (BaseAddon) this, 5691, 2, 2, 9, 2071, -1, "VineBed", 1);// 199
			AddComplexComponent( (BaseAddon) this, 5691, 1, 2, 9, 2071, -1, "VineBed", 1);// 200
			AddComplexComponent( (BaseAddon) this, 3167, 2, -5, 16, 0, -1, "VineBed", 1);// 201
			AddComplexComponent( (BaseAddon) this, 2749, 2, -1, 6, 2094, -1, "VineBed", 1);// 202
			AddComplexComponent( (BaseAddon) this, 5690, 2, 2, 6, 2827, -1, "VineBed", 1);// 203
			AddComplexComponent( (BaseAddon) this, 5690, 1, 2, 6, 2827, -1, "VineBed", 1);// 204
			AddComplexComponent( (BaseAddon) this, 5029, 2, 1, 6, 2827, -1, "VineBed", 1);// 205
			AddComplexComponent( (BaseAddon) this, 5029, 1, 1, 6, 2827, -1, "VineBed", 1);// 206
			AddComplexComponent( (BaseAddon) this, 5030, 2, 2, 6, 2827, -1, "VineBed", 1);// 207
			AddComplexComponent( (BaseAddon) this, 5030, 1, 2, 6, 2827, -1, "VineBed", 1);// 208
			AddComplexComponent( (BaseAddon) this, 3123, 2, 2, 0, 2094, -1, "VineBed", 1);// 209
			AddComplexComponent( (BaseAddon) this, 9376, 5, -5, 16, 2263, -1, "VineBed", 1);// 210
			AddComplexComponent( (BaseAddon) this, 3166, 5, 0, 16, 0, -1, "VineBed", 1);// 211
			AddComplexComponent( (BaseAddon) this, 3167, 5, -5, 16, 0, -1, "VineBed", 1);// 212

		}

		public VineBedAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class VineBedAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new VineBedAddon();
			}
		}

		[Constructable]
		public VineBedAddonDeed()
		{
			Name = "VineBed";
		}

		public VineBedAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}