/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CouchWestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CouchWestAddonDeed();
			}
		}

		[ Constructable ]
		public CouchWestAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1801 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1114 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1114 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1114 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 5028 );
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 5028 );
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 5028 );
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 5690 );
			AddComponent( ac, 1, -2, 5 );
			ac = new AddonComponent( 5690 );
			AddComponent( ac, 1, 2, 5 );
			ac = new AddonComponent( 5035 );
			AddComponent( ac, 0, 2, 5 );
			ac = new AddonComponent( 5035 );
			AddComponent( ac, 0, -2, 5 );

		}

		public CouchWestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CouchWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CouchWestAddon();
			}
		}

		[Constructable]
		public CouchWestAddonDeed()
		{
			Name = "CouchWest";
		}

		public CouchWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}