/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FancyCounter2EastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FancyCounter2EastAddonDeed();
			}
		}

		[ Constructable ]
		public FancyCounter2EastAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 6416 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6428 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6428 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6428 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6430 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2449 );
			AddComponent( ac, 0, 2, 8 );
			ac = new AddonComponent( 2449 );
			AddComponent( ac, 0, 1, 8 );
			ac = new AddonComponent( 2519 );
			AddComponent( ac, 1, -2, 8 );
			ac = new AddonComponent( 2519 );
			AddComponent( ac, 1, -2, 9 );
			ac = new AddonComponent( 2519 );
			AddComponent( ac, 1, -2, 10 );
			ac = new AddonComponent( 2519 );
			AddComponent( ac, 0, -2, 8 );
			ac = new AddonComponent( 2519 );
			AddComponent( ac, 0, -2, 9 );
			ac = new AddonComponent( 2519 );
			AddComponent( ac, 0, -2, 10 );
			ac = new AddonComponent( 6428 );
			AddComponent( ac, 0, -1, 0 );

		}

		public FancyCounter2EastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FancyCounter2EastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FancyCounter2EastAddon();
			}
		}

		[Constructable]
		public FancyCounter2EastAddonDeed()
		{
			Name = "FancyCounter2East";
		}

		public FancyCounter2EastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}