/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FountainPoolEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FountainPoolEastAddonDeed();
			}
		}

		[ Constructable ]
		public FountainPoolEastAddon()
		{
			AddComponent( new AddonComponent( 1302 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 13488 ), 1, 1, 7 );
			AddComponent( new AddonComponent( 13422 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 65 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 10298 ), 1, 1, 9 );
			AddComponent( new AddonComponent( 13422 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 67 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 10301 ), 1, 0, 6 );
			AddComponent( new AddonComponent( 1302 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 66 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 1302 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 68 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 1302 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 66 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 1302 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 3332 ), 0, 1, 7 );
			AddComponent( new AddonComponent( 7950 ), 0, 1, 26 );
			AddComponent( new AddonComponent( 3311 ), 0, 1, 3 );
			AddComponent( new AddonComponent( 13422 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 66 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 3312 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 13555 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 13422 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 53 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 1302 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 60 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, 2, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, -1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 1302 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1302 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1302 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 13488 );
			AddComponent( ac, 1, 1, 7 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 0, 1, 7 );
			ac = new AddonComponent( 3312 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 7950 );
			AddComponent( ac, 0, 1, 26 );
			ac = new AddonComponent( 53 );
			ac.Hue = 1150;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3311 );
			AddComponent( ac, 0, 1, 3 );
			ac = new AddonComponent( 13555 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 68 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 67 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 66 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 66 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 66 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 65 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 60 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 1150;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 10298 );
			AddComponent( ac, 1, 1, 9 );
			ac = new AddonComponent( 10301 );
			AddComponent( ac, 1, 0, 6 );

		}

		public FountainPoolEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FountainPoolEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FountainPoolEastAddon();
			}
		}

		[Constructable]
		public FountainPoolEastAddonDeed()
		{
			Name = "FountainPoolEast";
		}

		public FountainPoolEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}