/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FountainPoolSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FountainPoolSouthAddonDeed();
			}
		}

		[ Constructable ]
		public FountainPoolSouthAddon()
		{
			AddComponent( new AddonComponent( 1302 ), 1, 2, 0 );
			AddComponent( new AddonComponent( 13451 ), 1, 1, 7 );
			AddComponent( new AddonComponent( 13422 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 65 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 10298 ), 1, 1, 11 );
			AddComponent( new AddonComponent( 1302 ), 0, 2, 0 );
			AddComponent( new AddonComponent( 1302 ), -1, 2, 0 );
			AddComponent( new AddonComponent( 1302 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 67 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 1302 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 67 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 13422 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 66 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 10301 ), 0, 1, 7 );
			AddComponent( new AddonComponent( 1302 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 59 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 3307 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 13579 ), 0, 0, 1 );
			AddComponent( new AddonComponent( 13422 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 7949 ), 1, 0, 21 );
			AddComponent( new AddonComponent( 7949 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 3332 ), 1, 0, 7 );
			AddComponent( new AddonComponent( 3307 ), 1, 0, 1 );
			AddComponent( new AddonComponent( 13422 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 67 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 1302 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 59 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, 2, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 1302 ), 2, -1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 1302 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1302 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1302 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1302 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 7949 );
			AddComponent( ac, 1, 0, 21 );
			ac = new AddonComponent( 7949 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3332 );
			AddComponent( ac, 1, 0, 7 );
			ac = new AddonComponent( 3307 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3307 );
			AddComponent( ac, 1, 0, 1 );
			ac = new AddonComponent( 13451 );
			AddComponent( ac, 1, 1, 7 );
			ac = new AddonComponent( 13579 );
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 67 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 67 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 67 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 66 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 65 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 59 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 1150;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 59 );
			ac.Light = LightType.ArchedWindowEast;
			ac.Hue = 1150;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 10298 );
			AddComponent( ac, 1, 1, 11 );
			ac = new AddonComponent( 10301 );
			AddComponent( ac, 0, 1, 7 );

		}

		public FountainPoolSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FountainPoolSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FountainPoolSouthAddon();
			}
		}

		[Constructable]
		public FountainPoolSouthAddonDeed()
		{
			Name = "FountainPoolSouth";
		}

		public FountainPoolSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}