/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class STableWLampAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new STableWLampAddonDeed();
			}
		}

		[ Constructable ]
		public STableWLampAddon()
		{
			AddComponent( new AddonComponent( 7807 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 2842 ), 0, 0, 8 );
			AddComponent( new AddonComponent( 2330 ), 0, 0, 10 );
			AddonComponent ac = null;

		}

		public STableWLampAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class STableWLampAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new STableWLampAddon();
			}
		}

		[Constructable]
		public STableWLampAddonDeed()
		{
			Name = "STableWLamp";
		}

		public STableWLampAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}