/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CandycaneDecoAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CandycaneDecoAddonDeed();
			}
		}

		[ Constructable ]
		public CandycaneDecoAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 2594 );
			ac.Light = LightType.Circle225;
			ac.Hue = 1369;
			AddComponent( ac, 0, 1, 11 );
			ac = new AddonComponent( 933 );
			ac.Hue = 1153;
			ac.Name = "candycane";
			AddComponent( ac, 1, 0, 24 );
			ac = new AddonComponent( 933 );
			ac.Hue = 138;
			ac.Name = "candycane";
			AddComponent( ac, 1, 0, 19 );
			ac = new AddonComponent( 933 );
			ac.Hue = 1153;
			ac.Name = "candycane";
			AddComponent( ac, 1, 0, 14 );
			ac = new AddonComponent( 933 );
			ac.Hue = 138;
			ac.Name = "candycane";
			AddComponent( ac, 1, 0, 9 );
			ac = new AddonComponent( 933 );
			ac.Hue = 1153;
			ac.Name = "candycane";
			AddComponent( ac, 1, 0, 4 );
			ac = new AddonComponent( 933 );
			ac.Hue = 138;
			ac.Name = "candycane";
			AddComponent( ac, 1, 0, 0 );

		}

		public CandycaneDecoAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CandycaneDecoAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CandycaneDecoAddon();
			}
		}

		[Constructable]
		public CandycaneDecoAddonDeed()
		{
			Name = "CandycaneDeco";
		}

		public CandycaneDecoAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}