
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ChristmasTreeSkirtAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6090, -2, 0, 0}, {6085, -2, -2, 0}, {6092, 2, 0, 0}// 4	8	9	
			, {6090, -2, 1, 0}, {6092, 2, -1, 0}, {6091, 0, -2, 0}// 10	15	21	
			, {6086, 2, -2, 0}, {6091, -1, -2, 0}, {6092, 2, 1, 0}// 22	24	25	
			, {6091, 1, -2, 0}, {6090, -2, -1, 0}, {6088, -2, 2, 0}// 26	27	28	
			, {6087, 2, 2, 0}, {6089, 0, 2, 0}, {6089, 1, 2, 0}// 29	30	31	
			, {6089, -1, 2, 0}// 32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ChristmasTreeSkirtAddonDeed();
			}
		}

		[ Constructable ]
		public ChristmasTreeSkirtAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2254, -1, 1, 0, 1260, -1, "Christmas Tree Skirt", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3530, 0, -1, 0, 168, -1, "Christmas Tree Skirt", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3530, 1, 0, 0, 168, -1, "Christmas Tree Skirt", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3530, 0, 1, 0, 168, -1, "Christmas Tree Skirt", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3530, -1, 0, 0, 168, -1, "Christmas Tree Skirt", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2254, -1, -2, 0, 1260, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2252, -2, 1, 0, 1260, -1, "Christmas Tree Skirt", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3530, 1, -1, 0, 33, -1, "Christmas Tree Skirt", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2253, 1, 1, 0, 1260, -1, "Christmas Tree Skirt", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3530, -1, 1, 0, 33, -1, "Christmas Tree Skirt", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3530, 1, 1, 0, 33, -1, "Christmas Tree Skirt", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2252, 1, -1, 0, 1260, -1, "Christmas Tree Skirt", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3530, 0, 0, 0, 33, -1, "Christmas Tree Skirt", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3530, -1, -1, 0, 33, -1, "Christmas Tree Skirt", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2252, -2, -1, 0, 1260, -1, "Christmas Tree Skirt", 1);// 20
			AddComplexComponent( (BaseAddon) this, 2254, 1, -2, 0, 1260, -1, "", 1);// 23

		}

		public ChristmasTreeSkirtAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ChristmasTreeSkirtAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ChristmasTreeSkirtAddon();
			}
		}

		[Constructable]
		public ChristmasTreeSkirtAddonDeed()
		{
			Name = "ChristmasTreeSkirt";
		}

		public ChristmasTreeSkirtAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}