
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FireplaceBrickCustomSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7134, 0, 0, 1}, {7137, 0, 0, 3}// 24	25	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FireplaceBrickCustomSouthAddonDeed();
			}
		}

		[ Constructable ]
		public FireplaceBrickCustomSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 51, 2, 0, 0, 0, -1, "Fireplace Custom Brick", 1);// 1
			AddComplexComponent( (BaseAddon) this, 51, -1, 0, 0, 0, -1, "Fireplace Custom Brick", 1);// 2
			AddComplexComponent( (BaseAddon) this, 52, 2, -1, 0, 0, -1, "Fireplace Custom Brick", 1);// 3
			AddComplexComponent( (BaseAddon) this, 52, 1, -1, 0, 0, -1, "Fireplace Custom Brick", 1);// 4
			AddComplexComponent( (BaseAddon) this, 52, 0, -1, 0, 0, -1, "Fireplace Custom Brick", 1);// 5
			AddComplexComponent( (BaseAddon) this, 52, -1, -1, 0, 0, -1, "Fireplace Custom Brick", 1);// 6
			AddComplexComponent( (BaseAddon) this, 53, -2, 0, 0, 0, -1, "Fireplace Custom Brick", 1);// 7
			AddComplexComponent( (BaseAddon) this, 53, 1, 0, 0, 0, -1, "Fireplace Custom Brick", 1);// 8
			AddComplexComponent( (BaseAddon) this, 54, -2, -1, 0, 0, -1, "Fireplace Custom Brick", 1);// 9
			AddComplexComponent( (BaseAddon) this, 71, 0, 0, 0, 0, -1, "Fireplace Custom Brick", 1);// 10
			AddComplexComponent( (BaseAddon) this, 72, 1, 0, 0, 0, -1, "Fireplace Custom Brick", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1981, 0, 0, 0, 1109, -1, "Fireplace Custom Brick", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1981, 1, 0, 0, 1109, -1, "Fireplace Custom Brick", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1981, 0, 1, 0, 1109, -1, "Fireplace Custom Brick", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1981, 1, 1, 0, 1109, -1, "Fireplace Custom Brick", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1981, 2, 1, 0, 1109, -1, "Fireplace Custom Brick", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1981, -1, 1, 0, 1109, -1, "Fireplace Custom Brick", 1);// 17
			AddComplexComponent( (BaseAddon) this, 82, 2, 1, 0, 0, -1, "Fireplace Custom Brick", 1);// 18
			AddComplexComponent( (BaseAddon) this, 83, 1, 1, 0, 0, -1, "Fireplace Custom Brick", 1);// 19
			AddComplexComponent( (BaseAddon) this, 83, 0, 1, 0, 0, -1, "Fireplace Custom Brick", 1);// 20
			AddComplexComponent( (BaseAddon) this, 83, -1, 1, 0, 0, -1, "Fireplace Custom Brick", 1);// 21
			AddComplexComponent( (BaseAddon) this, 84, -2, 1, 0, 0, -1, "Fireplace Custom Brick", 1);// 22
			AddComplexComponent( (BaseAddon) this, 3561, 0, 0, 1, 0, 1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 3561, 0, 0, 5, 0, 1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 3555, 0, 0, 6, 0, 1, "", 1);// 27

		}

		public FireplaceBrickCustomSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FireplaceBrickCustomSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FireplaceBrickCustomSouthAddon();
			}
		}

		[Constructable]
		public FireplaceBrickCustomSouthAddonDeed()
		{
			Name = "FireplaceBrickCustomSouth";
		}

		public FireplaceBrickCustomSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}