/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarbleTVAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarbleTVAddonDeed();
			}
		}

		[ Constructable ]
		public MarbleTVAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, -1, 0, 9 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 2, 0, 9 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 4;
			ac.Name = "TV Screen";
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 4;
			ac.Name = "TV Screen";
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 0, 0, 14 );
			ac = new AddonComponent( 1173 );
			AddComponent( ac, 1, 0, 14 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 2, 0, 14 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 1, 0, 14 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, 0, 0, 14 );
			ac = new AddonComponent( 1801 );
			ac.Name = "Television";
			AddComponent( ac, -1, 0, 14 );
			ac = new AddonComponent( 7891 );
			ac.Hue = 1104;
			ac.Name = "Speaker";
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 7891 );
			ac.Hue = 1104;
			ac.Name = "Speaker";
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 3888 );
			ac.Hue = 38;
			ac.Name = "Power Light";
			AddComponent( ac, -1, 1, 9 );
			ac = new AddonComponent( 3856 );
			ac.Hue = 1107;
			ac.Name = "Remote Sensor";
			AddComponent( ac, 0, 0, 1 );
			ac = new AddonComponent( 3866 );
			ac.Hue = 1108;
			ac.Name = "Volume Up";
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 3869 );
			ac.Hue = 1108;
			ac.Name = "Volume Down";
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 3866 );
			ac.Hue = 1108;
			ac.Name = "Channel Up";
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 3869 );
			ac.Hue = 1108;
			ac.Name = "Channel Down";
			AddComponent( ac, 1, 1, 5 );

		}

		public MarbleTVAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarbleTVAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarbleTVAddon();
			}
		}

		[Constructable]
		public MarbleTVAddonDeed()
		{
			Name = "MarbleTV";
		}

		public MarbleTVAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}