
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SantasLargeSnowglobeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2254, 0, -1, 11}, {2254, 1, -1, 11}, {2254, 2, -1, 11}// 1	2	3	
			, {2254, 0, -1, 32}, {9002, 2, 0, 11}, {6079, 1, 0, 11}// 9	10	13	
			, {2252, -1, 0, 11}, {6078, 0, 0, 11}, {2252, -1, 1, 11}// 25	26	31	
			, {2252, -1, 2, 11}, {6080, 0, 1, 11}, {6079, 2, 2, 11}// 32	43	50	
			, {6078, 1, 1, 11}, {3886, 1, 1, 25}, {6087, 1, 2, 12}// 53	54	74	
			, {6088, 2, 1, 11}, {6085, 1, 2, 11}// 75	76	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SantasLargeSnowglobeAddonDeed();
			}
		}

		[ Constructable ]
		public SantasLargeSnowglobeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2252, 2, 0, 11, 0, -1, "snowglobe", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2254, 1, 0, 32, 0, -1, "snowglobe", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2252, -1, 0, 32, 0, -1, "snowglobe", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3882, 0, 0, 20, 0, -1, "christmas light", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2252, 2, 0, 32, 0, -1, "snowglobe", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2254, 1, -1, 32, 0, -1, "snowglobe", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2254, 2, -1, 32, 0, -1, "snowglobe", 1);// 12
			AddComplexComponent( (BaseAddon) this, 3884, 0, 0, 22, 1372, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3876, 0, 0, 22, 0, -1, "christmas light", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6077, 2, 0, 11, 0, -1, "snowglobe", 1);// 16
			AddComplexComponent( (BaseAddon) this, 7385, 0, 0, 32, 1153, -1, "glass", 1);// 17
			AddComplexComponent( (BaseAddon) this, 7385, 1, 0, 32, 1153, -1, "glass", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6827, 2, -1, 0, 32, -1, "snowglobe", 1);// 19
			AddComplexComponent( (BaseAddon) this, 7385, 2, 0, 32, 1153, -1, "glass", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6843, 2, -1, 7, 32, -1, "snowglobe", 1);// 21
			AddComplexComponent( (BaseAddon) this, 11180, 2, -1, 11, 32, -1, "snowglobe", 1);// 22
			AddComplexComponent( (BaseAddon) this, 3887, 0, 0, 20, 0, -1, "christmas light", 1);// 23
			AddComplexComponent( (BaseAddon) this, 6826, 2, 0, 0, 32, -1, "snowglobe", 1);// 24
			AddComplexComponent( (BaseAddon) this, 10682, 1, -1, 11, 1153, 1, "snowglobe", 1);// 27
			AddComplexComponent( (BaseAddon) this, 10682, 0, -1, 11, 1153, 1, "snowglobe", 1);// 28
			AddComplexComponent( (BaseAddon) this, 10683, -1, 0, 11, 1153, 1, "snowglobe", 1);// 29
			AddComplexComponent( (BaseAddon) this, 3272, 0, 0, 14, 0, -1, "tree", 1);// 30
			AddComplexComponent( (BaseAddon) this, 2252, 2, 1, 11, 0, -1, "snowglobe", 1);// 33
			AddComplexComponent( (BaseAddon) this, 2254, 0, 2, 11, 0, -1, "snowglobe", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2254, 1, 2, 11, 0, -1, "snowglobe", 1);// 35
			AddComplexComponent( (BaseAddon) this, 2253, 2, 2, 11, 0, -1, "snowglobe", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2252, -1, 1, 32, 0, -1, "snowglobe", 1);// 37
			AddComplexComponent( (BaseAddon) this, 2252, -1, 2, 32, 0, -1, "snowglobe", 1);// 38
			AddComplexComponent( (BaseAddon) this, 10683, -1, 1, 11, 1153, 1, "snowglobe", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2252, 0, 1, 32, 0, -1, "snowglobe", 1);// 40
			AddComplexComponent( (BaseAddon) this, 2253, 1, 1, 32, 0, -1, "snowglobe", 1);// 41
			AddComplexComponent( (BaseAddon) this, 14952, 2, 1, 10, 0, -1, "reindeer", 1);// 42
			AddComplexComponent( (BaseAddon) this, 9009, 0, 2, 11, 33, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 14202, 2, 2, 21, 1153, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2254, 0, 2, 32, 0, -1, "snowglobe", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2253, 1, 2, 32, 0, -1, "snowglobe", 1);// 47
			AddComplexComponent( (BaseAddon) this, 6077, 0, 2, 11, 0, -1, "snowglobe", 1);// 48
			AddComplexComponent( (BaseAddon) this, 3861, 1, 1, 26, 0, -1, "christmas light", 1);// 49
			AddComplexComponent( (BaseAddon) this, 6080, 2, 1, 11, 0, -1, "snowglobe", 1);// 51
			AddComplexComponent( (BaseAddon) this, 6078, 1, 2, 11, 0, -1, "snowglobe", 1);// 52
			AddComplexComponent( (BaseAddon) this, 7385, 0, 1, 32, 1153, -1, "glass", 1);// 55
			AddComplexComponent( (BaseAddon) this, 6843, -1, 2, 7, 32, -1, "snowglobe", 1);// 56
			AddComplexComponent( (BaseAddon) this, 6822, 0, 2, 0, 32, -1, "snowglobe", 1);// 57
			AddComplexComponent( (BaseAddon) this, 11177, -1, 2, 11, 32, -1, "snowglobe", 1);// 58
			AddComplexComponent( (BaseAddon) this, 6821, -1, 2, 0, 32, -1, "snowglobe", 1);// 59
			AddComplexComponent( (BaseAddon) this, 3867, 1, 1, 23, 0, -1, "christmas light", 1);// 60
			AddComplexComponent( (BaseAddon) this, 6825, 2, 1, 0, 32, -1, "snowglobe", 1);// 61
			AddComplexComponent( (BaseAddon) this, 7385, 2, 1, 32, 1153, -1, "glass", 1);// 62
			AddComplexComponent( (BaseAddon) this, 2253, 2, 1, 32, 0, -1, "snowglobe", 1);// 63
			AddComplexComponent( (BaseAddon) this, 6824, 2, 2, 0, 32, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 7385, 1, 2, 32, 1153, -1, "glass", 1);// 65
			AddComplexComponent( (BaseAddon) this, 6823, 1, 2, 0, 32, -1, "snowglobe", 1);// 66
			AddComplexComponent( (BaseAddon) this, 10379, 2, 2, 13, 1367, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 14964, 0, 1, 11, 0, -1, "sleigh", 1);// 68
			AddComplexComponent( (BaseAddon) this, 2472, 2, 2, 16, 32, -1, "mailbox", 1);// 69
			AddComplexComponent( (BaseAddon) this, 3883, 0, 1, 22, 0, -1, "christmas light", 1);// 70
			AddComplexComponent( (BaseAddon) this, 14202, 2, 1, 33, 1153, -1, "snow", 1);// 71
			AddComplexComponent( (BaseAddon) this, 7385, 0, 2, 32, 1153, -1, "glass", 1);// 72
			AddComplexComponent( (BaseAddon) this, 14966, 1, 1, 11, 0, -1, "sleigh", 1);// 73

		}

		public SantasLargeSnowglobeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SantasLargeSnowglobeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SantasLargeSnowglobeAddon();
			}
		}

		[Constructable]
		public SantasLargeSnowglobeAddonDeed()
		{
			Name = "SantasLargeSnowglobe";
		}

		public SantasLargeSnowglobeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}