/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SantasSleighNew1Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SantasSleighNew1AddonDeed();
			}
		}

		[ Constructable ]
		public SantasSleighNew1Addon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 8967 );
			ac.Hue = 1368;
			ac.Name = "Christmas Stocking";
			AddComponent( ac, 0, 1, 33 );
			ac = new AddonComponent( 9002 );
			ac.Hue = 33;
			ac.Name = "Present";
			AddComponent( ac, -1, 0, 19 );
			ac = new AddonComponent( 9002 );
			ac.Hue = 148;
			ac.Name = "Present";
			AddComponent( ac, -1, 0, 15 );
			ac = new AddonComponent( 9002 );
			ac.Name = "Present";
			AddComponent( ac, -1, 1, 19 );
			ac = new AddonComponent( 3519 );
			AddComponent( ac, -1, 1, 29 );
			ac = new AddonComponent( 3962 );
			ac.Hue = 33;
			ac.Name = "Berry";
			AddComponent( ac, 0, 0, 26 );
			ac = new AddonComponent( 3962 );
			ac.Hue = 33;
			ac.Name = "Berry";
			AddComponent( ac, 0, 2, 28 );
			ac = new AddonComponent( 3962 );
			ac.Hue = 33;
			ac.Name = "Berry";
			AddComponent( ac, 2, 0, 23 );
			ac = new AddonComponent( 3962 );
			ac.Hue = 33;
			AddComponent( ac, 1, 0, 16 );
			ac = new AddonComponent( 3962 );
			ac.Hue = 33;
			ac.Name = "Berry";
			AddComponent( ac, 2, 2, 25 );
			ac = new AddonComponent( 3169 );
			ac.Name = "Holly";
			AddComponent( ac, 0, 0, 24 );
			ac = new AddonComponent( 3169 );
			ac.Name = "Holly";
			AddComponent( ac, 0, 2, 26 );
			ac = new AddonComponent( 3169 );
			ac.Name = "Holly";
			AddComponent( ac, 2, 0, 21 );
			ac = new AddonComponent( 3169 );
			ac.Name = "Holly";
			AddComponent( ac, 2, 2, 23 );
			ac = new AddonComponent( 11727 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, -1, 0, 11 );
			ac = new AddonComponent( 11727 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, -1, 1, 11 );
			ac = new AddonComponent( 3740 );
			AddComponent( ac, -1, 0, 23 );
			ac = new AddonComponent( 413 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 8472 );
			ac.Name = "Teddy Bear";
			AddComponent( ac, -1, 1, 25 );
			ac = new AddonComponent( 2252 );
			ac.Name = "Sleigh";
			AddComponent( ac, -1, 1, 17 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1108;
			ac.Name = "Sleigh";
			AddComponent( ac, -1, 0, 9 );
			ac = new AddonComponent( 218 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 218 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 2860 );
			ac.Hue = 1368;
			ac.Name = "Seat";
			AddComponent( ac, 0, 1, 11 );
			ac = new AddonComponent( 2860 );
			ac.Hue = 1368;
			ac.Name = "Seat";
			AddComponent( ac, 0, 0, 11 );
			ac = new AddonComponent( 2668 );
			ac.Hue = 1368;
			ac.Name = "Blanket";
			AddComponent( ac, 1, 0, 17 );
			ac = new AddonComponent( 2668 );
			ac.Hue = 1368;
			ac.Name = "Blanket";
			AddComponent( ac, 1, 1, 17 );
			ac = new AddonComponent( 3121 );
			ac.Hue = 1368;
			AddComponent( ac, 1, 0, 11 );
			ac = new AddonComponent( 3121 );
			ac.Hue = 1368;
			ac.Name = "Blanket";
			AddComponent( ac, 1, 1, 13 );
			ac = new AddonComponent( 3126 );
			ac.Hue = 1368;
			ac.Name = "Blanket";
			AddComponent( ac, 1, 0, 12 );
			ac = new AddonComponent( 2254 );
			ac.Name = "Sleigh";
			AddComponent( ac, 0, 1, 12 );
			ac = new AddonComponent( 2252 );
			ac.Name = "Sleigh";
			AddComponent( ac, -1, 0, 17 );
			ac = new AddonComponent( 2252 );
			ac.Name = "Sleigh";
			AddComponent( ac, -2, 0, 21 );
			ac = new AddonComponent( 2252 );
			ac.Name = "Sleigh";
			AddComponent( ac, -2, 1, 21 );
			ac = new AddonComponent( 2252 );
			ac.Name = "Sleigh";
			AddComponent( ac, 1, 0, 15 );
			ac = new AddonComponent( 2253 );
			AddComponent( ac, 1, 1, 15 );
			ac = new AddonComponent( 2254 );
			ac.Name = "Sleigh";
			AddComponent( ac, -1, -1, 21 );
			ac = new AddonComponent( 2254 );
			ac.Name = "Sleigh";
			AddComponent( ac, 1, -1, 16 );
			ac = new AddonComponent( 2254 );
			ac.Name = "Sleigh";
			AddComponent( ac, 0, -1, 16 );
			ac = new AddonComponent( 2254 );
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 11210 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, -2, -1, 11 );
			ac = new AddonComponent( 11503 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, 1, 0, 11 );
			ac = new AddonComponent( 11503 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, 1, 1, 11 );
			ac = new AddonComponent( 11504 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, 0, -1, 11 );
			ac = new AddonComponent( 11504 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, 1, -1, 11 );
			ac = new AddonComponent( 11504 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, 1, 1, 11 );
			ac = new AddonComponent( 11505 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, -2, 1, 11 );
			ac = new AddonComponent( 11505 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, -2, 0, 11 );
			ac = new AddonComponent( 11506 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, -1, 1, 10 );
			ac = new AddonComponent( 11506 );
			ac.Hue = 138;
			ac.Name = "Sleigh";
			AddComponent( ac, -1, -1, 11 );
			ac = new AddonComponent( 2254 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 2, -1, 10 );
			ac = new AddonComponent( 2254 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 0, 2, 13 );
			ac = new AddonComponent( 2254 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 1, 2, 13 );
			ac = new AddonComponent( 413 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 1, 2, 3 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1108;
			ac.Name = "Sleigh";
			AddComponent( ac, -1, 1, 9 );
			ac = new AddonComponent( 413 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 0, 2, 3 );
			ac = new AddonComponent( 413 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 2, 2, 3 );
			ac = new AddonComponent( 2254 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, -1, 2, 13 );
			ac = new AddonComponent( 2254 );
			ac.Hue = 2101;
			ac.Name = "Runner";
			AddComponent( ac, 2, 2, 13 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1108;
			ac.Name = "Sleigh";
			AddComponent( ac, 0, 0, 9 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1108;
			ac.Name = "Sleigh";
			AddComponent( ac, 1, 0, 9 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1108;
			ac.Name = "Sleigh";
			AddComponent( ac, 1, 1, 9 );
			ac = new AddonComponent( 1981 );
			ac.Hue = 1108;
			ac.Name = "Sleigh";
			AddComponent( ac, 0, 1, 9 );

		}

		public SantasSleighNew1Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SantasSleighNew1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SantasSleighNew1Addon();
			}
		}

		[Constructable]
		public SantasSleighNew1AddonDeed()
		{
			Name = "SantasSleighNew1";
		}

		public SantasSleighNew1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}