/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SantasSleighSmallAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SantasSleighSmallAddonDeed();
			}
		}

		[ Constructable ]
		public SantasSleighSmallAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 14964 );
			ac.Name = "Santa's Sleigh";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 14963 );
			ac.Name = "Santa's Sleigh";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 9002 );
			AddComponent( ac, 1, 1, 18 );
			ac = new AddonComponent( 3740 );
			ac.Name = "Toy Drum";
			AddComponent( ac, 1, 1, 21 );
			ac = new AddonComponent( 3169 );
			ac.Name = "Holly";
			AddComponent( ac, 1, 1, 12 );
			ac = new AddonComponent( 3962 );
			ac.Hue = 38;
			ac.Name = "Berry";
			AddComponent( ac, 1, 1, 14 );

		}

		public SantasSleighSmallAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SantasSleighSmallAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SantasSleighSmallAddon();
			}
		}

		[Constructable]
		public SantasSleighSmallAddonDeed()
		{
			Name = "SantasSleighSmall";
		}

		public SantasSleighSmallAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}