
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TreeSkirtSnowAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TreeSkirtSnowAddonDeed();
			}
		}

		[ Constructable ]
		public TreeSkirtSnowAddon()
		{



			AddComplexComponent( (BaseAddon) this, 6077, 0, 1, 0, 0, -1, "Snow Tree Skirt", 1);// 1
			AddComplexComponent( (BaseAddon) this, 6077, 1, 0, 0, 0, -1, "Snow Tree Skirt", 1);// 2
			AddComplexComponent( (BaseAddon) this, 6077, 0, -1, 0, 0, -1, "Snow Tree Skirt", 1);// 3
			AddComplexComponent( (BaseAddon) this, 6078, 0, 0, 0, 0, -1, "Snow Tree Skirt", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6079, 1, 1, 0, 0, -1, "Snow Tree Skirt", 1);// 5
			AddComplexComponent( (BaseAddon) this, 6080, 1, -1, 0, 0, -1, "Snow Tree Skirt", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6077, 2, 0, 0, 0, -1, "Snow Tree Skirt", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6078, 2, 1, 0, 0, -1, "Snow Tree Skirt", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6079, 2, -1, 0, 0, -1, "Snow Tree Skirt", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6089, 1, 2, 0, 0, -1, "Snow Tree Skirt", 1);// 10
			AddComplexComponent( (BaseAddon) this, 6089, 2, 2, 0, 0, -1, "Snow Tree Skirt", 1);// 11
			AddComplexComponent( (BaseAddon) this, 6089, 0, 2, 0, 0, -1, "Snow Tree Skirt", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6090, -1, 1, 0, 0, -1, "Snow Tree Skirt", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6090, -1, 0, 0, 0, -1, "Snow Tree Skirt", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6090, -1, -1, 0, 0, -1, "Snow Tree Skirt", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6091, 0, -2, 0, 0, -1, "Snow Tree Skirt", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6091, 1, -2, 0, 0, -1, "Snow Tree Skirt", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6091, 2, -2, 0, 0, -1, "Snow Tree Skirt", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6088, -1, 2, 0, 0, -1, "Snow Tree Skirt", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6085, -1, -2, 0, 0, -1, "Snow Tree Skirt", 1);// 20

		}

		public TreeSkirtSnowAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TreeSkirtSnowAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TreeSkirtSnowAddon();
			}
		}

		[Constructable]
		public TreeSkirtSnowAddonDeed()
		{
			Name = "TreeSkirtSnow";
		}

		public TreeSkirtSnowAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}