
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WhiteWinterTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {5940, -1, -2, 0}, {3286, 1, 2, 0}// 1	3	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new WhiteWinterTreeAddonDeed();
			}
		}

		[ Constructable ]
		public WhiteWinterTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3287, 1, 2, 0, 2744, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 7437, 1, 2, 3, 1153, -1, "snow", 1);// 4
			AddComplexComponent( (BaseAddon) this, 7438, 1, 3, 11, 1153, -1, "snow", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7423, 1, 2, 16, 1153, -1, "snow", 1);// 6
			AddComplexComponent( (BaseAddon) this, 7427, 1, 2, 26, 1153, -1, "snow", 1);// 7
			AddComplexComponent( (BaseAddon) this, 4651, 1, 2, 20, 1153, -1, "snow", 1);// 8
			AddComplexComponent( (BaseAddon) this, 7417, 1, 2, 12, 1153, -1, "snow", 1);// 9
			AddComplexComponent( (BaseAddon) this, 7423, 1, 2, 33, 1153, -1, "snow", 1);// 10
			AddComplexComponent( (BaseAddon) this, 7430, 1, 3, 16, 1153, -1, "snow", 1);// 11

		}

		public WhiteWinterTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class WhiteWinterTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new WhiteWinterTreeAddon();
			}
		}

		[Constructable]
		public WhiteWinterTreeAddonDeed()
		{
			Name = "WhiteWinterTree";
		}

		public WhiteWinterTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}