/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FandancerStairsAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FandancerStairsAddonDeed();
			}
		}

		[ Constructable ]
		public FandancerStairsAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 9459 );
			ac.Name = "stairs";
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 9458 );
			ac.Name = "stairs";
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 10087 );
			AddComponent( ac, 0, 2, 8 );
			ac = new AddonComponent( 9457 );
			ac.Name = "stairs";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 9456 );
			ac.Name = "stairs";
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 10087 );
			AddComponent( ac, 2, 1, 18 );
			ac = new AddonComponent( 10391 );
			ac.Hue = 1509;
			ac.Name = "table";
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 9269 );
			ac.Hue = 1509;
			ac.Name = "table";
			AddComponent( ac, 0, 0, 10 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			ac.Name = "table";
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 10384 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 10387 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 10403 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 10030 );
			ac.Hue = 1509;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 9405 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 0, 0, 12 );
			ac = new AddonComponent( 10382 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 10385 );
			AddComponent( ac, 1, -1, 0 );

		}

		public FandancerStairsAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FandancerStairsAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FandancerStairsAddon();
			}
		}

		[Constructable]
		public FandancerStairsAddonDeed()
		{
			Name = "FandancerStairs";
		}

		public FandancerStairsAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}